# ─────────────────────────────────────────────────────────────────────────────
# GTLE Practice Question Bank
# Ghana Teacher Licensure Examination – starter questions across 4 domains
# ─────────────────────────────────────────────────────────────────────────────

GTLE_QUESTION_BANK = [
    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 1: LITERACY (20 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'literacy',
        'topic': 'Phonemic Awareness',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which of the following is the best example of a phonemic awareness activity?',
        'option_a': 'Asking pupils to identify the first sound in the word "ball"',
        'option_b': 'Asking pupils to copy the word "ball" from the board',
        'option_c': 'Asking pupils to draw a picture of a ball',
        'option_d': 'Asking pupils to spell the word "ball" in their exercise books',
        'correct_option': 'A',
        'explanation': 'Phonemic awareness involves the ability to hear, identify, and manipulate individual sounds (phonemes) in spoken words. Identifying the first sound in a word is a core phonemic awareness skill.',
    },
    {
        'domain': 'literacy',
        'topic': 'Reading Comprehension',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A teacher wants to develop inferential comprehension skills in Basic 5 pupils. Which question type is most appropriate?',
        'option_a': 'What is the title of the passage?',
        'option_b': 'Why do you think the character made that decision?',
        'option_c': 'List three characters mentioned in the passage.',
        'option_d': 'How many paragraphs are in the passage?',
        'correct_option': 'B',
        'explanation': 'Inferential comprehension requires readers to go beyond the literal text to make deductions, draw conclusions, and understand implied meanings. Asking "why" a character acted a certain way requires inference.',
    },
    {
        'domain': 'literacy',
        'topic': 'Vocabulary Development',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which strategy is most effective for teaching new vocabulary to early-grade learners?',
        'option_a': 'Giving pupils a dictionary to look up words independently',
        'option_b': 'Using the words in meaningful context with pictures and actions',
        'option_c': 'Writing the words and definitions on the board for pupils to copy',
        'option_d': 'Assigning the words as homework for parents to teach',
        'correct_option': 'B',
        'explanation': 'Young learners acquire vocabulary best through multi-sensory, contextual approaches. Using words in meaningful sentences supported by visuals and actions creates deeper understanding than rote copying.',
    },
    {
        'domain': 'literacy',
        'topic': 'Writing Process',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which stage of the writing process focuses on organizing ideas before actual writing begins?',
        'option_a': 'Drafting',
        'option_b': 'Pre-writing',
        'option_c': 'Revising',
        'option_d': 'Editing',
        'correct_option': 'B',
        'explanation': 'Pre-writing is the planning stage where writers brainstorm, organize ideas, create outlines, and gather information before beginning to draft. It lays the foundation for effective composition.',
    },
    {
        'domain': 'literacy',
        'topic': 'Phonics',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'In phonics instruction, the term "blend" refers to:',
        'option_a': 'Two or more consonants that appear together but each keeps its own sound',
        'option_b': 'Two vowels that make one sound',
        'option_c': 'A silent letter in a word',
        'option_d': 'The stress pattern in a multi-syllable word',
        'correct_option': 'A',
        'explanation': 'A consonant blend (or cluster) consists of two or more consonants placed together where each consonant retains its individual sound, such as "bl" in "blend" or "str" in "strong".',
    },
    {
        'domain': 'literacy',
        'topic': 'Fluency',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A teacher notices a pupil reads word-by-word without expression. The most appropriate intervention is:',
        'option_a': 'Assign more silent reading homework',
        'option_b': 'Model fluent reading and use repeated reading practice',
        'option_c': 'Move the pupil to a lower reading level permanently',
        'option_d': 'Test the pupil for a learning disability',
        'correct_option': 'B',
        'explanation': 'Reading fluency develops through hearing fluent reading模led and through repeated practice with the same text. This builds automaticity, proper phrasing, and expression (prosody).',
    },
    {
        'domain': 'literacy',
        'topic': 'Oral Language',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which classroom activity best promotes oral language development?',
        'option_a': 'Copying notes from the board',
        'option_b': 'Think-pair-share discussions on a topic',
        'option_c': 'Silent sustained reading',
        'option_d': 'Completing fill-in-the-blank worksheets',
        'correct_option': 'B',
        'explanation': 'Think-pair-share gives every pupil an opportunity to formulate thoughts and articulate them verbally to a partner, building confidence and oral language skills through structured interaction.',
    },
    {
        'domain': 'literacy',
        'topic': 'Reading Comprehension',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Which of the following describes the "reciprocal teaching" strategy?',
        'option_a': 'The teacher reads aloud while pupils listen silently',
        'option_b': 'Pupils take turns being "teacher," using predicting, questioning, clarifying, and summarizing',
        'option_c': 'Pupils exchange exercise books and mark each other\'s work',
        'option_d': 'The teacher asks questions and pupils respond in chorus',
        'correct_option': 'B',
        'explanation': 'Reciprocal teaching (Palincsar & Brown, 1984) involves pupils taking turns leading discussion using four strategies: predicting, questioning, clarifying, and summarizing. It develops metacognitive reading skills.',
    },
    {
        'domain': 'literacy',
        'topic': 'Print Concepts',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A KG2 teacher holds up a book and asks "Where do I start reading?" This is teaching:',
        'option_a': 'Phonemic awareness',
        'option_b': 'Print concepts',
        'option_c': 'Fluency',
        'option_d': 'Vocabulary',
        'correct_option': 'B',
        'explanation': 'Print concepts (or concepts of print) include understanding that text is read from left to right, top to bottom, and front to back. Showing where reading starts is a fundamental print concept lesson.',
    },
    {
        'domain': 'literacy',
        'topic': 'Writing',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which approach to writing instruction allows pupils to write about topics of personal interest and share with peers?',
        'option_a': 'Dictation',
        'option_b': 'Writers\' workshop',
        'option_c': 'Copying exercises',
        'option_d': 'Grammar drills',
        'correct_option': 'B',
        'explanation': 'Writers\' workshop gives pupils choice of topic, time to write at their own pace, and opportunities for peer sharing and feedback. It develops authentic writing skills and motivation.',
    },
    {
        'domain': 'literacy',
        'topic': 'Assessment',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A running record in literacy assessment is used primarily to:',
        'option_a': 'Test spelling ability',
        'option_b': 'Assess oral reading accuracy and analyze reading behaviors',
        'option_c': 'Evaluate handwriting neatness',
        'option_d': 'Measure vocabulary size',
        'correct_option': 'B',
        'explanation': 'A running record is an assessment tool where the teacher records a pupil\'s reading behaviors during oral reading, noting accuracy, self-corrections, substitutions, and omissions to determine reading level and strategies used.',
    },
    {
        'domain': 'literacy',
        'topic': 'Phonics',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A digraph differs from a blend because a digraph:',
        'option_a': 'Contains only vowels',
        'option_b': 'Produces a single new sound from two letters',
        'option_c': 'Is always at the end of a word',
        'option_d': 'Contains three or more consonants',
        'correct_option': 'B',
        'explanation': 'A digraph consists of two letters that combine to produce one new sound (e.g., "sh," "ch," "th"), unlike a blend where each letter retains its own sound.',
    },
    {
        'domain': 'literacy',
        'topic': 'Guided Reading',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'In guided reading, the teacher\'s primary role is to:',
        'option_a': 'Read the text aloud to the group',
        'option_b': 'Support pupils as they read texts at their instructional level, prompting strategy use',
        'option_c': 'Assign comprehension questions after reading',
        'option_d': 'Correct every error the pupil makes immediately',
        'correct_option': 'B',
        'explanation': 'In guided reading, the teacher works with a small group reading at a similar level. The teacher\'s role is to introduce the text, then observe and prompt pupils to apply reading strategies independently.',
    },
    {
        'domain': 'literacy',
        'topic': 'Bilingual Education',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'In Ghana\'s language-in-education policy, the mother tongue is used as medium of instruction from:',
        'option_a': 'KG1 to Basic 3',
        'option_b': 'KG1 to Basic 6',
        'option_c': 'Basic 1 to Basic 2 only',
        'option_d': 'KG1 to JHS 3',
        'correct_option': 'A',
        'explanation': 'Ghana\'s National Literacy Acceleration Program (NALAP) and language policy use the local Ghanaian language as the primary medium of instruction from Kindergarten through Basic 3 (lower primary), transitioning to English from Basic 4.',
    },
    {
        'domain': 'literacy',
        'topic': 'Reading Comprehension',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Bloom\'s Taxonomy level of "evaluate" in reading comprehension would be demonstrated by asking pupils to:',
        'option_a': 'Retell the main events of a story',
        'option_b': 'Judge whether the author\'s argument is convincing, giving reasons',
        'option_c': 'Define the meaning of a word from the passage',
        'option_d': 'List the characters in the story',
        'correct_option': 'B',
        'explanation': 'Evaluation is one of the highest levels of Bloom\'s Taxonomy, requiring pupils to make judgments based on criteria. Assessing whether an argument is convincing requires critical analysis and evaluation.',
    },
    {
        'domain': 'literacy',
        'topic': 'Differentiation',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A teacher has pupils at different reading levels in the same class. The best approach is to:',
        'option_a': 'Teach only to the average level and hope others catch up',
        'option_b': 'Use leveled texts and flexible grouping based on reading ability',
        'option_c': 'Have advanced readers wait while struggling readers catch up',
        'option_d': 'Give all pupils the same text and same assignment',
        'correct_option': 'B',
        'explanation': 'Differentiated instruction using leveled texts ensures each pupil reads at their instructional level (not too easy, not too hard). Flexible grouping allows teachers to target specific skill needs.',
    },
    {
        'domain': 'literacy',
        'topic': 'Spelling',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Invented spelling in early writing should be:',
        'option_a': 'Immediately corrected every time',
        'option_b': 'Encouraged as a developmental stage while gradually teaching conventional spelling',
        'option_c': 'Ignored completely and never addressed',
        'option_d': 'Punished to discourage bad habits',
        'correct_option': 'B',
        'explanation': 'Invented (or developmental) spelling reflects a child\'s growing understanding of sound-letter relationships. It should be accepted as a natural stage while conventional spelling is gradually taught through systematic instruction.',
    },
    {
        'domain': 'literacy',
        'topic': 'Listening Skills',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which technique best develops active listening skills in Basic 2 pupils?',
        'option_a': 'Having pupils sit quietly with hands folded',
        'option_b': 'Read-aloud followed by asking pupils to retell or answer questions',
        'option_c': 'Playing background music while pupils work silently',
        'option_d': 'Having pupils copy from the board without talking',
        'correct_option': 'B',
        'explanation': 'Active listening requires engagement with the content. Read-alouds followed by retelling or answering questions give pupils a purpose for listening and develop their comprehension of spoken language.',
    },
    {
        'domain': 'literacy',
        'topic': 'Shared Reading',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The primary purpose of shared reading with a Big Book in KG is to:',
        'option_a': 'Keep pupils quiet and occupied',
        'option_b': 'Model reading strategies while pupils follow along and participate',
        'option_c': 'Test pupils\' ability to read independently',
        'option_d': 'Teach pupils to memorize the text word for word',
        'correct_option': 'B',
        'explanation': 'Shared reading uses enlarged text (Big Books) so all pupils can see. The teacher models fluent reading, points to words, and invites participation, building concepts of print, vocabulary, and reading enjoyment.',
    },
    {
        'domain': 'literacy',
        'topic': 'Grammar',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Research suggests the most effective way to teach grammar in primary school is through:',
        'option_a': 'Isolated grammar drills and exercises',
        'option_b': 'Integrating grammar instruction within meaningful reading and writing activities',
        'option_c': 'Having pupils memorize grammar rules without application',
        'option_d': 'Postponing grammar instruction until JHS',
        'correct_option': 'B',
        'explanation': 'Research consistently shows that grammar taught in context — within authentic reading and writing — transfers better to pupils\' own writing than isolated drill-and-practice exercises.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 2: NUMERACY (20 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'numeracy',
        'topic': 'Number Sense',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which manipulative is most appropriate for teaching place value to Basic 2 pupils?',
        'option_a': 'A ruler',
        'option_b': 'Base-ten blocks (Dienes blocks)',
        'option_c': 'A protractor',
        'option_d': 'A calendar',
        'correct_option': 'B',
        'explanation': 'Base-ten blocks (also called Dienes blocks) physically represent ones, tens, hundreds, and thousands, making the abstract concept of place value concrete and visible for young learners.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Problem Solving',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Polya\'s four-step problem-solving process includes: Understand the problem, Devise a plan, Carry out the plan, and:',
        'option_a': 'Memorize the formula',
        'option_b': 'Look back and check',
        'option_c': 'Copy the answer from a friend',
        'option_d': 'Move to the next problem immediately',
        'correct_option': 'B',
        'explanation': 'George Polya\'s (1945) four steps are: (1) Understand the problem, (2) Devise a plan, (3) Carry out the plan, (4) Look back — reflecting on the solution, checking for reasonableness, and considering alternative methods.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Fractions',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'When introducing fractions to Basic 4 pupils, the teacher should first:',
        'option_a': 'Teach the rules for adding fractions',
        'option_b': 'Use concrete objects to show equal parts of a whole',
        'option_c': 'Give fraction problems on the board to solve',
        'option_d': 'Explain the terms "numerator" and "denominator"',
        'correct_option': 'B',
        'explanation': 'The Concrete-Representational-Abstract (CRA) approach requires starting with concrete manipulatives. Pupils should physically divide objects into equal parts before moving to fraction notation and terminology.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Multiplication',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which of the following activities best helps pupils understand multiplication as repeated addition?',
        'option_a': 'Memorizing the multiplication table through chanting',
        'option_b': 'Grouping counters into equal sets and counting the total',
        'option_c': 'Writing multiplication facts ten times each',
        'option_d': 'Completing timed multiplication quizzes',
        'correct_option': 'B',
        'explanation': 'Grouping physical objects (counters, bottle caps) into equal sets — e.g., 3 groups of 4 — helps pupils see that 3 × 4 means adding 4 three times, building conceptual understanding before procedural fluency.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Geometry',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'According to the Van Hiele model of geometric thinking, at which level do pupils recognize shapes by appearance only?',
        'option_a': 'Level 0 – Visualization',
        'option_b': 'Level 1 – Analysis',
        'option_c': 'Level 2 – Informal Deduction',
        'option_d': 'Level 3 – Formal Deduction',
        'correct_option': 'A',
        'explanation': 'At the Van Hiele Visualization level (Level 0), pupils recognize shapes holistically by their overall appearance — "it looks like a rectangle" — without analyzing specific properties like number of sides or angle measures.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Measurement',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Before teaching standard units of measurement, pupils should first experience:',
        'option_a': 'Converting between metric and imperial units',
        'option_b': 'Measuring with non-standard units like hand spans and foot lengths',
        'option_c': 'Memorizing the metric conversion table',
        'option_d': 'Using only rulers and tape measures',
        'correct_option': 'B',
        'explanation': 'Using non-standard units (hand spans, pencils, cups) helps pupils understand the concept of measurement — comparing an attribute against a unit — before introducing standard units like centimeters and liters.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Data Handling',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A Basic 5 teacher asks pupils to collect data on favorite fruits and display results. The most appropriate graph type is:',
        'option_a': 'Line graph',
        'option_b': 'Bar chart or pictograph',
        'option_c': 'Scatter plot',
        'option_d': 'Histogram',
        'correct_option': 'B',
        'explanation': 'Categorical data (favorite fruits) is best represented using bar charts or pictographs. Line graphs are for showing change over time, scatter plots for correlations, and histograms for continuous data distributions.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Subtraction',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A pupil solves 43 − 27 = 24. The most likely error is:',
        'option_a': 'Incorrect addition',
        'option_b': 'Subtracting the smaller digit from the larger in each column without regrouping',
        'option_c': 'Misreading the numbers',
        'option_d': 'Using the wrong operation',
        'correct_option': 'B',
        'explanation': 'The pupil likely computed 7 − 3 = 4 (ones column) and 4 − 2 = 2 (tens column), always subtracting smaller from larger without regrouping/borrowing. This is a very common subtraction error in early grades.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Number Patterns',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Identifying the next number in the sequence 2, 5, 8, 11, ___ develops which mathematical skill?',
        'option_a': 'Spatial reasoning',
        'option_b': 'Pattern recognition and algebraic thinking',
        'option_c': 'Geometric visualization',
        'option_d': 'Data analysis',
        'correct_option': 'B',
        'explanation': 'Number patterns develop algebraic thinking — the ability to identify rules and relationships. Here the rule is "add 3," so the next number is 14. This foundational skill prepares pupils for algebra.',
    },
    {
        'domain': 'numeracy',
        'topic': 'CRA Approach',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'In the Concrete-Representational-Abstract (CRA) approach, the "representational" stage involves:',
        'option_a': 'Using physical objects to model the concept',
        'option_b': 'Drawing pictures, diagrams, or tally marks to represent the concept',
        'option_c': 'Using only numbers and symbols',
        'option_d': 'Reciting math facts from memory',
        'correct_option': 'B',
        'explanation': 'The Representational (or Pictorial) stage bridges concrete and abstract. Pupils draw pictures, diagrams, bar models, or tally marks to represent what they previously did with physical objects, before moving to abstract symbols.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Division',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which real-life context best illustrates the "sharing" model of division for Basic 3 pupils?',
        'option_a': 'How many groups of 4 can be made from 20 items?',
        'option_b': 'Sharing 12 pencils equally among 3 pupils',
        'option_c': 'Finding the product of 4 and 5',
        'option_d': 'Counting back from 20 by 4s',
        'correct_option': 'B',
        'explanation': 'Division has two models: sharing (partitive) and grouping (measurement). Sharing 12 pencils among 3 pupils illustrates the partitive model — dividing a total into a known number of equal groups.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Math Anxiety',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which classroom practice is most likely to reduce math anxiety in pupils?',
        'option_a': 'Frequent timed tests with public scoring',
        'option_b': 'Creating a safe environment where mistakes are treated as learning opportunities',
        'option_c': 'Comparing pupils\' scores publicly on a class chart',
        'option_d': 'Giving extra homework to struggling pupils only',
        'correct_option': 'B',
        'explanation': 'Math anxiety is reduced when pupils feel safe to make mistakes and learn from them. A supportive classroom culture that values process over speed, and effort over natural ability, builds confidence.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Estimation',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Teaching pupils to estimate before computing answers helps them to:',
        'option_a': 'Avoid doing any calculations',
        'option_b': 'Check whether their final answer is reasonable',
        'option_c': 'Skip steps in the problem',
        'option_d': 'Guess randomly',
        'correct_option': 'B',
        'explanation': 'Estimation develops number sense and serves as a self-checking strategy. If a pupil estimates 48 + 33 as "about 80" and gets 81, they can verify reasonableness. If they get 811, they know to recheck.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Word Problems',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A pupil can compute 45 + 28 correctly but fails when the same problem is presented as a word problem. This suggests difficulty with:',
        'option_a': 'Computational fluency',
        'option_b': 'Reading comprehension and translating language to mathematical operations',
        'option_c': 'Number recognition',
        'option_d': 'Fine motor skills',
        'correct_option': 'B',
        'explanation': 'When a pupil can compute but not solve word problems, the barrier is typically comprehension — understanding the context, identifying relevant information, and translating the verbal description into a mathematical operation.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Time',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The best way to teach telling time to Basic 1 pupils is:',
        'option_a': 'Start with reading digital clocks',
        'option_b': 'Use a demonstration clock with movable hands, starting with hours',
        'option_c': 'Have pupils memorize all the minute positions first',
        'option_d': 'Show video animations only',
        'correct_option': 'B',
        'explanation': 'A demonstration clock with movable hands allows pupils to physically manipulate the hour and minute hands. Start with telling time to the hour, then half-hour, quarter-hour, and finally to the minute.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Mental Math',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which mental math strategy involves breaking 47 + 36 into (47 + 30) + 6?',
        'option_a': 'Compensation',
        'option_b': 'Decomposition (partitioning)',
        'option_c': 'Counting on',
        'option_d': 'Rounding',
        'correct_option': 'B',
        'explanation': 'Decomposition (or partitioning) involves breaking one number into parts that are easier to work with. Here, 36 is split into 30 and 6, allowing step-by-step mental addition: 47 + 30 = 77, then 77 + 6 = 83.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Assessment',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A teacher who asks a pupil to explain their solution strategy during a math lesson is using:',
        'option_a': 'Summative assessment',
        'option_b': 'Formative assessment through mathematical discourse',
        'option_c': 'Standardized testing',
        'option_d': 'Norm-referenced assessment',
        'correct_option': 'B',
        'explanation': 'Asking pupils to explain their thinking is formative assessment — gathering real-time information about understanding. Mathematical discourse reveals misconceptions, validates strategies, and deepens conceptual understanding.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Money',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'When teaching money concepts, it is important to use:',
        'option_a': 'Only pictures of coins and notes in a textbook',
        'option_b': 'Play money and real-world shopping role-play activities',
        'option_c': 'Only abstract written problems about money',
        'option_d': 'Calculator-based exercises only',
        'correct_option': 'B',
        'explanation': 'Play money and shopping role-play make money concepts concrete and relevant. Pupils handle "money," make purchases, calculate change — all of which build practical numeracy skills.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Algebra Readiness',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'In the equation □ + 5 = 12, using a box symbol instead of a letter variable is appropriate for primary pupils because:',
        'option_a': 'Letters are only for secondary school mathematics',
        'option_b': 'It builds the concept of an unknown without the abstraction of letter variables',
        'option_c': 'Boxes are easier to draw',
        'option_d': 'It prevents pupils from learning algebra',
        'correct_option': 'B',
        'explanation': 'Using symbols like boxes or blank spaces introduces the concept of "unknown" in a developmentally appropriate way. It prepares pupils for formal algebraic notation while keeping the representation concrete and accessible.',
    },
    {
        'domain': 'numeracy',
        'topic': 'Counting',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'One-to-one correspondence in counting means:',
        'option_a': 'Counting by twos',
        'option_b': 'Matching each object with exactly one number word in sequence',
        'option_c': 'Writing numbers from 1 to 100',
        'option_d': 'Adding two numbers together',
        'correct_option': 'B',
        'explanation': 'One-to-one correspondence is a fundamental counting principle where each object in a set is paired with exactly one number word, and each number word is used only once. It is essential for meaningful counting.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 3: PEDAGOGICAL KNOWLEDGE (20 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'pedagogy',
        'topic': 'Learning Theories',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Piaget\'s theory of cognitive development identifies four stages. The "concrete operational" stage (ages 7-11) is characterized by:',
        'option_a': 'Abstract hypothetical reasoning',
        'option_b': 'Logical thinking about concrete objects and events',
        'option_c': 'Purely sensory and motor interactions',
        'option_d': 'Magical thinking and egocentrism',
        'correct_option': 'B',
        'explanation': 'In the Concrete Operational stage (ages 7-11), children develop logical thinking about concrete (real, physical) situations. They understand conservation, classification, and seriation but struggle with abstract reasoning.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Vygotsky',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Vygotsky\'s "Zone of Proximal Development" (ZPD) refers to:',
        'option_a': 'What a child can do independently',
        'option_b': 'The gap between what a child can do alone and what they can do with guidance',
        'option_c': 'The physical space around a child\'s desk',
        'option_d': 'The child\'s chronological age',
        'correct_option': 'B',
        'explanation': 'The ZPD is the distance between what a learner can do independently and what they can achieve with the help of a more knowledgeable other (teacher, peer). Effective teaching targets this zone.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Scaffolding',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'In teaching, "scaffolding" means:',
        'option_a': 'Building physical structures in the classroom',
        'option_b': 'Providing temporary support that is gradually removed as the learner gains competence',
        'option_c': 'Giving pupils the answers to help them finish faster',
        'option_d': 'Repeating the same lesson multiple times',
        'correct_option': 'B',
        'explanation': 'Scaffolding (Bruner) provides temporary, structured support — modeling, hints, prompts, graphic organizers — that helps learners accomplish tasks in their ZPD. Support is gradually withdrawn as competence grows.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Bloom\'s Taxonomy',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'In Bloom\'s revised taxonomy, which level requires the HIGHEST order thinking?',
        'option_a': 'Apply',
        'option_b': 'Analyze',
        'option_c': 'Create',
        'option_d': 'Evaluate',
        'correct_option': 'C',
        'explanation': 'Bloom\'s revised taxonomy (Anderson & Krathwohl, 2001) from lowest to highest: Remember, Understand, Apply, Analyze, Evaluate, Create. "Create" is the highest level, requiring synthesis of knowledge to produce something new.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Lesson Planning',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A well-written lesson objective should be:',
        'option_a': 'Vague so it covers many possible outcomes',
        'option_b': 'Specific, measurable, achievable, relevant, and time-bound',
        'option_c': 'Written in language only the teacher understands',
        'option_d': 'Focused on what the teacher will do, not what pupils will learn',
        'correct_option': 'B',
        'explanation': 'Effective lesson objectives follow SMART criteria — they clearly state what pupils will be able to do by the end of the lesson in observable, measurable terms. This guides both instruction and assessment.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Differentiated Instruction',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Differentiated instruction can be achieved by modifying:',
        'option_a': 'Only the content of the lesson',
        'option_b': 'Content, process, product, and/or learning environment',
        'option_c': 'Only the final assessment',
        'option_d': 'Only the seating arrangement',
        'correct_option': 'B',
        'explanation': 'Tomlinson\'s model of differentiation identifies four elements teachers can modify: Content (what is taught), Process (how pupils learn), Product (how pupils demonstrate learning), and Learning Environment (classroom conditions).',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Assessment',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Formative assessment differs from summative assessment in that formative assessment:',
        'option_a': 'Is only done at the end of the term',
        'option_b': 'Occurs during learning to monitor progress and adjust instruction',
        'option_c': 'Always results in a grade on the report card',
        'option_d': 'Is only administered by the headteacher',
        'correct_option': 'B',
        'explanation': 'Formative assessment is ongoing assessment FOR learning — quizzes, observations, questioning, exit tickets — used to monitor pupil understanding and adjust teaching in real-time. Summative is assessment OF learning at the end.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Learning Styles',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Howard Gardner\'s theory of Multiple Intelligences suggests that:',
        'option_a': 'Intelligence is a single, fixed ability measured by IQ tests',
        'option_b': 'People have different kinds of intelligences and learn in different ways',
        'option_c': 'Only linguistic and logical-mathematical abilities matter in school',
        'option_d': 'Intelligence cannot be developed through education',
        'correct_option': 'B',
        'explanation': 'Gardner proposed at least 8 intelligences (linguistic, logical-mathematical, spatial, bodily-kinesthetic, musical, interpersonal, intrapersonal, naturalistic), suggesting varied learning pathways for different learners.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Cooperative Learning',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'For cooperative learning to be effective, groups must have:',
        'option_a': 'Only high-achieving pupils working together',
        'option_b': 'Positive interdependence, individual accountability, and social skills',
        'option_c': 'As many pupils as possible in each group',
        'option_d': 'A competitive scoring system between groups',
        'correct_option': 'B',
        'explanation': 'Johnson & Johnson identified five essential elements of cooperative learning: positive interdependence, individual accountability, promotive interaction, social skills, and group processing. All members must contribute and be accountable.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Questioning Techniques',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A teacher asks: "What would happen if there were no trees?" This is an example of:',
        'option_a': 'A closed question',
        'option_b': 'A divergent (open-ended) question',
        'option_c': 'A recall question',
        'option_d': 'A yes/no question',
        'correct_option': 'B',
        'explanation': 'Divergent (open-ended) questions have multiple possible answers and require higher-order thinking — analysis, synthesis, evaluation. They stimulate critical thinking and creativity, unlike convergent questions with one correct answer.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Behaviorism',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Positive reinforcement in the classroom means:',
        'option_a': 'Punishing bad behavior',
        'option_b': 'Adding a desirable stimulus after a behavior to increase the likelihood of that behavior',
        'option_c': 'Removing privileges',
        'option_d': 'Ignoring all behavior',
        'correct_option': 'B',
        'explanation': 'In Skinner\'s operant conditioning, positive reinforcement adds something pleasant (praise, stickers, extra playtime) after a desired behavior, increasing the probability the behavior will occur again.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Constructivism',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The constructivist approach to teaching suggests that:',
        'option_a': 'Teachers should transmit knowledge directly through lectures',
        'option_b': 'Learners actively build understanding through experience and interaction with prior knowledge',
        'option_c': 'Pupils learn best by memorizing facts',
        'option_d': 'The curriculum should be fixed with no room for pupil input',
        'correct_option': 'B',
        'explanation': 'Constructivism (Piaget, Vygotsky, Dewey) holds that learners construct knowledge by connecting new experiences to existing understanding. Teachers facilitate discovery rather than transmit information.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Inclusive Education',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Inclusive education means:',
        'option_a': 'Placing pupils with disabilities in separate special schools',
        'option_b': 'Ensuring all learners, including those with special needs, learn together in regular classrooms with appropriate support',
        'option_c': 'Excluding slow learners from class activities',
        'option_d': 'Teaching only gifted pupils',
        'correct_option': 'B',
        'explanation': 'Inclusive education ensures all learners — regardless of ability, disability, gender, or background — participate in the same regular classroom with appropriate accommodations and support.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Motivation',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A pupil who reads extra books because they enjoy learning is displaying:',
        'option_a': 'Extrinsic motivation',
        'option_b': 'Intrinsic motivation',
        'option_c': 'Negative reinforcement',
        'option_d': 'Classical conditioning',
        'correct_option': 'B',
        'explanation': 'Intrinsic motivation comes from within — the inherent satisfaction, curiosity, or enjoyment of the activity itself. Extrinsic motivation comes from external rewards like grades, prizes, or avoiding punishment.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Curriculum',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Ghana\'s Standards-Based Curriculum (2019) emphasizes:',
        'option_a': 'Rote memorization and teacher-centered instruction',
        'option_b': 'Core competencies, learner-centered approaches, and 21st-century skills',
        'option_c': 'Only examination preparation',
        'option_d': 'Eliminating all assessments',
        'correct_option': 'B',
        'explanation': 'Ghana\'s Standards-Based Curriculum focuses on developing core competencies (critical thinking, creativity, communication, collaboration), values, and attitudes through learner-centered pedagogies aligned with 21st-century needs.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Teaching Methods',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The "I Do, We Do, You Do" model of instruction represents:',
        'option_a': 'Discovery-based learning',
        'option_b': 'Gradual release of responsibility from teacher to learner',
        'option_c': 'Test-based teaching',
        'option_d': 'Peer assessment',
        'correct_option': 'B',
        'explanation': 'The Gradual Release of Responsibility model moves from teacher modeling (I Do), to guided practice (We Do), to independent practice (You Do), systematically transferring ownership of learning to pupils.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Feedback',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which type of teacher feedback is most effective for improving pupil learning?',
        'option_a': 'Simply writing "Good" or "Poor" on pupils\' work',
        'option_b': 'Specific, descriptive feedback that tells the pupil what was done well and what to improve',
        'option_c': 'Only giving numerical scores without comments',
        'option_d': 'Delayed feedback given weeks after the assignment',
        'correct_option': 'B',
        'explanation': 'Research (Hattie & Timperley) shows effective feedback is timely, specific, and actionable — telling pupils exactly what was strong, what needs improvement, and how to improve. Generic praise or grades alone provide little learning guidance.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Classroom Resources',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Teacher-made learning aids using local materials are valuable because they:',
        'option_a': 'Are always more expensive than commercial materials',
        'option_b': 'Are relevant to pupils\' local context and can be made at low cost',
        'option_c': 'Cannot effectively teach concepts',
        'option_d': 'Are only useful for decoration',
        'correct_option': 'B',
        'explanation': 'Locally made teaching-learning materials (TLMs) are contextually relevant, cost-effective, and can be tailored to specific lesson objectives. They connect abstract concepts to familiar, everyday objects in the pupils\' environment.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Microteaching',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Microteaching as a teacher training technique involves:',
        'option_a': 'Teaching a full 80-minute lesson to an entire school',
        'option_b': 'Teaching a short lesson to a small group, followed by feedback and re-teaching',
        'option_c': 'Reading about teaching from a textbook only',
        'option_d': 'Observing experienced teachers without practicing',
        'correct_option': 'B',
        'explanation': 'Microteaching (Allen & Ryan) is a scaled-down teaching encounter — a short lesson (5-15 minutes) to a small group, followed by feedback, reflection, and re-teaching. It allows focused practice of specific teaching skills.',
    },
    {
        'domain': 'pedagogy',
        'topic': 'Action Research',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A teacher notices pupils struggle with reading comprehension and designs a study to test whether graphic organizers improve understanding. This is an example of:',
        'option_a': 'Standardized testing',
        'option_b': 'Action research',
        'option_c': 'Summative evaluation',
        'option_d': 'National curriculum review',
        'correct_option': 'B',
        'explanation': 'Action research is a systematic inquiry by teachers into their own practice. They identify a classroom problem, design an intervention, collect data, analyze results, and use findings to improve teaching — a reflective cycle.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 4: CLASSROOM MANAGEMENT (20 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'management',
        'topic': 'Rules and Procedures',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Classroom rules are most effective when they are:',
        'option_a': 'Imposed by the headteacher without pupil input',
        'option_b': 'Developed collaboratively with pupils and stated positively',
        'option_c': 'Changed every week to keep pupils guessing',
        'option_d': 'As numerous as possible to cover every situation',
        'correct_option': 'B',
        'explanation': 'Rules co-created with pupils promote ownership and buy-in. Stating rules positively (e.g., "Walk in the hallway" instead of "Don\'t run") tells pupils what TO do rather than what not to do. Keep to 3-5 clear rules.',
    },
    {
        'domain': 'management',
        'topic': 'Transitions',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'To minimize disruption during transitions between activities, a teacher should:',
        'option_a': 'Allow unlimited time for pupils to settle',
        'option_b': 'Use consistent signals and routines that pupils have practiced',
        'option_c': 'Shout at pupils to hurry up',
        'option_d': 'Skip transitions entirely',
        'correct_option': 'B',
        'explanation': 'Smooth transitions require taught and practiced routines — clapping patterns, countdown signals, specific procedures. Consistent signals reduce wasted time and prevent the off-task behavior that often occurs during unstructured moments.',
    },
    {
        'domain': 'management',
        'topic': 'Positive Behavior',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A teacher who notices a pupil behaving well and says "Thank you, Ama, for sitting quietly" in front of the class is using:',
        'option_a': 'Punishment',
        'option_b': 'Positive reinforcement and narrating desired behavior',
        'option_c': 'Negative reinforcement',
        'option_d': 'Planned ignoring',
        'correct_option': 'B',
        'explanation': 'Publicly acknowledging specific positive behavior (behavior narration) reinforces the desired behavior in Ama and serves as a model for other pupils. It is more effective than repeatedly correcting misbehavior.',
    },
    {
        'domain': 'management',
        'topic': 'Motivation',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'When a pupil is frequently off-task, the teacher should first consider:',
        'option_a': 'Immediately sending the pupil to the headteacher',
        'option_b': 'Whether the task is at the appropriate level and engaging for the pupil',
        'option_c': 'Calling the pupil\'s parents to come to school',
        'option_d': 'Punishing the pupil with extra homework',
        'correct_option': 'B',
        'explanation': 'Off-task behavior often signals that the work is too difficult, too easy, or not engaging. Effective teachers first examine the instructional match before attributing the behavior to the pupil\'s character.',
    },
    {
        'domain': 'management',
        'topic': 'Physical Environment',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Arranging desks in groups or clusters is most appropriate when the lesson involves:',
        'option_a': 'Individual standardized testing',
        'option_b': 'Collaborative group work and discussion',
        'option_c': 'A formal examination',
        'option_d': 'Silent individual reading',
        'correct_option': 'B',
        'explanation': 'Desk arrangement should match the learning activity. Clusters/groups facilitate collaboration, discussion, and cooperative learning. Rows are better for individual work, direct instruction, or testing.',
    },
    {
        'domain': 'management',
        'topic': 'Conflict Resolution',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'When two pupils have a disagreement, the teacher should:',
        'option_a': 'Ignore the conflict and hope it resolves itself',
        'option_b': 'Listen to both sides, guide pupils to express feelings, and help them find a resolution',
        'option_c': 'Punish both pupils equally regardless of circumstances',
        'option_d': 'Take one pupil\'s side immediately',
        'correct_option': 'B',
        'explanation': 'Effective conflict resolution involves active listening, validating feelings, and guiding pupils toward their own solutions. This teaches social-emotional skills and creates a respectful classroom community.',
    },
    {
        'domain': 'management',
        'topic': 'Time Management',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Allocated time, engaged time, and academic learning time are concepts in classroom management. The most important for learning is:',
        'option_a': 'Allocated time (total time for a lesson)',
        'option_b': 'Academic learning time (time pupils are successfully engaged with appropriate material)',
        'option_c': 'Transition time between activities',
        'option_d': 'Break time between lessons',
        'correct_option': 'B',
        'explanation': 'Academic Learning Time (ALT) — when pupils are actively and successfully engaged with material at the right difficulty level — is the strongest predictor of achievement. Maximizing ALT is a key management goal.',
    },
    {
        'domain': 'management',
        'topic': 'Preventive Strategies',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The concept of "withitness" (Kounin) means the teacher:',
        'option_a': 'Always uses technology in lessons',
        'option_b': 'Is aware of everything happening in the classroom at all times',
        'option_c': 'Uses only worksheets for instruction',
        'option_d': 'Sits at the desk while pupils work',
        'correct_option': 'B',
        'explanation': 'Jacob Kounin coined "withitness" to describe teachers\' ability to monitor the entire classroom simultaneously — having "eyes in the back of the head." Withit teachers catch problems early before they escalate.',
    },
    {
        'domain': 'management',
        'topic': 'Routines',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Establishing routines at the beginning of the school year is important because:',
        'option_a': 'It fills time during the first week',
        'option_b': 'It creates a predictable, safe environment and saves instructional time throughout the year',
        'option_c': 'It shows pupils who is in charge',
        'option_d': 'It is required by the Ghana Education Service only',
        'correct_option': 'B',
        'explanation': 'Well-taught routines at the start of the year create a structured environment where pupils know expectations. This reduces behavior issues, minimizes wasted time, and allows more time for actual instruction all year long.',
    },
    {
        'domain': 'management',
        'topic': 'Discipline',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'According to Ghana Education Service guidelines, which of the following is an acceptable disciplinary measure?',
        'option_a': 'Corporal punishment (caning)',
        'option_b': 'Withdrawal of privileges combined with counseling and guidance',
        'option_c': 'Public humiliation of the pupil',
        'option_d': 'Denying the pupil food or water',
        'correct_option': 'B',
        'explanation': 'GES has banned corporal punishment in schools. Acceptable discipline includes withdrawal of privileges, counseling, guidance, and restorative practices that maintain the pupil\'s dignity and teach better behavior.',
    },
    {
        'domain': 'management',
        'topic': 'Student Engagement',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'During whole-class teaching, the teacher can engage all learners by:',
        'option_a': 'Only calling on pupils who raise their hands',
        'option_b': 'Using random selection strategies (e.g., name sticks) so every pupil may be called',
        'option_c': 'Asking the same 5 pupils every time',
        'option_d': 'Not asking questions at all',
        'correct_option': 'B',
        'explanation': 'Random selection (pulling names from sticks/cards) ensures all pupils stay alert and engaged, not just volunteers. It distributes participation equitably and increases accountability for paying attention.',
    },
    {
        'domain': 'management',
        'topic': 'Parent Communication',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Effective parent-teacher communication should:',
        'option_a': 'Only happen when a pupil misbehaves',
        'option_b': 'Be proactive, regular, and include both positive reports and concerns',
        'option_c': 'Only take place at PTA meetings once per term',
        'option_d': 'Avoid discussing the pupil\'s academic progress',
        'correct_option': 'B',
        'explanation': 'Strong parent-teacher relationships are built through regular, proactive communication that shares both positive achievements and areas for growth. This builds trust and creates a partnership for the child\'s benefit.',
    },
    {
        'domain': 'management',
        'topic': 'Lesson Pacing',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Good lesson pacing means:',
        'option_a': 'Rushing through the lesson to cover all content regardless of understanding',
        'option_b': 'Maintaining a brisk but appropriate pace with varied activities to sustain attention',
        'option_c': 'Spending the entire period on one activity',
        'option_d': 'Allowing unlimited time for every activity',
        'correct_option': 'B',
        'explanation': 'Effective pacing keeps the lesson moving to maintain engagement while allowing sufficient time for understanding. Varying activities (input, practice, discussion, movement) every 10-15 minutes sustains attention.',
    },
    {
        'domain': 'management',
        'topic': 'Attention Signals',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A teacher claps a pattern and pupils clap back the same pattern. This is an example of:',
        'option_a': 'A punishment strategy',
        'option_b': 'A call-and-response attention signal',
        'option_c': 'A music lesson',
        'option_d': 'A physical education activity',
        'correct_option': 'B',
        'explanation': 'Call-and-response attention signals (clap patterns, verbal prompts like "Class-Class/Yes-Yes") are efficient, non-punitive ways to regain whole-class attention. They work best when consistently taught and practiced.',
    },
    {
        'domain': 'management',
        'topic': 'Bullying',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A teacher observes one pupil repeatedly excluding another from group activities. The best response is to:',
        'option_a': 'Ignore it as normal childhood behavior',
        'option_b': 'Address the behavior privately, teach empathy, and monitor the situation',
        'option_c': 'Punish the whole class',
        'option_d': 'Tell the excluded pupil to find other friends',
        'correct_option': 'B',
        'explanation': 'Social exclusion is a form of relational bullying. Teachers should address it directly but privately, help the aggressor develop empathy, support the victim, and monitor to ensure the behavior stops. Ignoring it allows escalation.',
    },
    {
        'domain': 'management',
        'topic': 'Equity',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Gender-responsive classroom management includes:',
        'option_a': 'Asking only boys to answer difficult questions',
        'option_b': 'Ensuring equal participation opportunities, avoiding gender stereotypes in tasks',
        'option_c': 'Seating boys and girls in completely separate rooms',
        'option_d': 'Giving leadership roles only to boys',
        'correct_option': 'B',
        'explanation': 'Gender-responsive management ensures all pupils — regardless of gender — have equal opportunities to participate, lead, and succeed. It avoids stereotyped task assignments and actively encourages inclusive participation.',
    },
    {
        'domain': 'management',
        'topic': 'Behavior Tracking',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Keeping a behavior log helps teachers to:',
        'option_a': 'Find pupils to punish',
        'option_b': 'Identify patterns, triggers, and effective interventions for behavior concerns',
        'option_c': 'Report every minor infraction to parents',
        'option_d': 'Reduce the number of pupils in the class',
        'correct_option': 'B',
        'explanation': 'Behavior logs (anecdotal records) help teachers track when, where, and under what conditions behaviors occur. This data reveals patterns and triggers, informing targeted interventions rather than reactive punishment.',
    },
    {
        'domain': 'management',
        'topic': 'Proximity',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': '"Proximity control" as a management technique involves:',
        'option_a': 'Standing at the front of the class at all times',
        'option_b': 'Moving near a pupil who is off-task to redirect behavior without verbal confrontation',
        'option_c': 'Sending off-task pupils outside the classroom',
        'option_d': 'Using a microphone so pupils can hear from far away',
        'correct_option': 'B',
        'explanation': 'Proximity control is a low-key, non-verbal strategy where the teacher moves near a misbehaving pupil. The physical closeness alone often redirects behavior without disrupting the lesson or embarrassing the pupil.',
    },
    {
        'domain': 'management',
        'topic': 'Restorative Practices',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Restorative practices in schools focus on:',
        'option_a': 'Punishing offenders as harshly as possible to deter others',
        'option_b': 'Repairing harm, restoring relationships, and reintegrating the offender into the community',
        'option_c': 'Expelling pupils at the first offense',
        'option_d': 'Ignoring all misbehavior',
        'correct_option': 'B',
        'explanation': 'Restorative practices shift from punitive discipline to relationship-centered approaches. They focus on who was harmed, what needs exist, and how to repair damage — using circles, conferences, and mediation to restore community.',
    },
    {
        'domain': 'management',
        'topic': 'Self-Regulation',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Teaching pupils self-regulation strategies means helping them to:',
        'option_a': 'Always rely on the teacher for direction',
        'option_b': 'Monitor, control, and adjust their own behavior, emotions, and learning independently',
        'option_c': 'Follow rules without understanding why',
        'option_d': 'Avoid all challenging situations',
        'correct_option': 'B',
        'explanation': 'Self-regulation involves metacognitive skills — self-monitoring, setting personal goals, managing emotions, and adjusting behavior. Teaching these skills builds independence and intrinsic discipline beyond teacher-controlled management.',
    },
]
