# ─────────────────────────────────────────────────────────────────────────────
# GES Promotion Exam Practice Question Bank
# Ghana Education Service — Promotion Examination preparation across 5 domains
# 85 questions (17 per domain)
# ─────────────────────────────────────────────────────────────────────────────

PROMOTION_QUESTION_BANK = [
    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 1: PROFESSIONAL STANDARDS (17 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'professional',
        'topic': 'Code of Conduct',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'According to the GES Code of Conduct, which of the following is a primary obligation of a professional teacher?',
        'option_a': 'Maintaining the dignity and integrity of the teaching profession',
        'option_b': 'Ensuring maximum personal income through private tutoring',
        'option_c': 'Prioritising personal advancement over student welfare',
        'option_d': 'Delegating all classroom responsibilities to student leaders',
        'correct_option': 'A',
        'explanation': 'The GES Code of Conduct requires teachers to uphold the dignity and integrity of the profession through ethical behaviour, professional competence, and commitment to student welfare.',
    },
    {
        'domain': 'professional',
        'topic': 'Professional Development',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which body is primarily responsible for setting professional standards for teachers in Ghana?',
        'option_a': 'Ghana Education Service Council',
        'option_b': 'National Teaching Council (NTC)',
        'option_c': 'Ministry of Finance',
        'option_d': 'National Commission for Civic Education',
        'correct_option': 'B',
        'explanation': 'The National Teaching Council (NTC) is the statutory body responsible for licensing teachers, setting professional standards, and regulating the teaching profession in Ghana.',
    },
    {
        'domain': 'professional',
        'topic': 'Teacher Licensing',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'What is the primary purpose of the Ghana Teacher Licensure Examination (GTLE)?',
        'option_a': 'To determine teacher salary levels',
        'option_b': 'To ensure all practising teachers meet minimum professional competency standards',
        'option_c': 'To rank teachers for immediate promotion',
        'option_d': 'To replace continuous professional development requirements',
        'correct_option': 'B',
        'explanation': 'The GTLE ensures that all teachers in Ghana meet the minimum professional competency standards before being licensed to teach, thereby improving the quality of education delivery.',
    },
    {
        'domain': 'professional',
        'topic': 'Professional Ethics',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A teacher discovers that a colleague is consistently arriving late and not covering their syllabus. The most professionally appropriate action is to:',
        'option_a': 'Ignore the situation as it is not their responsibility',
        'option_b': 'Publicly criticise the colleague at the next staff meeting',
        'option_c': 'Report the concern to the headteacher through proper channels',
        'option_d': 'Inform parents directly about the colleague\'s behaviour',
        'correct_option': 'C',
        'explanation': 'Professional ethics require that concerns about colleague performance be addressed through the appropriate institutional channels — in this case, reporting to the headteacher who has supervisory authority.',
    },
    {
        'domain': 'professional',
        'topic': 'Continuing Professional Development',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which of the following best describes the purpose of Continuing Professional Development (CPD) for teachers?',
        'option_a': 'A one-time training during initial teacher education',
        'option_b': 'An ongoing process of improving knowledge, skills, and practices throughout a teacher\'s career',
        'option_c': 'A requirement only for newly qualified teachers',
        'option_d': 'Attending one workshop every five years',
        'correct_option': 'B',
        'explanation': 'CPD is a continuous, lifelong process through which teachers update and enhance their professional knowledge, skills, and practices to improve student outcomes.',
    },
    {
        'domain': 'professional',
        'topic': 'NTC Standards',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The National Teachers\' Standards (NTS) for Ghana are organised into how many broad domains?',
        'option_a': 'Two domains',
        'option_b': 'Three domains',
        'option_c': 'Four domains',
        'option_d': 'Five domains',
        'correct_option': 'B',
        'explanation': 'The NTS is organised into three broad domains: (1) Professional Values and Attitudes, (2) Professional Knowledge, and (3) Professional Practice. Each domain has specific standards and indicators.',
    },
    {
        'domain': 'professional',
        'topic': 'Teacher Accountability',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A teacher\'s record of work (scheme of work and lesson notes) is primarily reviewed by:',
        'option_a': 'The District Director of Education',
        'option_b': 'Parent representatives',
        'option_c': 'The headteacher or head of department',
        'option_d': 'The school\'s security officer',
        'correct_option': 'C',
        'explanation': 'The headteacher or head of department is responsible for supervising and reviewing teachers\' professional records, including schemes of work and lesson notes, as part of internal quality assurance.',
    },
    {
        'domain': 'professional',
        'topic': 'Professional Boundaries',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which of the following is a violation of professional boundaries between a teacher and student?',
        'option_a': 'Providing academic support during office hours',
        'option_b': 'Engaging in a personal romantic relationship with a student',
        'option_c': 'Organising extra revision classes before exams',
        'option_d': 'Communicating with parents about student progress',
        'correct_option': 'B',
        'explanation': 'Engaging in romantic relationships with students is a serious violation of professional boundaries and the GES Code of Conduct. It constitutes professional misconduct and is subject to disciplinary action.',
    },
    {
        'domain': 'professional',
        'topic': 'Promotion Requirements',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'For a teacher at the rank of Superintendent to be promoted to Senior Superintendent, which of the following is typically required?',
        'option_a': 'Only years of service',
        'option_b': 'Years of service, satisfactory performance appraisals, and passing the promotion examination',
        'option_c': 'Obtaining a doctoral degree',
        'option_d': 'Transferring to a new school',
        'correct_option': 'B',
        'explanation': 'Promotion in the GES typically requires a combination of requisite years of service at the current rank, consistently satisfactory performance appraisals, and passing the promotion examination.',
    },
    {
        'domain': 'professional',
        'topic': 'Reflective Practice',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Reflective practice in teaching primarily involves:',
        'option_a': 'Memorising the content of textbooks before teaching',
        'option_b': 'Critically examining one\'s own teaching methods and their impact on learning',
        'option_c': 'Copying the teaching methods of senior colleagues without modification',
        'option_d': 'Allowing students to evaluate other teachers',
        'correct_option': 'B',
        'explanation': 'Reflective practice involves teachers systematically examining their own teaching strategies, decisions, and outcomes to understand what works, what doesn\'t, and how to improve their practice.',
    },
    {
        'domain': 'professional',
        'topic': 'Stakeholder Relations',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The School Management Committee (SMC) typically includes representation from which group?',
        'option_a': 'Only teachers and headteacher',
        'option_b': 'Teachers, parents, community leaders, and the District Education office',
        'option_c': 'Only parents and students',
        'option_d': 'Only the District Director',
        'correct_option': 'B',
        'explanation': 'The SMC is a broad-based committee that includes teachers, parents, community leaders, and a representative of the District Education Directorate to ensure inclusive governance of the school.',
    },
    {
        'domain': 'professional',
        'topic': 'GES Rank Structure',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'What is the correct ascending order of GES teacher ranks?',
        'option_a': 'Superintendent → Principal Superintendent → Senior Superintendent → Assistant Director',
        'option_b': 'Superintendent → Senior Superintendent → Principal Superintendent → Assistant Director',
        'option_c': 'Senior Superintendent → Superintendent → Assistant Director → Principal Superintendent',
        'option_d': 'Assistant Director → Superintendent → Senior Superintendent → Principal Superintendent',
        'correct_option': 'B',
        'explanation': 'The ascending GES rank structure is: Superintendent → Senior Superintendent → Principal Superintendent → Assistant Director I → Assistant Director II → Deputy Director → Director.',
    },
    {
        'domain': 'professional',
        'topic': 'Mentoring',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'What is the primary role of a mentor teacher assigned to a beginning teacher?',
        'option_a': 'To write lesson notes on behalf of the beginning teacher',
        'option_b': 'To guide, support, and model effective teaching practices for professional growth',
        'option_c': 'To report the beginning teacher\'s mistakes to the headteacher',
        'option_d': 'To set examination papers for the beginning teacher\'s class',
        'correct_option': 'B',
        'explanation': 'Mentor teachers provide guidance, model effective instructional strategies, offer constructive feedback, and support the professional development of beginning teachers during their induction period.',
    },
    {
        'domain': 'professional',
        'topic': 'Teacher Appraisal',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Performance appraisals in the GES are primarily intended to:',
        'option_a': 'Punish underperforming teachers',
        'option_b': 'Provide a basis for teacher improvement, accountability, and career progression decisions',
        'option_c': 'Replace classroom observation entirely',
        'option_d': 'Determine which teachers should be transferred',
        'correct_option': 'B',
        'explanation': 'Performance appraisals serve a developmental and evaluative purpose — they identify strengths and areas for improvement, inform professional development planning, and provide evidence for career progression decisions.',
    },
    {
        'domain': 'professional',
        'topic': 'Community Engagement',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A teacher\'s role in community engagement includes all of the following EXCEPT:',
        'option_a': 'Participating in PTA meetings',
        'option_b': 'Engaging parents in their children\'s education',
        'option_c': 'Using school funds for personal community projects',
        'option_d': 'Serving as a role model in the community',
        'correct_option': 'C',
        'explanation': 'Teachers are expected to engage with the community through PTA involvement, parent communication, and exemplary behaviour, but misusing school funds for personal community projects is a violation of financial ethics.',
    },
    {
        'domain': 'professional',
        'topic': 'Inclusive Education',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Inclusive education as promoted by GES requires teachers to:',
        'option_a': 'Teach only gifted and talented students',
        'option_b': 'Ensure all learners, including those with disabilities, have equal access to quality education',
        'option_c': 'Separate students with special needs into different schools',
        'option_d': 'Focus resources exclusively on high-performing students',
        'correct_option': 'B',
        'explanation': 'Inclusive education is a policy commitment by GES to ensure that all learners, regardless of ability, disability, gender, or socio-economic background, have access to quality education in the same school environment.',
    },
    {
        'domain': 'professional',
        'topic': 'Professional Conduct',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Under the GES disciplinary procedures, which of the following offences may lead to immediate dismissal?',
        'option_a': 'Arriving five minutes late on one occasion',
        'option_b': 'Sexual exploitation of a pupil',
        'option_c': 'Failing to submit lesson notes once',
        'option_d': 'Missing one staff meeting',
        'correct_option': 'B',
        'explanation': 'Sexual exploitation of a pupil is classified as gross misconduct under GES regulations and may lead to immediate dismissal, criminal prosecution, and permanent debarment from the teaching profession.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 2: CURRICULUM & INSTRUCTION (17 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'curriculum',
        'topic': 'Standards-Based Curriculum',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The Ghana Standards-Based Curriculum (SBC) was introduced to replace:',
        'option_a': 'The Objective-Based Curriculum',
        'option_b': 'The Competency-Based Curriculum',
        'option_c': 'The Activity-Based Curriculum',
        'option_d': 'The Subject-Based Curriculum',
        'correct_option': 'A',
        'explanation': 'The Standards-Based Curriculum (SBC), introduced from 2019, replaced the earlier Objective-Based Curriculum to shift focus from rote learning to competency development and critical thinking.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Core Competencies',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which of the following is NOT one of the core competencies in the Ghana Standards-Based Curriculum?',
        'option_a': 'Critical thinking and problem solving',
        'option_b': 'Creativity and innovation',
        'option_c': 'Rote memorisation and recall',
        'option_d': 'Communication and collaboration',
        'correct_option': 'C',
        'explanation': 'The SBC promotes core competencies including critical thinking, creativity, communication, collaboration, digital literacy, and cultural identity — not rote memorisation, which is a departure from the old curriculum.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Lesson Planning',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which component of a lesson plan describes what learners should know or be able to do by the end of the lesson?',
        'option_a': 'Teaching and learning resources',
        'option_b': 'Introduction',
        'option_c': 'Performance indicators / learning objectives',
        'option_d': 'Closure activities',
        'correct_option': 'C',
        'explanation': 'Performance indicators or learning objectives clearly state the expected learning outcomes — what learners should know, understand, or be able to do upon completing the lesson.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Differentiated Instruction',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Differentiated instruction requires a teacher to:',
        'option_a': 'Teach every student the same way regardless of ability',
        'option_b': 'Modify content, process, or product to meet diverse learner needs',
        'option_c': 'Focus only on struggling learners and ignore advanced ones',
        'option_d': 'Prepare separate lessons for each student individually',
        'correct_option': 'B',
        'explanation': 'Differentiated instruction involves adjusting content (what is taught), process (how it is taught), or product (how learning is demonstrated) to address the readiness levels, interests, and learning profiles of all students.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Bloom\'s Taxonomy',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'In Bloom\'s Revised Taxonomy, which level represents the highest order of cognitive thinking?',
        'option_a': 'Applying',
        'option_b': 'Analysing',
        'option_c': 'Creating',
        'option_d': 'Evaluating',
        'correct_option': 'C',
        'explanation': 'Bloom\'s Revised Taxonomy orders cognitive levels as: Remember → Understand → Apply → Analyse → Evaluate → Create. "Create" is the highest level, involving producing new or original work.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Instructional Strategies',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which of the following is an example of a learner-centred teaching strategy?',
        'option_a': 'The teacher reads from the textbook while students listen',
        'option_b': 'Students work in groups to investigate a problem and present findings',
        'option_c': 'The teacher dictates notes for students to copy',
        'option_d': 'Students memorise definitions from the chalkboard',
        'correct_option': 'B',
        'explanation': 'Learner-centred strategies place students at the centre of the learning process. Group investigation and presentation is a collaborative, active-learning approach that develops critical thinking and communication skills.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Strand and Sub-strand',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'In the Standards-Based Curriculum, a "strand" refers to:',
        'option_a': 'A single lesson objective',
        'option_b': 'A broad theme or area of learning within a subject that organises content and standards',
        'option_c': 'The time allocated for each subject',
        'option_d': 'A textbook chapter',
        'correct_option': 'B',
        'explanation': 'A strand is a broad thematic organiser within a subject area. Each strand is further divided into sub-strands, which contain content standards and indicators that guide teaching and learning.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Scheme of Work',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A scheme of work is best described as:',
        'option_a': 'A daily record of student attendance',
        'option_b': 'A plan that outlines the content to be covered over a term or academic year',
        'option_c': 'A financial plan for school expenditure',
        'option_d': 'A list of extra-curricular activities for students',
        'correct_option': 'B',
        'explanation': 'A scheme of work is a structured plan that breaks down the syllabus into weekly or fortnightly teaching blocks, specifying topics, sub-topics, objectives, and resources for a given period.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Cross-Curricular Issues',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Which of the following is an example of a cross-cutting issue that should be integrated across all subjects in the Ghanaian curriculum?',
        'option_a': 'Football skills training',
        'option_b': 'Gender responsiveness and environmental sustainability',
        'option_c': 'School uniform policies',
        'option_d': 'Examination timetable scheduling',
        'correct_option': 'B',
        'explanation': 'The SBC mandates integration of cross-cutting issues such as gender responsiveness, environmental sustainability, ICT, creativity, and inclusivity across all subject areas.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Constructivism',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The constructivist theory of learning, which underpins the SBC, holds that:',
        'option_a': 'Knowledge is passively received from the teacher',
        'option_b': 'Learners actively construct knowledge through experiences and interactions',
        'option_c': 'All learning occurs only through repetition and drills',
        'option_d': 'Students cannot learn without direct instruction at all times',
        'correct_option': 'B',
        'explanation': 'Constructivism posits that learners actively build their own understanding by connecting new experiences to prior knowledge. The SBC is grounded in this approach, promoting activity-based, participatory learning.',
    },
    {
        'domain': 'curriculum',
        'topic': 'ICT Integration',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Integrating ICT into instruction means:',
        'option_a': 'Replacing all textbooks with computers',
        'option_b': 'Using technology purposefully to enhance teaching processes and learning outcomes',
        'option_c': 'Allowing students to play games on tablets during lessons',
        'option_d': 'Only teaching a separate ICT subject',
        'correct_option': 'B',
        'explanation': 'ICT integration involves the purposeful and planned use of technology tools (computers, projectors, educational software) across subjects to make learning more engaging, accessible, and effective.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Teaching and Learning Materials',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which of the following is the MOST important consideration when selecting teaching and learning materials (TLMs)?',
        'option_a': 'The cost of the materials',
        'option_b': 'Their relevance to the lesson objectives and learner needs',
        'option_c': 'Whether they are imported from abroad',
        'option_d': 'How decorative they look in the classroom',
        'correct_option': 'B',
        'explanation': 'The primary consideration when selecting TLMs is their relevance to the lesson objectives and the needs of learners. Effective TLMs should support concept understanding and be appropriate for the developmental level of students.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Scaffolding',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Scaffolding in instruction refers to:',
        'option_a': 'Building physical structures in the classroom',
        'option_b': 'Providing temporary support to learners that is gradually removed as they gain competence',
        'option_c': 'Making lessons extremely easy so no one fails',
        'option_d': 'Testing students before teaching them',
        'correct_option': 'B',
        'explanation': 'Scaffolding involves providing structured support (prompts, models, guided practice) to help learners achieve tasks they cannot manage independently, then gradually withdrawing support as competence develops.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Multiple Intelligences',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Howard Gardner\'s theory of Multiple Intelligences suggests that teachers should:',
        'option_a': 'Only test linguistic and mathematical abilities',
        'option_b': 'Recognise and address diverse cognitive strengths including spatial, musical, and interpersonal intelligences',
        'option_c': 'Standardise all instruction to one modality',
        'option_d': 'Eliminate practical activities from the curriculum',
        'correct_option': 'B',
        'explanation': 'Gardner\'s theory identifies multiple forms of intelligence (linguistic, logical-mathematical, spatial, musical, bodily-kinaesthetic, interpersonal, intrapersonal, naturalistic). Effective teaching addresses this diversity.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Curriculum Adaptation',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'When a teacher adapts the curriculum for a student with a learning disability, this is an example of:',
        'option_a': 'Lowering standards',
        'option_b': 'Curriculum modification or accommodation to ensure inclusivity',
        'option_c': 'Academic fraud',
        'option_d': 'Ignoring the national curriculum',
        'correct_option': 'B',
        'explanation': 'Curriculum modifications and accommodations are legitimate, professional practices that adjust content delivery or assessment methods to ensure students with disabilities can access the curriculum meaningfully.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Formative Activities',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'During a lesson, a teacher asks probing questions and observes student responses to check understanding. This is an example of:',
        'option_a': 'Summative assessment',
        'option_b': 'Formative assessment',
        'option_c': 'Placement testing',
        'option_d': 'Diagnostic screening',
        'correct_option': 'B',
        'explanation': 'Formative assessment is the ongoing process of monitoring student learning during instruction through questioning, observation, and feedback to inform teaching decisions in real time.',
    },
    {
        'domain': 'curriculum',
        'topic': 'Cooperative Learning',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'In cooperative learning, students are grouped to:',
        'option_a': 'Compete against each other for the highest individual grade',
        'option_b': 'Work together towards shared learning goals with individual accountability',
        'option_c': 'Allow faster students to do all the work',
        'option_d': 'Reduce the teacher\'s lesson preparation time',
        'correct_option': 'B',
        'explanation': 'Cooperative learning structures require positive interdependence (shared goals), individual accountability, face-to-face interaction, and collaborative skills — all of which promote deeper learning and social development.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 3: ASSESSMENT & EVALUATION (17 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'assessment',
        'topic': 'Types of Assessment',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Which type of assessment is conducted at the end of a term or programme to determine what students have learned?',
        'option_a': 'Diagnostic assessment',
        'option_b': 'Formative assessment',
        'option_c': 'Summative assessment',
        'option_d': 'Ipsative assessment',
        'correct_option': 'C',
        'explanation': 'Summative assessment is conducted at the end of a learning period (term, year, programme) to evaluate student achievement against standards or benchmarks and often contributes to grades or certification.',
    },
    {
        'domain': 'assessment',
        'topic': 'Continuous Assessment',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'In the Ghanaian education system, Continuous Assessment (CA) constitutes what proportion of a student\'s overall grade at the basic level?',
        'option_a': '20%',
        'option_b': '30%',
        'option_c': '50%',
        'option_d': '40%',
        'correct_option': 'C',
        'explanation': 'Under the Standards-Based Curriculum assessment framework, continuous assessment (class exercises, projects, homework, quizzes) constitutes 50% of the overall grade, with end-of-term examinations accounting for the remaining 50%.',
    },
    {
        'domain': 'assessment',
        'topic': 'Test Construction',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'When constructing a test, a table of specifications (test blueprint) is primarily used to ensure:',
        'option_a': 'The test is very long',
        'option_b': 'Content coverage and cognitive level balance across test items',
        'option_c': 'Students find the test extremely easy',
        'option_d': 'The test contains only multiple-choice questions',
        'correct_option': 'B',
        'explanation': 'A table of specifications is a two-dimensional grid that maps test items to content areas and cognitive levels (Bloom\'s taxonomy), ensuring comprehensive content coverage and an appropriate distribution of difficulty.',
    },
    {
        'domain': 'assessment',
        'topic': 'Reliability',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A test is considered reliable when it:',
        'option_a': 'Measures exactly what it is intended to measure',
        'option_b': 'Produces consistent results across multiple administrations',
        'option_c': 'Is easy for all students to pass',
        'option_d': 'Contains only essay questions',
        'correct_option': 'B',
        'explanation': 'Reliability refers to the consistency of test scores. A reliable test produces similar results when administered to the same group under similar conditions on different occasions.',
    },
    {
        'domain': 'assessment',
        'topic': 'Validity',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A Mathematics test that includes questions about English grammar lacks:',
        'option_a': 'Reliability',
        'option_b': 'Content validity',
        'option_c': 'Objectivity',
        'option_d': 'Practicality',
        'correct_option': 'B',
        'explanation': 'Content validity means a test measures the content it is supposed to measure. A Mathematics test with English grammar questions fails to represent the intended mathematical content domain.',
    },
    {
        'domain': 'assessment',
        'topic': 'Rubrics',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A scoring rubric is best described as:',
        'option_a': 'A list of student names for attendance',
        'option_b': 'A set of criteria and performance level descriptors used to assess student work',
        'option_c': 'A class timetable',
        'option_d': 'A type of examination question',
        'correct_option': 'B',
        'explanation': 'A rubric is an assessment tool that lays out specific criteria and performance-level descriptors (e.g., excellent, good, satisfactory, needs improvement) for evaluating the quality of student work.',
    },
    {
        'domain': 'assessment',
        'topic': 'Item Analysis',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A test item with a discrimination index of 0.10 suggests that the item:',
        'option_a': 'Strongly differentiates between high and low performers',
        'option_b': 'Poorly differentiates between high and low performers and should be reviewed',
        'option_c': 'Is perfectly constructed and should remain unchanged',
        'option_d': 'Should be made more difficult',
        'correct_option': 'B',
        'explanation': 'A discrimination index below 0.20 indicates that the item does not effectively distinguish between students who know the material well and those who don\'t. Such items should be revised or discarded.',
    },
    {
        'domain': 'assessment',
        'topic': 'Diagnostic Assessment',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The primary purpose of a diagnostic assessment is to:',
        'option_a': 'Assign final grades to students',
        'option_b': 'Identify students\' specific strengths and weaknesses before or during instruction',
        'option_c': 'Rank students from best to worst',
        'option_d': 'Determine school funding levels',
        'correct_option': 'B',
        'explanation': 'Diagnostic assessments are used to identify students\' prior knowledge, misconceptions, and specific learning needs so that instruction can be tailored to address gaps and build on strengths.',
    },
    {
        'domain': 'assessment',
        'topic': 'Portfolio Assessment',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A student portfolio is a valuable assessment tool because it:',
        'option_a': 'Reduces the teacher\'s workload to zero',
        'option_b': 'Provides evidence of student learning and growth over time',
        'option_c': 'Replaces the need for any examination',
        'option_d': 'Is only useful for art students',
        'correct_option': 'B',
        'explanation': 'Portfolios collect samples of student work over time, showing progress, effort, and achievement. They provide authentic, holistic evidence of learning that complements traditional testing methods.',
    },
    {
        'domain': 'assessment',
        'topic': 'Norm-Referenced Testing',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A norm-referenced test differs from a criterion-referenced test in that it:',
        'option_a': 'Compares a student\'s performance to the performance of other students in a defined group',
        'option_b': 'Compares a student\'s performance to a fixed standard of mastery',
        'option_c': 'Has no grading system',
        'option_d': 'Is always administered orally',
        'correct_option': 'A',
        'explanation': 'Norm-referenced tests rank students relative to each other (e.g., percentile ranks), while criterion-referenced tests measure whether a student has met specific learning standards regardless of others\' performance.',
    },
    {
        'domain': 'assessment',
        'topic': 'Feedback',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Effective feedback to students should be:',
        'option_a': 'Given only at the end of the school year',
        'option_b': 'Timely, specific, and focused on how to improve',
        'option_c': 'Vague and general to avoid hurting feelings',
        'option_d': 'Focused entirely on what the student did wrong',
        'correct_option': 'B',
        'explanation': 'Effective feedback is timely (given soon after the task), specific (refers to particular aspects of work), and constructive (indicates what was done well and how to improve). This motivates and guides learner development.',
    },
    {
        'domain': 'assessment',
        'topic': 'BECE Structure',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Basic Education Certificate Examination (BECE) serves as:',
        'option_a': 'A diagnostic test for primary school pupils',
        'option_b': 'A terminal examination for JHS graduates that determines placement into SHS',
        'option_c': 'An entrance exam for primary school',
        'option_d': 'A professional examination for teachers',
        'correct_option': 'B',
        'explanation': 'The BECE is the national terminal examination taken by JHS 3 students. It assesses competencies across core and elective subjects and determines placement into Senior High Schools through the Computerised School Selection and Placement System (CSSPS).',
    },
    {
        'domain': 'assessment',
        'topic': 'Grading Systems',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Under the Standards-Based Curriculum assessment system, student performance at the basic level is reported using:',
        'option_a': 'Letter grades A to F',
        'option_b': 'Numerical scores only',
        'option_c': 'Performance levels (e.g., Beginning, Approaching, Meeting, Exceeding)',
        'option_d': 'Pass/Fail only',
        'correct_option': 'C',
        'explanation': 'The SBC assessment framework uses performance levels rather than traditional letter grades at the basic level, reporting student achievement as Beginning, Approaching, Meeting, or Exceeding the expected standard.',
    },
    {
        'domain': 'assessment',
        'topic': 'Authentic Assessment',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Authentic assessment is characterised by tasks that:',
        'option_a': 'Require only memorisation and recall',
        'option_b': 'Reflect real-world applications and require students to demonstrate meaningful competencies',
        'option_c': 'Are always multiple choice in format',
        'option_d': 'Have only one correct answer',
        'correct_option': 'B',
        'explanation': 'Authentic assessments engage students in meaningful, real-world tasks (projects, performances, investigations) that require them to apply knowledge and skills in contexts similar to those they would encounter outside the classroom.',
    },
    {
        'domain': 'assessment',
        'topic': 'Assessment for Learning',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Assessment for learning (AfL) is different from assessment of learning because AfL:',
        'option_a': 'Occurs only at the end of a course',
        'option_b': 'Is used formatively during instruction to improve teaching and learning',
        'option_c': 'Assigns final grades to students',
        'option_d': 'Is conducted only by external examiners',
        'correct_option': 'B',
        'explanation': 'Assessment for learning (formative) is embedded in instruction and used to identify what students know and don\'t know in real time, allowing teachers to adjust teaching strategies. Assessment of learning (summative) evaluates achievement at the end.',
    },
    {
        'domain': 'assessment',
        'topic': 'Differentiated Assessment',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A teacher who allows a visually impaired student to take an oral examination instead of a written one is practising:',
        'option_a': 'Academic dishonesty',
        'option_b': 'Assessment accommodation for equity and inclusion',
        'option_c': 'Lowering academic standards',
        'option_d': 'Classroom favouritism',
        'correct_option': 'B',
        'explanation': 'Providing alternative assessment formats for students with disabilities is a legitimate accommodation that ensures equity. The student is still assessed against the same standards, but the mode of assessment is adjusted to be accessible.',
    },
    {
        'domain': 'assessment',
        'topic': 'Record Keeping',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Proper record keeping of student assessment data is important because it:',
        'option_a': 'Creates unnecessary paperwork',
        'option_b': 'Provides evidence for monitoring progress, reporting to parents, and making instructional decisions',
        'option_c': 'Is only needed once a year',
        'option_d': 'Is the sole responsibility of the headteacher',
        'correct_option': 'B',
        'explanation': 'Systematic assessment records enable teachers to track student progress, identify learning trends, communicate with parents, inform instructional planning, and provide evidence for promotion and placement decisions.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 4: LEADERSHIP & ADMINISTRATION (17 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'leadership',
        'topic': 'School Leadership',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The headteacher\'s primary role in a school is to:',
        'option_a': 'Teach all classes personally',
        'option_b': 'Provide instructional leadership, manage resources, and ensure effective school operations',
        'option_c': 'Collect school fees from parents',
        'option_d': 'Only discipline students',
        'correct_option': 'B',
        'explanation': 'The headteacher serves as the instructional leader and chief administrator of the school, responsible for leading teaching and learning, managing human and material resources, and maintaining an effective school environment.',
    },
    {
        'domain': 'leadership',
        'topic': 'Staff Supervision',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Clinical supervision in education involves:',
        'option_a': 'Sending teachers to a hospital for health checks',
        'option_b': 'A structured cycle of pre-observation conference, classroom observation, and post-observation feedback',
        'option_c': 'Watching teachers through security cameras',
        'option_d': 'Reading teachers\' personal diaries',
        'correct_option': 'B',
        'explanation': 'Clinical supervision is a professional development tool comprising three phases: pre-observation planning, systematic classroom observation, and post-observation analysis and feedback to improve teaching effectiveness.',
    },
    {
        'domain': 'leadership',
        'topic': 'Conflict Resolution',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'When two teachers have a conflict about classroom space, the most effective leadership approach is:',
        'option_a': 'Ignoring the conflict until it resolves itself',
        'option_b': 'Taking one teacher\'s side without hearing the other',
        'option_c': 'Facilitating a collaborative discussion to reach a mutually acceptable solution',
        'option_d': 'Transferring both teachers to different schools immediately',
        'correct_option': 'C',
        'explanation': 'Effective conflict resolution involves facilitating open dialogue between the parties, understanding both perspectives, and working collaboratively towards a solution that addresses the concerns of all involved.',
    },
    {
        'domain': 'leadership',
        'topic': 'School Improvement Planning',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A School Performance Improvement Plan (SPIP) should be developed based on:',
        'option_a': 'The headteacher\'s personal preferences',
        'option_b': 'Data-driven analysis of the school\'s strengths, weaknesses, and stakeholder input',
        'option_c': 'Copying another school\'s plan exactly',
        'option_d': 'Instructions from the media',
        'correct_option': 'B',
        'explanation': 'An effective SPIP is evidence-based, drawing on assessment data, school self-evaluation, stakeholder consultations (teachers, parents, students, community), and identified priority areas for improvement.',
    },
    {
        'domain': 'leadership',
        'topic': 'Financial Management',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Capitation grants provided to basic schools by the government are intended to:',
        'option_a': 'Pay teacher salaries',
        'option_b': 'Fund the personal expenses of the headteacher',
        'option_c': 'Cover operational costs such as teaching materials, maintenance, and school activities',
        'option_d': 'Build new classrooms',
        'correct_option': 'C',
        'explanation': 'Capitation grants are per-pupil government funds provided to basic schools to cover operational costs including teaching and learning materials, minor repairs, sports, and cultural activities — replacing the fees parents used to pay.',
    },
    {
        'domain': 'leadership',
        'topic': 'Change Management',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'When implementing a new curriculum change at the school level, the most important first step for a leader is to:',
        'option_a': 'Implement the change immediately without informing staff',
        'option_b': 'Communicate the rationale, involve stakeholders, and provide necessary training',
        'option_c': 'Punish staff who express concerns about the change',
        'option_d': 'Wait until the change is abandoned',
        'correct_option': 'B',
        'explanation': 'Effective change management requires clear communication about why the change is needed, involving staff in planning, addressing concerns, providing professional development, and supporting teachers through the transition.',
    },
    {
        'domain': 'leadership',
        'topic': 'Time Management',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A well-constructed school timetable ensures:',
        'option_a': 'Free periods for every teacher every day',
        'option_b': 'Equitable distribution of instructional time across subjects and efficient use of resources',
        'option_c': 'That the most popular subjects get the most time',
        'option_d': 'That students have no break periods',
        'correct_option': 'B',
        'explanation': 'A well-designed timetable allocates instructional time equitably according to curriculum requirements, ensures efficient use of classrooms and teachers, and balances academic subjects with breaks and co-curricular activities.',
    },
    {
        'domain': 'leadership',
        'topic': 'Delegation',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Effective delegation by a headteacher involves:',
        'option_a': 'Assigning all tasks to a single assistant head',
        'option_b': 'Distributing responsibilities based on staff strengths while maintaining accountability',
        'option_c': 'Doing everything personally to ensure quality',
        'option_d': 'Giving tasks to the most junior staff without guidance',
        'correct_option': 'B',
        'explanation': 'Effective delegation involves assigning responsibilities to staff based on their strengths and expertise, providing clear expectations and support, and maintaining oversight without micromanaging.',
    },
    {
        'domain': 'leadership',
        'topic': 'School Culture',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'A positive school culture is characterised by:',
        'option_a': 'Strict punishment for all mistakes',
        'option_b': 'Mutual respect, collaboration, high expectations, and a shared vision for success',
        'option_c': 'Competition and rivalry among teachers',
        'option_d': 'Isolation of teachers from one another',
        'correct_option': 'B',
        'explanation': 'A positive school culture fosters mutual respect, collaboration, shared responsibility for student success, high expectations, and a welcoming environment for all stakeholders — students, teachers, and parents.',
    },
    {
        'domain': 'leadership',
        'topic': 'Circuit Supervision',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Circuit Supervisor\'s role in the education system includes:',
        'option_a': 'Teaching classes in schools',
        'option_b': 'Monitoring schools, providing professional support, and reporting to the District Education Directorate',
        'option_c': 'Managing the district\'s finances independently',
        'option_d': 'Appointing and dismissing headteachers',
        'correct_option': 'B',
        'explanation': 'Circuit Supervisors serve as the link between schools and the District Education Directorate, conducting school visits, monitoring teaching quality, providing professional support, and reporting on school performance.',
    },
    {
        'domain': 'leadership',
        'topic': 'Data-Driven Decision Making',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'A headteacher discovers that JHS 2 Mathematics scores have dropped significantly. The best data-driven response is to:',
        'option_a': 'Blame the Mathematics teacher publicly',
        'option_b': 'Analyse assessment data to identify specific topic gaps, provide targeted support, and monitor progress',
        'option_c': 'Ignore the data because one set of scores is not important',
        'option_d': 'Cancel Mathematics classes until scores improve',
        'correct_option': 'B',
        'explanation': 'Data-driven decision making involves systematically analysing assessment results to identify specific areas of weakness, developing targeted interventions, providing teacher support, and monitoring the impact of those interventions.',
    },
    {
        'domain': 'leadership',
        'topic': 'PTA Collaboration',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The Parent-Teacher Association (PTA) primarily serves to:',
        'option_a': 'Replace the role of the headteacher',
        'option_b': 'Foster collaboration between parents and teachers to support student learning and school development',
        'option_c': 'Only raise money for teachers\' personal needs',
        'option_d': 'Discipline teachers who arrive late',
        'correct_option': 'B',
        'explanation': 'The PTA is a collaborative platform that brings parents and teachers together to discuss student welfare, support school improvement initiatives, mobilise resources, and strengthen the home-school partnership.',
    },
    {
        'domain': 'leadership',
        'topic': 'Instructional Leadership',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'An instructional leader differs from a purely administrative leader in that an instructional leader:',
        'option_a': 'Focuses only on budgets and logistics',
        'option_b': 'Prioritises improving the quality of teaching and learning as the core mission',
        'option_c': 'Avoids classroom visits altogether',
        'option_d': 'Handles only student discipline matters',
        'correct_option': 'B',
        'explanation': 'Instructional leadership places teaching and learning at the centre of all leadership activity. Instructional leaders regularly observe classrooms, support teacher development, and use data to drive improvement in student outcomes.',
    },
    {
        'domain': 'leadership',
        'topic': 'Record Management',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Essential school records that must be properly maintained include all EXCEPT:',
        'option_a': 'Admission register and attendance records',
        'option_b': 'Financial records and inventory',
        'option_c': 'Personal social media accounts of teachers',
        'option_d': 'Staff meeting minutes and correspondence files',
        'correct_option': 'C',
        'explanation': 'Essential school records include the admission register, attendance records, academic records, financial books, inventory registers, staff records, minutes, and correspondence. Personal social media is not a school record.',
    },
    {
        'domain': 'leadership',
        'topic': 'Disaster Preparedness',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'A school safety plan should include:',
        'option_a': 'Only fire drills',
        'option_b': 'Emergency evacuation procedures, first aid provisions, and communication protocols for various emergencies',
        'option_c': 'A plan to close the school permanently',
        'option_d': 'Information only available to the headteacher',
        'correct_option': 'B',
        'explanation': 'A comprehensive school safety plan addresses multiple hazards (fire, floods, health emergencies) with clear evacuation routes, communication protocols, first aid provisions, and regular drills involving all stakeholders.',
    },
    {
        'domain': 'leadership',
        'topic': 'Distributed Leadership',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Distributed leadership in schools means:',
        'option_a': 'The headteacher makes all decisions alone',
        'option_b': 'Leadership responsibilities are shared among staff at multiple levels based on expertise',
        'option_c': 'Students lead the school without adult supervision',
        'option_d': 'Only department heads have any leadership role',
        'correct_option': 'B',
        'explanation': 'Distributed leadership recognises that leadership functions can be shared among headteachers, department heads, senior teachers, and other staff based on expertise, creating a more collaborative and empowered school community.',
    },
    {
        'domain': 'leadership',
        'topic': 'Resource Management',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Effective management of school textbooks and teaching materials includes:',
        'option_a': 'Locking all materials in the headteacher\'s office permanently',
        'option_b': 'Maintaining an inventory, distributing materials equitably, and ensuring proper retrieval at term end',
        'option_c': 'Allowing students to take textbooks home permanently',
        'option_d': 'Purchasing new materials every term regardless of existing stock',
        'correct_option': 'B',
        'explanation': 'Resource management requires maintaining accurate inventories, equitable distribution to students and teachers, proper storage, retrieval systems, and planned replenishment to ensure learning materials are available when needed.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOMAIN 5: EDUCATION POLICY & LAW (17 questions)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'domain': 'policy',
        'topic': 'Free SHS Policy',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The Free Senior High School (Free SHS) policy was launched in Ghana in:',
        'option_a': '2010',
        'option_b': '2017',
        'option_c': '2020',
        'option_d': '2015',
        'correct_option': 'B',
        'explanation': 'The Free SHS policy was launched in September 2017 under President Nana Addo Dankwa Akufo-Addo\'s government, eliminating tuition, boarding, and other fees for public SHS students to increase access to secondary education.',
    },
    {
        'domain': 'policy',
        'topic': 'Education Act',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Education Act 2008 (Act 778) established which of the following?',
        'option_a': 'Only the Ghana Education Service',
        'option_b': 'A comprehensive legal framework for pre-tertiary education including compulsory basic education',
        'option_c': 'The abolition of all private schools',
        'option_d': 'A university entrance examination',
        'correct_option': 'B',
        'explanation': 'Act 778 provides the comprehensive legal framework governing pre-tertiary education in Ghana, mandating compulsory Free Compulsory Universal Basic Education (fCUBE), and establishing governance structures for the education sector.',
    },
    {
        'domain': 'policy',
        'topic': 'fCUBE',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The Free Compulsory Universal Basic Education (fCUBE) policy guarantees:',
        'option_a': 'Free university education for all Ghanaians',
        'option_b': 'Free and compulsory education from Kindergarten through Junior High School for all children',
        'option_c': 'Free education only for boys',
        'option_d': 'Free education only in urban areas',
        'correct_option': 'B',
        'explanation': 'The fCUBE policy, enshrined in the 1992 Constitution (Article 25) and operationalised through various education reforms, guarantees every child the right to free, compulsory basic education from KG through JHS.',
    },
    {
        'domain': 'policy',
        'topic': 'Child Protection',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'Under Ghana\'s Children\'s Act 1998 (Act 560), which of the following is TRUE about corporal punishment in schools?',
        'option_a': 'It is encouraged as the most effective disciplinary method',
        'option_b': 'It is permitted only by the headteacher',
        'option_c': 'It is prohibited as it violates children\'s rights to dignity and protection from harm',
        'option_d': 'It is allowed during examination periods only',
        'correct_option': 'C',
        'explanation': 'The Children\'s Act 1998 (Act 560) and subsequent GES directives prohibit corporal punishment in schools, recognising children\'s right to dignity and protection from physical and emotional harm. Alternative disciplinary approaches must be used.',
    },
    {
        'domain': 'policy',
        'topic': 'Gender Parity',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Ghana\'s education policies promote gender parity in education by:',
        'option_a': 'Restricting boys\' enrolment to match girls\' numbers',
        'option_b': 'Implementing targeted interventions to increase girls\' enrolment, retention, and completion rates',
        'option_c': 'Separating boys and girls into different school systems',
        'option_d': 'Eliminating co-educational schools',
        'correct_option': 'B',
        'explanation': 'Gender parity policies include targeted interventions such as the Girls\' Education Unit programmes, mentoring, scholarship schemes, addressing barriers like early pregnancy and child marriage, and creating girl-friendly school environments.',
    },
    {
        'domain': 'policy',
        'topic': 'Inclusive Education Policy',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'Ghana\'s Inclusive Education Policy requires that:',
        'option_a': 'All children with disabilities attend separate special schools',
        'option_b': 'Schools make reasonable adjustments to accommodate learners with diverse needs in mainstream settings',
        'option_c': 'Only academically gifted students receive additional support',
        'option_d': 'Inclusive education applies only at the SHS level',
        'correct_option': 'B',
        'explanation': 'The Inclusive Education Policy mandates that mainstream schools make reasonable adjustments to accommodate learners with diverse needs, including physical, intellectual, and sensory disabilities, in line with the Persons with Disability Act 2006 (Act 715).',
    },
    {
        'domain': 'policy',
        'topic': 'GES Act',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The Ghana Education Service Act 1995 (Act 506) established the GES under the supervision of:',
        'option_a': 'The Ministry of Health',
        'option_b': 'The Ministry of Education acting through the GES Council',
        'option_c': 'The Office of the President directly',
        'option_d': 'The Judicial Service',
        'correct_option': 'B',
        'explanation': 'Act 506 established the GES as an implementing agency under the Ministry of Education, governed by the GES Council which oversees policy implementation, staffing, and management of pre-tertiary education.',
    },
    {
        'domain': 'policy',
        'topic': 'Education Strategic Plan',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The Education Strategic Plan (ESP) primarily serves to:',
        'option_a': 'Set examination dates for the year',
        'option_b': 'Provide a medium-term policy framework aligning education goals with national development priorities',
        'option_c': 'Determine individual school timetables',
        'option_d': 'Regulate teacher dress codes',
        'correct_option': 'B',
        'explanation': 'The ESP is a multi-year strategic document that sets education sector goals aligned with national development priorities (e.g., SDG 4), defines strategies for achieving quality, access, and equity, and guides resource allocation.',
    },
    {
        'domain': 'policy',
        'topic': 'Right to Education',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'According to the 1992 Constitution of Ghana, basic education is:',
        'option_a': 'Optional for all citizens',
        'option_b': 'Free, compulsory, and available to all',
        'option_c': 'Free only for children of government employees',
        'option_d': 'Compulsory only in Accra and Kumasi',
        'correct_option': 'B',
        'explanation': 'Article 25 of the 1992 Constitution of Ghana guarantees that basic education shall be free, compulsory, and available to all children, establishing education as a fundamental right for every Ghanaian child.',
    },
    {
        'domain': 'policy',
        'topic': 'Single-Track System',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Double-Track system introduced in some SHS schools was primarily designed to:',
        'option_a': 'Reduce the quality of education',
        'option_b': 'Manage increased enrolment from Free SHS by operating two sets of students in rotation',
        'option_c': 'Create two different curricula',
        'option_d': 'Allow schools to charge higher fees',
        'correct_option': 'B',
        'explanation': 'The Double-Track system was introduced in 2018 to manage the surge in enrolment following the Free SHS policy. It operates two semester tracks in alternating sessions, maximising existing infrastructure capacity.',
    },
    {
        'domain': 'policy',
        'topic': 'School Feeding Programme',
        'difficulty': 'easy',
        'source': 'practice',
        'question_text': 'The Ghana School Feeding Programme (GSFP) was established to:',
        'option_a': 'Replace school canteens with fast food restaurants',
        'option_b': 'Provide one nutritious meal per day to public basic school pupils to boost enrolment and attendance',
        'option_c': 'Feed only teachers during school hours',
        'option_d': 'Provide three meals a day for SHS students',
        'correct_option': 'B',
        'explanation': 'The GSFP provides one hot nutritious meal per school day to pupils in public basic schools, aiming to increase enrolment, reduce hunger-related absenteeism, improve nutritional status, and boost local food production.',
    },
    {
        'domain': 'policy',
        'topic': 'Teacher Conditions of Service',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Conditions of Service for teachers in Ghana are negotiated through:',
        'option_a': 'Individual teacher-headteacher agreements',
        'option_b': 'Collective bargaining between teacher unions (e.g., GNAT, NAGRAT) and the government',
        'option_c': 'Instructions from international organisations',
        'option_d': 'Social media discussions',
        'correct_option': 'B',
        'explanation': 'Teacher conditions of service (salaries, allowances, leave provisions) are negotiated through collective bargaining between recognised teacher unions such as GNAT, NAGRAT, and CCT, and the government through the Fair Wages and Salaries Commission.',
    },
    {
        'domain': 'policy',
        'topic': 'SDG 4',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'Sustainable Development Goal 4 (SDG 4) calls for:',
        'option_a': 'Eliminating all forms of education by 2030',
        'option_b': 'Ensuring inclusive and equitable quality education and promoting lifelong learning opportunities for all',
        'option_c': 'Privatising all government schools',
        'option_d': 'Reducing the school week to three days',
        'correct_option': 'B',
        'explanation': 'SDG 4, adopted by the UN in 2015, commits nations to ensuring inclusive and equitable quality education and promoting lifelong learning opportunities for all by 2030. Ghana\'s education policies are aligned with this global goal.',
    },
    {
        'domain': 'policy',
        'topic': 'Disability Act',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The Persons with Disability Act 2006 (Act 715) mandates that educational institutions:',
        'option_a': 'Can refuse admission to persons with disabilities',
        'option_b': 'Must provide accessible facilities and make reasonable accommodations for persons with disabilities',
        'option_c': 'Are exempt from accessibility requirements',
        'option_d': 'Should admit persons with disabilities only into special schools',
        'correct_option': 'B',
        'explanation': 'Act 715 requires educational institutions to make their facilities accessible and provide reasonable accommodations for persons with disabilities, ensuring they can participate fully in education without discrimination.',
    },
    {
        'domain': 'policy',
        'topic': 'Early Childhood Education',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Early Childhood Care and Development (ECCD) policy in Ghana covers:',
        'option_a': 'Only children aged 10-15',
        'option_b': 'Children from birth to 8 years, with KG1 and KG2 forming the first years of basic education',
        'option_c': 'Only children in private schools',
        'option_d': 'Children in SHS only',
        'correct_option': 'B',
        'explanation': 'The ECCD policy covers children from birth to 8 years. Under the education reform, two years of Kindergarten (KG1 and KG2) for children aged 4-5 became part of the basic education structure, making basic education a 13-year programme.',
    },
    {
        'domain': 'policy',
        'topic': 'CSSPS',
        'difficulty': 'medium',
        'source': 'practice',
        'question_text': 'The Computerised School Selection and Placement System (CSSPS) is used to:',
        'option_a': 'Assign teachers to schools',
        'option_b': 'Place JHS graduates into Senior High Schools based on BECE performance and school choices',
        'option_c': 'Determine university admissions',
        'option_d': 'Schedule school examinations',
        'correct_option': 'B',
        'explanation': 'The CSSPS is an automated system that places JHS graduates into Senior High Schools based on their BECE results, school preferences (students select up to 4 choices), and available capacities, ensuring a transparent placement process.',
    },
    {
        'domain': 'policy',
        'topic': 'National Pre-Tertiary Education Curriculum Framework',
        'difficulty': 'hard',
        'source': 'practice',
        'question_text': 'The National Pre-Tertiary Education Curriculum Framework (NPECF) guides curriculum development in Ghana by:',
        'option_a': 'Prescribing daily lesson plans for every teacher',
        'option_b': 'Providing a coherent vision for learner outcomes, pedagogy, and assessment from KG through SHS',
        'option_c': 'Focusing exclusively on tertiary education',
        'option_d': 'Eliminating subjects from the curriculum',
        'correct_option': 'B',
        'explanation': 'The NPECF provides the overarching philosophy and framework for curriculum development from Kindergarten through SHS, ensuring coherence in learning standards, pedagogy, and assessment across all levels of pre-tertiary education.',
    },
]
