# Generated by Django 5.0 on 2026-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_localization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aura_notes',
            field=models.TextField(blank=True, default='', help_text="Teacher/admin notes for Aura — e.g. 'struggles with fractions', 'preparing for BECE', 'gifted in science'"),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('twi', 'Twi / Akan'), ('hausa', 'Hausa'), ('ewe', 'Ewe'), ('ga', 'Ga'), ('dagbani', 'Dagbani'), ('french', 'French'), ('other', 'Other')], default='english', help_text="Student's primary spoken language (informs Aura's vocabulary style)", max_length=20),
        ),
    ]
