# Generated by Django 5.0 on 2026-03-30 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_exam_schedule'),
        ('students', '0009_grade_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'term'], name='grade_student_term_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='grade_student_year_term_idx'),
        ),
    ]
