# Generated by Django 5.0 on 2026-04-06 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_add_grade_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aura_notes',
            field=models.TextField(blank=True, default='', help_text="Teacher/admin notes for SchoolPadi — e.g. 'struggles with fractions', 'preparing for BECE', 'gifted in science'"),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('twi', 'Twi / Akan'), ('hausa', 'Hausa'), ('ewe', 'Ewe'), ('ga', 'Ga'), ('dagbani', 'Dagbani'), ('french', 'French'), ('other', 'Other')], default='english', help_text="Student's primary spoken language (informs SchoolPadi's vocabulary style)", max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='att_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='att_date_status_idx'),
        ),
    ]
