"""
One-off script to apply pending migrations to the GirlsModel tenant schema.
Run: python fix_girlsmodel_migrations.py
"""
import os
import sys
import django

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'school_system.settings')
django.setup()

from django.db import connection
from django_tenants.utils import schema_context

SCHEMA = 'GirlsModel'

def apply_migration_sql(cursor, sql):
    try:
        cursor.execute(sql)
        return True
    except Exception as e:
        print(f"  SQL ERROR: {e}")
        return False

print(f"\n{'='*60}")
print(f"Applying pending migrations to schema: {SCHEMA}")
print(f"{'='*60}\n")

with connection.cursor() as cursor:
    # Switch to the target schema
    cursor.execute(f'SET search_path TO "{SCHEMA}", public')

    # ── 1. academics.0021_studygrouproom_studygroupmessage ────────────
    print("[1/3] academics.0021 – StudyGroupRoom & StudyGroupMessage")

    # Check if tables already exist
    cursor.execute("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = %s
        AND table_name IN ('academics_studygrouproom', 'academics_studygroupmessage')
    """, [SCHEMA])
    existing = {r[0] for r in cursor.fetchall()}

    if 'academics_studygrouproom' not in existing:
        print("  Creating academics_studygrouproom...")
        cursor.execute(f"""
            CREATE TABLE "{SCHEMA}".academics_studygrouproom (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name character varying(200) NOT NULL,
                is_global boolean NOT NULL DEFAULT false,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                student_class_id bigint
                    REFERENCES "{SCHEMA}".academics_class(id)
                    ON DELETE CASCADE
                    DEFERRABLE INITIALLY DEFERRED
            )
        """)
        print("  ✅ Created academics_studygrouproom")
    else:
        print("  ⏭  academics_studygrouproom already exists")

    if 'academics_studygroupmessage' not in existing:
        print("  Creating academics_studygroupmessage...")
        cursor.execute(f"""
            CREATE TABLE "{SCHEMA}".academics_studygroupmessage (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content text NOT NULL,
                is_aura boolean NOT NULL DEFAULT false,
                is_battle_question boolean NOT NULL DEFAULT false,
                battle_answered boolean NOT NULL DEFAULT false,
                battle_answer character varying(255),
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                battle_winner_id integer
                    REFERENCES "{SCHEMA}".accounts_user(id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED,
                room_id bigint NOT NULL
                    REFERENCES "{SCHEMA}".academics_studygrouproom(id)
                    ON DELETE CASCADE
                    DEFERRABLE INITIALLY DEFERRED,
                sender_id integer
                    REFERENCES "{SCHEMA}".accounts_user(id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED
            )
        """)
        print("  ✅ Created academics_studygroupmessage")
    else:
        print("  ⏭  academics_studygroupmessage already exists")

    # Record this migration in django_migrations
    cursor.execute(f"""
        INSERT INTO "{SCHEMA}".django_migrations (app, name, applied)
        VALUES ('academics', '0021_studygrouproom_studygroupmessage', now())
        ON CONFLICT DO NOTHING
    """)
    print("  ✅ Recorded academics.0021 in django_migrations")

    # ── 2. students.0007_add_preferred_language_and_aura_notes ────────
    print("\n[2/3] students.0007 – preferred_language & aura_notes")

    cursor.execute("""
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = %s
        AND table_name = 'students_student'
        AND column_name IN ('preferred_language', 'aura_notes')
    """, [SCHEMA])
    existing_cols = {r[0] for r in cursor.fetchall()}

    if 'preferred_language' not in existing_cols:
        print("  Adding preferred_language column...")
        cursor.execute(f"""
            ALTER TABLE "{SCHEMA}".students_student
            ADD COLUMN preferred_language character varying(20) NOT NULL DEFAULT 'english'
        """)
        print("  ✅ Added preferred_language")
    else:
        print("  ⏭  preferred_language already exists")

    if 'aura_notes' not in existing_cols:
        print("  Adding aura_notes column...")
        cursor.execute(f"""
            ALTER TABLE "{SCHEMA}".students_student
            ADD COLUMN aura_notes text NOT NULL DEFAULT ''
        """)
        print("  ✅ Added aura_notes")
    else:
        print("  ⏭  aura_notes already exists")

    # Record this migration
    cursor.execute(f"""
        INSERT INTO "{SCHEMA}".django_migrations (app, name, applied)
        VALUES ('students', '0007_add_preferred_language_and_aura_notes', now())
        ON CONFLICT DO NOTHING
    """)
    print("  ✅ Recorded students.0007 in django_migrations")

    # ── 3. Verify ─────────────────────────────────────────────────────
    print("\n[3/3] Verification")

    cursor.execute("""
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = %s
        AND table_name = 'students_student'
        AND column_name IN ('preferred_language', 'aura_notes')
        ORDER BY column_name
    """, [SCHEMA])
    cols = [r[0] for r in cursor.fetchall()]
    print(f"  students_student new columns: {cols}")

    cursor.execute("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = %s
        AND table_name IN ('academics_studygrouproom', 'academics_studygroupmessage')
        ORDER BY table_name
    """, [SCHEMA])
    tables = [r[0] for r in cursor.fetchall()]
    print(f"  New tables: {tables}")

    expected_cols = {'preferred_language', 'aura_notes'}
    expected_tables = {'academics_studygrouproom', 'academics_studygroupmessage'}
    if expected_cols.issubset(set(cols)) and expected_tables.issubset(set(tables)):
        print(f"\n✅ SUCCESS: {SCHEMA} schema is fully up to date!")
    else:
        print(f"\n❌ INCOMPLETE: some items still missing")

print(f"\n{'='*60}\n")
