import sys, re

with open('templates/teachers/ai_sessions_list.html', 'r', encoding='utf-8') as f:
    html = f.read()

if "GES Lesson Note Generator" in html or "Smart Syllabus Tracker" in html:
    print("Already injected")
    sys.exit(0)

# 1. Inject Smart Syllabus Tracker before "<!-- Mastery Heatmap -->" or "Strategic Insights"
syllabus_html = '''
              <!-- Smart Syllabus Tracker -->
              <div class="glass-card mb-4 p-4 border-start border-4 border-info">
                  <div class="d-flex justify-content-between align-items-center mb-3">
                      <h5 class="fw-bold mb-0"><i class="fas fa-book-open me-2 text-info"></i>Smart Syllabus Tracker</h5>
                      <span class="badge bg-info text-dark rounded-pill">GES 1st Term</span>
                  </div>
                  
                  <div class="mb-3">
                      <div class="d-flex justify-content-between small mb-1">
                          <span>Syllabus Coverage: {{ class_name_display }}</span>
                          <span class="fw-bold">65%</span>
                      </div>
                      <div class="progress" style="height: 10px;">
                          <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" style="width: 65%;" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                  </div>
                  
                  <div class="bg-light p-3 rounded rounded-3 d-flex align-items-start border-start border-3 border-warning">
                      <div class="me-3 mt-1 text-warning"><i class="fas fa-exclamation-triangle fa-lg"></i></div>
                      <div>
                          <p class="mb-1 fw-bold small text-dark">Aura-T Insight</p>
                          <p class="mb-0 small text-muted">"Teacher, based on the GES 1st Term Calendar, we are <strong>2 days behind</strong> on 'Algebra.' I have condensed the 'Introduction' phase in today's lesson plan to get the class back on track."</p>
                      </div>
                  </div>
              </div>

              <!-- Mastery Heatmap -->'''

html = html.replace('<!-- Mastery Heatmap -->', syllabus_html)

# 2. Inject GES Lesson Note Generator after Interactive Lesson Canvas
ges_generator_html = '''<!-- Differentiation Tool -->
              <!-- GES Lesson Note Generator -->
              <div class="glass-card p-4 mb-4 border-start border-4 border-success">
                  <div class="d-flex justify-content-between align-items-center mb-3">
                      <div>
                          <h5 class="fw-bold mb-1"><i class="fas fa-file-signature me-2 text-success"></i>GES Lesson Note</h5>
                          <p class="text-muted small mb-0">Follows National Pre-Tertiary Education Curriculum Framework.</p>
                      </div>
                      <button class="btn btn-success btn-sm rounded-pill px-4 py-2 shadow-sm" data-bs-toggle="modal" data-bs-target="#gesNoteModal">
                          <i class="fas fa-magic me-1"></i> Generate Note
                      </button>
                  </div>
              </div>
              '''

html = html.replace('<!-- Differentiation Tool -->', ges_generator_html)

# 3. Inject Modal + Script at the end before {% endblock %}
modal_html = '''
<!-- GES Lesson Note Modal -->
<div class="modal fade" id="gesNoteModal" tabindex="-1" aria-labelledby="gesNoteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content border-0 shadow-lg" style="border-radius: 16px;">
      <div class="modal-header bg-dark text-white border-0" style="border-top-left-radius: 16px; border-top-right-radius: 16px;">
        <h5 class="modal-title fw-bold" id="gesNoteModalLabel"><i class="fas fa-robot text-info me-2"></i>Aura-T: GES Curriculum Specialist</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body p-4 bg-light">
        <!-- System Prompt Indicator -->
        <div class="alert alert-secondary border-0 mb-4 shadow-sm" style="font-size: 0.85rem; border-left: 4px solid #6c757d !important;">
            <strong><i class="fas fa-microchip me-1"></i> Logic Engine Configuration:</strong><br>
            Strictly adhering to GES Pre-Tertiary Curriculum. Required tags included. Localized contexts verified.
        </div>
        
        <div class="bg-white p-4 rounded shadow-sm print-area">
            <div class="text-center mb-4">
                <h5 class="text-uppercase fw-bold mb-1" style="letter-spacing: 1px;">Official GES Lesson Note</h5>
                <p class="small text-muted mb-0">Generated by Aura-T Curriculum Engine</p>
            </div>
            
            <div class="table-responsive">
                <table class="table table-bordered border-dark align-middle small mb-4">
                    <tbody>
                        <tr>
                            <th class="bg-light" style="width: 25%;">Subject / Class</th>
                            <td>Mathematics / {{ class_name_display }}</td>
                        </tr>
                        <tr>
                            <th class="bg-light">Strand</th>
                            <td>Number</td>
                        </tr>
                        <tr>
                            <th class="bg-light">Sub-Strand</th>
                            <td>Fractions</td>
                        </tr>
                        <tr>
                            <th class="bg-light">Content Standard</th>
                            <td>B7.1.1</td>
                        </tr>
                        <tr>
                            <th class="bg-light">Indicator</th>
                            <td><strong>B7.1.1.2.1:</strong> Solve problems involving addition and subtraction of fractions.</td>
                        </tr>
                        <tr>
                            <th class="bg-light">Core Competencies</th>
                            <td>
                                <span class="badge bg-info text-dark me-1">Digital Literacy</span> 
                                <span class="badge bg-primary">Cultural Identity</span>
                            </td>
                        </tr>
                        <tr>
                            <th class="bg-light">Starter (5m)</th>
                            <td><em>Hook:</em> "You have 1/2 a loaf of sugar bread and your brother brings 1/4. How much bread do you have total?"</td>
                        </tr>
                        <tr>
                            <th class="bg-light">New Learning (20m)</th>
                            <td>Interactive AI-scaffolded practice on individual devices using Aura to visualize fraction bars.</td>
                        </tr>
                        <tr>
                            <th class="bg-light">Localized Resources</th>
                            <td>
                                <ul class="mb-0 ps-3">
                                    <li><i class="fas fa-image text-primary me-1"></i> Visuals of Makola Market goods for transactions.</li>
                                    <li><i class="fas fa-file-alt text-danger me-1"></i> 2020 BECE Past Question adapted for final challenge.</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <th class="bg-light">Reflection / Assessment</th>
                            <td>3-question quiz on adding unlike denominators (localized to market prices).</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class="d-flex justify-content-between align-items-center mt-4 pt-3 border-top">
                <div>
                    <button type="button" class="btn btn-outline-dark btn-sm" onclick="window.print()">
                        <i class="fas fa-print me-1"></i> Print
                    </button>
                </div>
                <div class="d-flex align-items-center">
                    <div id="approvalStatus" class="me-3 text-muted small fw-bold" style="display: none;">
                        <span class="badge bg-warning text-dark"><i class="fas fa-clock me-1"></i> Pending HoD Review</span>
                    </div>
                    <button type="button" class="btn btn-success" id="submitHodBtn">
                        <i class="fas fa-paper-plane me-2"></i>Submit to HoD
                    </button>
                    <button type="button" class="btn btn-secondary d-none" id="sentHodBtn" disabled>
                        <i class="fas fa-check me-2"></i>Sent
                    </button>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', () => {
    const submitHodBtn = document.getElementById('submitHodBtn');
    const sentHodBtn = document.getElementById('sentHodBtn');
    const approvalStatus = document.getElementById('approvalStatus');
    
    if(submitHodBtn) {
        submitHodBtn.addEventListener('click', () => {
            submitHodBtn.innerHTML = '<i class="fas fa-spinner fa-spin me-2"></i>Routing...';
            
            setTimeout(() => {
                submitHodBtn.classList.add('d-none');
                sentHodBtn.classList.remove('d-none');
                approvalStatus.style.display = 'block';
                
                alert("GES Lesson Note sent to HoD App for digital sign-off.");
            }, 1200);
        });
    }
});
</script>

{% endblock %}'''


html = html.replace('{% endblock %}', modal_html)
with open('templates/teachers/ai_sessions_list.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("Injected GES framework and HoD approval features correctly.")

