# Generated by Django 5.0 on 2026-03-11 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Receipt number or Transaction ID', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('reference',), name='unique_non_empty_reference'),
        ),
    ]
