# Generated by Django 5.0 on 2026-03-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_unique_reference_constraint'),
        ('teachers', '0017_alter_livesession_id_alter_pollresponse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='assigned_collector',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for collecting this fee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collection_tasks', to='teachers.teacher', verbose_name='Assigned Collector'),
        ),
    ]
