# Generated by Django 5.0 on 2026-04-06 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_exam_schedule'),
        ('finance', '0003_add_assigned_collector_to_feestructure'),
        ('students', '0011_alter_student_aura_notes_and_more'),
        ('teachers', '0027_credit_token_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['class_level', 'academic_year', 'term'], name='fs_class_year_term_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student_fee', 'date'], name='pay_fee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date', 'method'], name='pay_date_method_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'status'], name='sf_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['status', 'created_at'], name='sf_status_created_idx'),
        ),
    ]
