# Generated by Django 5.0 on 2026-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='Ghana', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary School (Class 1-6)'), ('jhs', 'Junior High School (JHS 1-3)'), ('shs', 'Senior High School'), ('basic', 'Basic School (Kindergarten - JHS 3)'), ('other', 'Other / Tertiary')], default='basic', max_length=20),
        ),
    ]
