# Generated by Django 5.0 on 2026-01-16 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_address_school_country_school_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Any additional verification documents', null=True, upload_to='school_credentials/additional/'),
        ),
        migrations.AddField(
            model_name='school',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin review'),
        ),
        migrations.AddField(
            model_name='school',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_info', 'Requires More Information')], default='pending', help_text='Current approval status of the school', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_title',
            field=models.CharField(blank=True, help_text='e.g., Principal, Headmaster, Administrator', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='registration_certificate',
            field=models.FileField(blank=True, help_text='School registration certificate or license', null=True, upload_to='school_credentials/registration/'),
        ),
        migrations.AddField(
            model_name='school',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='school',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='tax_id_document',
            field=models.FileField(blank=True, help_text='Tax identification document', null=True, upload_to='school_credentials/tax/'),
        ),
    ]
