# Generated by Django 5.0 on 2026-01-16 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_school_additional_documents_school_admin_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ai', 'AI & Automation'), ('analytics', 'Analytics & Reporting'), ('communication', 'Communication'), ('integration', 'Integrations'), ('storage', 'Storage & Resources'), ('feature', 'Premium Features')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-plus-circle', help_text='Bootstrap icon class', max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_one_time', models.BooleanField(default=False, help_text='One-time purchase vs recurring')),
                ('is_active', models.BooleanField(default=True)),
                ('available_for_plans', models.JSONField(default=list, help_text='List of plan_types that can purchase this add-on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quarterly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_students', models.IntegerField(default=100, help_text='Maximum students allowed')),
                ('max_teachers', models.IntegerField(default=20, help_text='Maximum teachers allowed')),
                ('max_storage_gb', models.IntegerField(default=10, help_text='Storage limit in GB')),
                ('custom_domain', models.BooleanField(default=False)),
                ('white_label', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, help_text='Monthly Recurring Revenue', max_digits=10)),
                ('current_students', models.IntegerField(default=0)),
                ('current_teachers', models.IntegerField(default=0)),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('line_items', models.JSONField(default=list, help_text='List of invoice items')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.schoolsubscription')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('price', 'Too Expensive'), ('features', 'Missing Features'), ('support', 'Poor Support'), ('competitor', 'Switched to Competitor'), ('closure', 'School Closed'), ('other', 'Other')], max_length=20)),
                ('reason_detail', models.TextField(blank=True)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('months_subscribed', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_events', to='tenants.school')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.schoolsubscription')),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.addon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_addons', to='tenants.schoolsubscription')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('subscription', 'addon')},
            },
        ),
    ]
