# Generated by Django 5.0 on 2026-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_addon_category_supportticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary School (KG 1 – B6)'), ('jhs', 'Junior High School (JHS 1-3)'), ('shs', 'Senior High School (SHS 1-3)'), ('basic', 'Basic School (KG 1 – JHS 3)'), ('other', 'Other / Tertiary')], default='basic', max_length=20),
        ),
    ]
