# Generated by Django 5.0 on 2026-03-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_aiusagelog_ai_calls_per_month'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='tenants_aiu_school__b45413_idx',
            old_name='tenants_aiu_school_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='tenants_aiu_school__acfa3f_idx',
            old_name='tenants_aiu_school_action_idx',
        ),
    ]
