# Generated by Django 5.0 on 2026-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_rename_tenants_aiu_school_created_idx_tenants_aiu_school__b45413_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_template', models.CharField(choices=[('home/classic.html', 'Classic — Sidebar Navigation'), ('home/modern.html', 'Modern — Bold Hero'), ('home/minimal.html', 'Minimal — Clean Cards'), ('home/playful.html', 'Playful — Colourful & Animated'), ('home/elegant.html', 'Elegant — Navy / Gold'), ('home/swiss.html', 'Swiss — Grid System')], default='home/swiss.html', help_text='Which landing page template to show at /', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
