# Generated by Django 5.0 on 2026-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_paystack_and_payment_reference_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='landing_template',
            field=models.CharField(choices=[('home/classic.html', 'Classic — Sidebar Navigation'), ('home/modern.html', 'Modern — Bold Hero'), ('home/minimal.html', 'Minimal — Clean Cards'), ('home/playful.html', 'Playful — Colourful & Animated'), ('home/elegant.html', 'Elegant — Navy / Gold'), ('home/swiss.html', 'Swiss — Grid System'), ('home/glass.html', 'Glass — Digital Lucidity'), ('home/artdeco.html', 'Art Deco — Gilded Authority'), ('home/japandi.html', 'Japandi — Natural Clarity')], default='home/swiss.html', help_text='Which landing page template to show at /', max_length=60),
        ),
    ]
