# Generated by Django 5.0 on 2026-04-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_update_plan_prices_to_ghs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('body_html', models.TextField(help_text='HTML email body')),
                ('audience', models.CharField(choices=[('all_schools', 'All Active Schools'), ('trial_schools', 'Trial Schools Only'), ('approved_schools', 'Approved Schools Only'), ('individual_teachers', 'Individual Portal Teachers'), ('individual_all', 'All Individual Portal Users')], default='all_schools', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Campaign',
                'ordering': ['-created_at'],
            },
        ),
    ]
