# Generated by Django 5.0 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_landlord_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocampaign',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Schedule send for a future date/time (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='promocampaign',
            name='template_key',
            field=models.CharField(blank=True, choices=[('', 'Custom (write your own)'), ('feature_launch', 'Feature Launch'), ('back_to_school', 'Back to School'), ('discount_offer', 'Discount / Promo Offer'), ('re_engagement', 'Re-engagement'), ('newsletter', 'Newsletter Update')], default='', help_text='Pre-built email template style', max_length=30),
        ),
        migrations.AlterField(
            model_name='promocampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
    ]
