# Generated by Django 5.0 on 2026-04-06 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_promocampaign_scheduled_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSharedBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The shared knowledge or artifact')),
                ('category', models.CharField(choices=[('insight', 'Key Insight'), ('decision', 'Decision Made'), ('asset', 'Content Asset'), ('request', 'Request for Input'), ('data', 'Data / Analysis')], default='insight', max_length=20)),
                ('source_agent', models.CharField(choices=[('pmm', 'Product Marketing Manager'), ('curriculum', 'Curriculum Analyst'), ('content', 'Content Creator')], help_text='Which agent produced this brief', max_length=20)),
                ('pinned', models.BooleanField(default=False, help_text='Pinned briefs always appear in agent context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_shared_briefs', to=settings.AUTH_USER_MODEL)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_briefs', to='tenants.landlordagentconversation')),
            ],
            options={
                'verbose_name': 'Agent Shared Brief',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
