# Generated by Django 5.0 on 2026-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_agent_shared_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscription',
            name='grace_period_days',
            field=models.IntegerField(default=3, help_text='Days after trial/period expiry before hard lock-out'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('user_create', 'User Created'), ('user_delete', 'User Deleted'), ('permission_change', 'Permission Change'), ('subscription_change', 'Subscription Change'), ('school_approve', 'School Approved'), ('school_reject', 'School Rejected'), ('data_export', 'Data Export'), ('admin_action', 'Admin Action')], max_length=30)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=63)),
                ('detail', models.TextField(blank=True, help_text='JSON or free-text detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='tenants_aud_action_9c4dec_idx'), models.Index(fields=['user_id', 'created_at'], name='tenants_aud_user_id_e62ef0_idx')],
            },
        ),
    ]
