# Generated by Django 5.0 on 2026-04-06 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_audit_log_and_grace_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, default='', max_length=300)),
                ('cta_text', models.CharField(default='Learn More', max_length=40)),
                ('cta_link', models.CharField(blank=True, default='', max_length=500)),
                ('style', models.CharField(choices=[('gradient', 'Gradient'), ('glass', 'Glass'), ('bold', 'Bold'), ('minimal', 'Minimal')], default='gradient', max_length=12)),
                ('audience', models.CharField(choices=[('all', 'All Schools'), ('admins', 'School Admins'), ('teachers', 'Teachers'), ('students', 'Students'), ('parents', 'Parents')], default='all', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_agent', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'ordering': ['-created_at'],
            },
        ),
    ]
