# Generated by Django 5.0 on 2026-04-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_add_promo_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBannerDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='tenants.promobanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_promos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('banner', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PromoBannerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=12)),
                ('tenant_schema', models.CharField(blank=True, default='', max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.promobanner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['banner', 'event_type'], name='tenants_pro_banner__6502bb_idx'), models.Index(fields=['created_at'], name='tenants_pro_created_2a9c59_idx')],
            },
        ),
    ]
