# Generated by Django 5.0 on 2026-04-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_promo_tracking_dismissal_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(help_text='Day number in campaign')),
                ('campaign', models.CharField(default='Launch Campaign', max_length=120)),
                ('theme', models.CharField(help_text='Day theme e.g. Intro / value prop', max_length=120)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('hook', models.CharField(blank=True, default='', max_length=200)),
                ('copy', models.TextField()),
                ('cta', models.CharField(blank=True, default='', max_length=200)),
                ('cta_link', models.CharField(blank=True, default='', max_length=500)),
                ('image_note', models.CharField(blank=True, default='', help_text='Image/visual brief', max_length=300)),
                ('hashtags', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=12)),
                ('source_agent', models.CharField(blank=True, default='content', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'ordering': ['day', 'platform'],
            },
        ),
    ]
