# Generated by Django 5.0 on 2026-04-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_social_media_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsharedbrief',
            name='source_agent',
            field=models.CharField(choices=[('pmm', 'Product Marketing Manager'), ('curriculum', 'Curriculum Analyst'), ('content', 'Content Creator'), ('seo', 'SEO Specialist & Brand Manager')], help_text='Which agent produced this brief', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlordagentconversation',
            name='agent',
            field=models.CharField(choices=[('pmm', 'Product Marketing Manager'), ('curriculum', 'Curriculum Analyst'), ('content', 'Content Creator'), ('seo', 'SEO Specialist & Brand Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='audience',
            field=models.CharField(choices=[('all', 'All Schools'), ('admins', 'School Admins'), ('teachers', 'Teachers'), ('students', 'Students'), ('parents', 'Parents'), ('landlord', 'Platform Admins')], default='all', max_length=12),
        ),
    ]
