# Generated by Django 5.0 on 2026-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_add_seo_agent_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsharedbrief',
            name='source_agent',
            field=models.CharField(choices=[('pmm', 'Product Marketing Manager'), ('curriculum', 'Curriculum Analyst'), ('content', 'Content Creator'), ('seo', 'SEO Specialist & Brand Lead')], help_text='Which agent produced this brief', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlordagentconversation',
            name='agent',
            field=models.CharField(choices=[('pmm', 'Product Marketing Manager'), ('curriculum', 'Curriculum Analyst'), ('content', 'Content Creator'), ('seo', 'SEO Specialist & Brand Lead')], max_length=20),
        ),
    ]
