# Generated by Django 5.0 on 2026-04-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_rename_seo_agent_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsharedbrief',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Feedback from the reviewer (pivot instructions, approval notes)'),
        ),
        migrations.AddField(
            model_name='agentsharedbrief',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsharedbrief',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revision', 'Needs Revision'), ('rejected', 'Rejected')], default='pending', help_text='HITL gate — only approved briefs are injected into agent context', max_length=12),
        ),
        migrations.CreateModel(
            name='AgentChainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(help_text='The high-level objective for the pipeline')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('current_step', models.CharField(blank=True, default='', max_length=20)),
                ('pmm_output', models.TextField(blank=True, default='')),
                ('curriculum_output', models.TextField(blank=True, default='')),
                ('content_output', models.TextField(blank=True, default='')),
                ('seo_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_chain_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
