# Generated by Django 5.0 on 2026-04-08 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_add_agent_chain_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('pmm', 'Product Marketing Manager'), ('curriculum', 'Curriculum Analyst'), ('content', 'Content Creator'), ('seo', 'SEO Specialist & Brand Lead')], max_length=20)),
                ('summary', models.TextField(help_text='AI-generated summary of conversation insights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to=settings.AUTH_USER_MODEL)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='tenants.landlordagentconversation')),
            ],
            options={
                'verbose_name_plural': 'Agent memories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'agent', '-created_at'], name='agentmem_owner_agent_idx')],
            },
        ),
    ]
