# Generated by Django 5.0 on 2026-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_lowercase_dutyweek_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyweek',
            name='term',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=15),
        ),
    ]
