# Generated by Django 5.0 on 2026-02-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_normalize_term_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGenerationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Session', max_length=200)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
