# Generated by Django 5.0 on 2026-03-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_pulse_models'),
        ('teachers', '0007_teacher_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(choices=[('aurora', 'Aurora'), ('midnight', 'Midnight'), ('forest', 'Forest'), ('coral', 'Coral'), ('slate', 'Slate')], default='aurora', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('title', 'Title Slide'), ('bullets', 'Bullet List'), ('two_col', 'Two Column'), ('big_stat', 'Big Stat'), ('quote', 'Quote'), ('summary', 'Summary')], default='bullets', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('speaker_notes', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='teachers.presentation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
