# Generated by Django 5.0 on 2026-03-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_presentation_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='theme',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('midnight', 'Midnight'), ('forest', 'Forest'), ('coral', 'Coral'), ('slate', 'Slate'), ('ocean', 'Ocean'), ('amber', 'Amber'), ('rose', 'Rose')], default='aurora', max_length=20),
        ),
    ]
