# Generated by Django 5.0 on 2026-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_add_ocean_amber_rose_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='layout',
            field=models.CharField(choices=[('title', 'Title Slide'), ('bullets', 'Bullet List'), ('two_col', 'Two Column'), ('big_stat', 'Big Stat'), ('quote', 'Quote'), ('summary', 'Summary'), ('image', 'Image + Caption')], default='bullets', max_length=20),
        ),
    ]
