# Generated by Django 5.0 on 2026-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_lessonplan_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pollresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='layout',
            field=models.CharField(choices=[('title', 'Title Slide'), ('bullets', 'Bullet List'), ('two_col', 'Two Column'), ('big_stat', 'Big Stat'), ('quote', 'Quote'), ('summary', 'Summary'), ('image', 'Image + Caption'), ('poll', 'Live Poll'), ('quiz', 'Quiz Reveal'), ('video', 'Embedded Video')], default='bullets', max_length=20),
        ),
    ]
