# Generated by Django 5.0 on 2026-03-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_alter_livesession_id_alter_pollresponse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='sub_strand',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sub Strand'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Strand'),
        ),
    ]
