# Generated by Django 5.0 on 2026-03-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_add_sub_strand_to_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='last_presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='times_presented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='transition',
            field=models.CharField(choices=[('slide', 'Slide'), ('fade', 'Fade'), ('zoom', 'Zoom'), ('flip', 'Flip'), ('swirl', 'Swirl'), ('drop', 'Drop')], default='slide', max_length=20),
        ),
    ]
