# Generated by Django 5.0 on 2026-03-30 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_add_presentation_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('ai_tools', 'AI Tools'), ('assessment', 'Assessment'), ('content', 'Content Packs'), ('professional', 'Professional Dev'), ('classroom', 'Classroom Tools')], max_length=20)),
                ('icon', models.CharField(default='bi-box-seam', help_text='Bootstrap icon class', max_length=50)),
                ('badge_label', models.CharField(blank=True, default='', help_text='e.g. "NEW", "POPULAR"', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='One-time price in school currency', max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list, help_text='["Feature 1","Feature 2",…]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'price'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAddOnPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='teachers.teacheraddon')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('teacher', 'addon')},
            },
        ),
    ]
