# Generated by Django 5.0 on 2026-03-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_teacheraddon_teacheraddonpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraddonpurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacheraddonpurchase',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
