# Generated by Django 5.0 on 2026-03-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_add_payment_fields_to_addonpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraddon',
            name='trial_days',
            field=models.PositiveIntegerField(default=0, help_text='Free trial period in days (0 = no trial)'),
        ),
        migrations.AddField(
            model_name='teacheraddonpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Null = never expires', null=True),
        ),
    ]
