# Generated by Django 5.0 on 2026-03-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_addon_feature_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraddon',
            name='quota_boost',
            field=models.PositiveIntegerField(default=0, help_text='Extra monthly AI calls added to school quota when purchased (0 = no boost)'),
        ),
    ]
