# Generated by Django 5.0 on 2026-04-02 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_wave2_report_card_exam_bank_behavior_differentiated_live_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('icon', models.CharField(default='bi-lightning-charge', max_length=50)),
                ('url_name', models.CharField(help_text='Django URL name, e.g. teachers:enter_grades', max_length=120)),
                ('color', models.CharField(default='#4361ee', help_text='CSS color or gradient', max_length=80)),
                ('position', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='teachers.teacheraddon')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('teacher', 'addon')},
            },
        ),
    ]
