# Generated by Django 5.0 on 2026-04-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_add_dashboard_pin_and_quick_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('credits', models.PositiveIntegerField(help_text='Number of credits in this pack')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in school currency (GHS)', max_digits=8)),
                ('badge_label', models.CharField(blank=True, default='', max_length=30)),
                ('icon', models.CharField(default='bi-lightning-charge', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['position', 'price'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive = added, negative = deducted')),
                ('balance_after', models.IntegerField(help_text='Balance after this transaction')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'AI Usage'), ('bonus', 'Bonus / Welcome'), ('refund', 'Refund')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Current available credits')),
                ('total_purchased', models.PositiveIntegerField(default=0, help_text='Lifetime credits purchased')),
                ('total_used', models.PositiveIntegerField(default=0, help_text='Lifetime credits consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
