# Generated by Django 5.0 on 2026-01-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
