# Generated by Django 5.0 on 2026-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0004_toolquestion_toolexampaper_toollessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='toollessonplan',
            name='b7_meta',
            field=models.JSONField(blank=True, default=None, help_text='GES lesson metadata', null=True),
        ),
        migrations.AddField(
            model_name='toollessonplan',
            name='indicator',
            field=models.CharField(blank=True, default='', help_text='GES target indicator code or statement', max_length=300),
        ),
        migrations.AddField(
            model_name='toollessonplan',
            name='sub_strand',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
