# Generated by Django 5.0 on 2026-04-02 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0005_ges_lesson_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('english', 'English Language'), ('science', 'Integrated Science'), ('social_studies', 'Social Studies'), ('computing', 'Computing / ICT'), ('french', 'French'), ('ghanaian_language', 'Ghanaian Language'), ('rme', 'Religious & Moral Education'), ('creative_arts', 'Creative Arts & Design'), ('career_tech', 'Career Technology'), ('history', 'History'), ('geography', 'Geography'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('literature', 'Literature'), ('economics', 'Economics'), ('government', 'Government'), ('other', 'Other')], default='mathematics', max_length=30)),
                ('target_class', models.CharField(blank=True, default='', max_length=60)),
                ('theme', models.CharField(choices=[('aurora', 'Aurora'), ('midnight', 'Midnight'), ('forest', 'Forest'), ('coral', 'Coral'), ('slate', 'Slate'), ('ocean', 'Ocean'), ('amber', 'Amber'), ('rose', 'Rose')], default='aurora', max_length=20)),
                ('transition', models.CharField(choices=[('slide', 'Slide'), ('fade', 'Fade'), ('zoom', 'Zoom'), ('flip', 'Flip')], default='slide', max_length=20)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('times_presented', models.PositiveIntegerField(default=0)),
                ('last_presented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_presentations', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'Tool Presentation',
                'verbose_name_plural': 'Tool Presentations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('title', 'Title Slide'), ('bullets', 'Bullet List'), ('two_col', 'Two Column'), ('big_stat', 'Big Stat'), ('quote', 'Quote'), ('summary', 'Summary'), ('image', 'Image + Caption')], default='bullets', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('speaker_notes', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('image_url', models.TextField(blank=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='individual_users.toolpresentation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
