# Generated by Django 5.0 on 2026-04-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0006_presentation_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('literacy', 'Literacy'), ('numeracy', 'Numeracy'), ('pedagogy', 'Pedagogical Knowledge'), ('management', 'Classroom Management')], max_length=20)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=8)),
                ('source', models.CharField(choices=[('gtle_2024', 'GTLE 2024'), ('gtle_2023', 'GTLE 2023'), ('gtle_2022', 'GTLE 2022'), ('gtle_2021', 'GTLE 2021'), ('gtle_2020', 'GTLE 2020'), ('practice', 'Practice'), ('ai_generated', 'AI Generated')], default='practice', max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensure_questions', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'Licensure Question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicensureQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('timed', 'Timed Exam'), ('domain', 'Domain Focus')], default='practice', max_length=12)),
                ('domain_filter', models.CharField(blank=True, default='', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('time_limit_minutes', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensure_attempts', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'Licensure Quiz Attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LicensureAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, default='', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_users.licensurequestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='individual_users.licensurequizattempt')),
            ],
            options={
                'ordering': ['pk'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
