# Generated by Django 5.0 on 2026-04-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0007_licensure_prep'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('explain', 'Concept Explainer'), ('worksheet', 'Worksheet Generator'), ('feedback', 'Marking Feedback'), ('notes', 'Study Notes Creator'), ('general', 'General Assistant')], default='general', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('english', 'English Language'), ('science', 'Integrated Science'), ('social_studies', 'Social Studies'), ('computing', 'Computing / ICT'), ('french', 'French'), ('ghanaian_language', 'Ghanaian Language'), ('rme', 'Religious & Moral Education'), ('creative_arts', 'Creative Arts & Design'), ('career_tech', 'Career Technology'), ('history', 'History'), ('geography', 'Geography'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('literature', 'Literature'), ('economics', 'Economics'), ('government', 'Government'), ('other', 'Other')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_conversations', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'AI Tutor Conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AITutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='individual_users.aitutorconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
