# Generated by Django 5.0 on 2026-04-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0008_ai_tutor_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GESLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('posting', 'Posting / Transfer'), ('leave', 'Leave of Absence'), ('promotion', 'Promotion Request'), ('complaint', 'Complaint / Grievance'), ('permission', 'Permission Request'), ('resignation', 'Resignation'), ('recommendation', 'Recommendation'), ('report', 'Incident / Report'), ('introduction', 'Letter of Introduction'), ('request', 'General Request'), ('appreciation', 'Appreciation / Thank You'), ('other', 'Other')], default='request', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('recipient_title', models.CharField(blank=True, default='', help_text='e.g. District Director of Education', max_length=200)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('sender_title', models.CharField(blank=True, default='', help_text='e.g. Classroom Teacher', max_length=200)),
                ('school_name', models.CharField(blank=True, default='', max_length=200)),
                ('district', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('date_written', models.DateField(blank=True, null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('is_sample', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ges_letters', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'GES Letter',
                'verbose_name_plural': 'GES Letters',
                'ordering': ['-updated_at'],
            },
        ),
    ]
