# Generated by Django 5.0 on 2026-04-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0010_add_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(blank=True, default='', max_length=150)),
                ('class_name', models.CharField(blank=True, default='', help_text='e.g. Basic 7, JHS 2', max_length=100)),
                ('total_questions', models.PositiveIntegerField(default=40)),
                ('options_per_question', models.PositiveIntegerField(default=4, help_text='Number of options per question (e.g. 4 for A-D)')),
                ('answer_key', models.JSONField(blank=True, default=list, help_text='List of correct answers e.g. ["A","B","C",...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_sessions', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_index', models.CharField(blank=True, default='', help_text='Student ID or index number', max_length=50)),
                ('responses', models.JSONField(blank=True, default=list, help_text='List of student answers e.g. ["A","C","B",...]')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='individual_users.markingsession')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
