# Generated by Django 5.0 on 2026-04-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0011_paper_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], default='first', max_length=10)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('school_name', models.CharField(blank=True, default='', max_length=200)),
                ('next_term_begins', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_sets', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('subjects', models.JSONField(blank=True, default=list, help_text='[{subject, class_score, exam_score, total, grade, remark}]')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade', models.CharField(blank=True, default='', max_length=5)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('conduct', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('attitude', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('interest', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('attendance', models.CharField(blank=True, default='', max_length=30)),
                ('class_teacher_comment', models.TextField(blank=True, default='')),
                ('head_teacher_comment', models.TextField(blank=True, default='')),
                ('promoted', models.BooleanField(blank=True, null=True)),
                ('next_class', models.CharField(blank=True, default='', max_length=100)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='individual_users.reportcardset')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
