# Generated by Django 5.0 on 2026-04-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0012_report_card_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenEdActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('activity_type', models.CharField(choices=[('case_study', 'Case Study'), ('debate', 'Debate / Discussion Prompt'), ('scenario', 'Citizenship Scenario'), ('map_activity', 'Map / Geography Activity'), ('timeline', 'Historical Timeline'), ('research', 'Research Project'), ('values', 'National Values Education')], default='case_study', max_length=20)),
                ('level', models.CharField(choices=[('b7', 'Basic 7'), ('b8', 'Basic 8'), ('b9', 'Basic 9'), ('b10', 'Basic 10'), ('shs1', 'SHS 1'), ('shs2', 'SHS 2'), ('shs3', 'SHS 3')], default='b7', max_length=10)),
                ('strand', models.CharField(choices=[('environment', 'Our Environment'), ('governance', 'Governance & Politics'), ('culture', 'Culture & Identity'), ('globalism', 'Globalism & International Relations'), ('citizenship', 'Responsible Citizenship'), ('economics', 'Economics & Development')], default='citizenship', max_length=20)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('scenario_text', models.TextField(blank=True, default='', help_text='The case study, scenario or discussion prompt')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured activity: {questions, key_points, tasks, resources, rubric}')),
                ('answer_guide', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_ed_activities', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'CitizenEd Activity',
                'verbose_name_plural': 'CitizenEd Activities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompuThinkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('activity_type', models.CharField(choices=[('algorithm', 'Algorithm Design'), ('pseudocode', 'Pseudocode Writing'), ('pattern', 'Pattern Recognition'), ('decomposition', 'Decomposition'), ('abstraction', 'Abstraction'), ('coding', 'Coding Challenge'), ('ai_literacy', 'AI Literacy'), ('productivity', 'Digital Productivity')], default='algorithm', max_length=20)),
                ('level', models.CharField(choices=[('b7', 'Basic 7'), ('b8', 'Basic 8'), ('b9', 'Basic 9'), ('b10', 'Basic 10'), ('shs1', 'SHS 1'), ('shs2', 'SHS 2'), ('shs3', 'SHS 3')], default='b7', max_length=10)),
                ('strand', models.CharField(blank=True, default='', help_text='e.g. Computational Thinking, AI Literacy', max_length=100)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('instructions', models.TextField(blank=True, default='')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured activity: {problem, steps, hints, expected_output, extension}')),
                ('answer_key', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computhink_activities', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'CompuThink Activity',
                'verbose_name_plural': 'CompuThink Activities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteracyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('exercise_type', models.CharField(choices=[('comprehension', 'Reading Comprehension'), ('grammar', 'Grammar Drill'), ('vocabulary', 'Vocabulary Builder'), ('phonics', 'Phonics / Remedial'), ('essay', 'Essay / Creative Writing'), ('oral', 'Oral Language Activity'), ('literature', 'Literature Study')], default='comprehension', max_length=20)),
                ('level', models.CharField(choices=[('b7', 'Basic 7'), ('b8', 'Basic 8'), ('b9', 'Basic 9'), ('b10', 'Basic 10'), ('shs1', 'SHS 1'), ('shs2', 'SHS 2'), ('shs3', 'SHS 3')], default='b7', max_length=10)),
                ('strand', models.CharField(blank=True, default='', help_text='e.g. Reading, Grammar, Writing', max_length=100)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('passage', models.TextField(blank=True, default='', help_text='Reading passage or source text')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured exercise: {questions, options, word_list, rubric, prompts}')),
                ('answer_key', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literacy_exercises', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'Literacy Exercise',
                'verbose_name_plural': 'Literacy Exercises',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TVETProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('project_type', models.CharField(choices=[('project_plan', 'Project Plan'), ('safety_quiz', 'Health & Safety Quiz'), ('tool_id', 'Tools & Materials ID'), ('innovation', 'Innovation Challenge'), ('rubric', 'Skill Assessment Rubric'), ('workshop', 'Workshop Activity')], default='project_plan', max_length=20)),
                ('level', models.CharField(choices=[('b7', 'Basic 7'), ('b8', 'Basic 8'), ('b9', 'Basic 9'), ('b10', 'Basic 10'), ('shs1', 'SHS 1'), ('shs2', 'SHS 2'), ('shs3', 'SHS 3')], default='b7', max_length=10)),
                ('strand', models.CharField(choices=[('health_safety', 'Health & Safety'), ('materials', 'Materials & Processes'), ('tools', 'Tools & Equipment'), ('innovation', 'Innovation & Entrepreneurship'), ('design', 'Design & Technology')], default='tools', max_length=20)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured project: {objectives, materials, steps, safety_notes, assessment, extension}')),
                ('answer_key', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvet_projects', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'TVET Project',
                'verbose_name_plural': 'TVET Projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
