# Generated by Django 5.0 on 2026-04-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0013_citizenedactivity_computhinkactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ai', 'AI Tools'), ('analytics', 'Analytics'), ('management', 'Management'), ('finance', 'Finance'), ('communication', 'Communication'), ('documents', 'Documents'), ('assessment', 'Assessment'), ('productivity', 'Productivity'), ('professional', 'Professional Dev'), ('subject_tools', 'Subject Tools')], max_length=20)),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('teacher', 'Teachers Only'), ('developer', 'Developers Only')], default='all', max_length=20)),
                ('icon', models.CharField(default='bi-box-seam', help_text='Bootstrap icon class', max_length=50)),
                ('badge_label', models.CharField(blank=True, default='', help_text='e.g. "NEW", "POPULAR"', max_length=30)),
                ('plans', models.JSONField(default=list, help_text='Ordered list of plan names, e.g. ["free","pro"]')),
                ('prices', models.JSONField(default=dict, help_text='Map plan→price, e.g. {"free":0,"pro":59.99}')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Free trial period in days (0 = no trial)')),
                ('features', models.JSONField(blank=True, default=list, help_text='["Feature 1","Feature 2",…]')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Individual Addon',
                'verbose_name_plural': 'Individual Addons',
                'ordering': ['position', 'category', 'name'],
            },
        ),
    ]
