# Generated by Django 5.0 on 2026-04-05 11:06

import secrets
import django.db.models.deletion
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    """Assign unique referral codes to all existing profiles."""
    IndividualProfile = apps.get_model('individual_users', 'IndividualProfile')
    for profile in IndividualProfile.objects.filter(referral_code=''):
        code = secrets.token_urlsafe(8)[:8].upper()
        # Ensure uniqueness
        while IndividualProfile.objects.filter(referral_code=code).exists():
            code = secrets.token_urlsafe(8)[:8].upper()
        profile.referral_code = code
        profile.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0015_add_credit_system'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='individualprofile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        # Step 2: Populate existing rows
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='individualprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='individual_users.individualprofile'),
        ),
        migrations.AlterField(
            model_name='individualcredittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'AI Usage'), ('bonus', 'Bonus / Welcome'), ('referral', 'Referral Bonus'), ('refund', 'Refund')], max_length=20),
        ),
    ]
