# Generated by Django 5.0 on 2026-04-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0016_referral_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('target_class', models.CharField(blank=True, default='', max_length=50)),
                ('academic_year', models.CharField(blank=True, default='', max_length=20)),
                ('students', models.JSONField(blank=True, default=list, help_text='List of student names: ["Ama Mensah", "Kofi Asare", ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_registers', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'Attendance Register',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('target_class', models.CharField(blank=True, default='', max_length=50)),
                ('term', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], default='term_1', max_length=10)),
                ('academic_year', models.CharField(blank=True, default='', max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_books', to='individual_users.individualprofile')),
            ],
            options={
                'verbose_name': 'Grade Book',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A — Excellent'), ('B', 'B — Very Good'), ('C', 'C — Good'), ('D', 'D — Satisfactory'), ('E', 'E — Below Average'), ('F', 'F — Fail')], default='', max_length=2)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='individual_users.gradebook')),
            ],
            options={
                'verbose_name': 'Grade Entry',
                'verbose_name_plural': 'Grade Entries',
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('records', models.JSONField(blank=True, default=dict, help_text='{"student_name": "present"|"absent"|"late"|"excused", ...}')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='individual_users.attendanceregister')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'ordering': ['-date'],
                'unique_together': {('register', 'date')},
            },
        ),
    ]
