# Generated by Django 5.0 on 2026-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0017_add_gradebook_gradeentry_attendanceregister_attendancesession'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='addonsubscription',
            index=models.Index(fields=['profile', 'status'], name='individual__profile_320875_idx'),
        ),
        migrations.AddIndex(
            model_name='addonsubscription',
            index=models.Index(fields=['addon_slug', 'status'], name='individual__addon_s_6ff535_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['profile', 'is_active'], name='individual__profile_d8d7c5_idx'),
        ),
    ]
