# Generated by Django 5.0 on 2026-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0019_promotion_exam_prep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addonsubscription',
            options={'ordering': ['display_order', '-started_at']},
        ),
        migrations.AddField(
            model_name='addonsubscription',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
