# Generated by Django 5.0 on 2026-04-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0020_add_display_order_to_addonsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolpresentation',
            name='transition',
            field=models.CharField(choices=[('slide', 'Slide'), ('fade', 'Fade'), ('zoom', 'Zoom'), ('flip', 'Flip'), ('swirl', 'Swirl'), ('drop', 'Drop')], default='slide', max_length=20),
        ),
    ]
