# Generated by Django 5.0 on 2026-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0021_add_swirl_drop_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolslide',
            name='transition',
            field=models.CharField(blank=True, choices=[('', 'Deck Default'), ('slide', 'Slide'), ('fade', 'Fade'), ('zoom', 'Zoom'), ('flip', 'Flip'), ('swirl', 'Swirl'), ('drop', 'Drop')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='toolslide',
            name='video_url',
            field=models.TextField(blank=True),
        ),
    ]
