# Generated by Django 5.0 on 2026-04-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0022_add_slide_transition_and_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpresentation',
            name='target_duration',
            field=models.PositiveIntegerField(default=0, help_text='Target duration in minutes (0 = no target)'),
        ),
    ]
