# Generated by Django 5.0 on 2026-04-06 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0023_add_target_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_slide', models.PositiveIntegerField(default=0)),
                ('total_slides', models.PositiveIntegerField(default=0)),
                ('pending_command', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to='individual_users.toolpresentation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
