# Generated by Django 5.0 on 2026-04-06 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0024_add_presenter_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('slide_index', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=300)),
                ('options', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='individual_users.toolpresentation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveIntegerField()),
                ('voter_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='individual_users.slidepoll')),
            ],
            options={
                'unique_together': {('poll', 'voter_id')},
            },
        ),
    ]
