# Generated by Django 5.0 on 2026-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0028_table_alttext_imagefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentersession',
            name='last_phone_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentersession',
            name='phone_connected',
            field=models.BooleanField(default=False),
        ),
    ]
