# Generated by Django 5.0 on 2026-04-06 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0029_remote_phone_connected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpresentation',
            name='custom_palette',
            field=models.JSONField(blank=True, default=list, help_text='List of hex color strings for custom palette'),
        ),
        migrations.AddField(
            model_name='toolslide',
            name='branch_actions',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, goto} dicts for branching'),
        ),
        migrations.CreateModel(
            name='SlideComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='individual_users.toolslide')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
