# Generated by Django 5.0 on 2026-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0030_batch13_comments_palette_branching'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('lesson', 'Lesson Plan'), ('lecture', 'Lecture'), ('story', 'Storytelling'), ('report', 'Report'), ('pitch', 'Pitch'), ('workshop', 'Workshop')], default='lesson', max_length=20)),
                ('emoji', models.CharField(default='📄', max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('structure_json', models.JSONField(help_text='List of {layout, title_hint, content_hint, emoji}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='toolslide',
            name='chart_data',
            field=models.JSONField(blank=True, default=dict, help_text='Chart.js config: {type, labels, datasets, title}'),
        ),
        migrations.AddField(
            model_name='toolslide',
            name='coaching_script',
            field=models.TextField(blank=True, default='', help_text='AI-generated speaking script with pacing marks'),
        ),
    ]
