# Generated by Django 5.0 on 2026-04-06 14:46

from django.db import migrations


TEMPLATES = [
    {
        'name': 'Lesson Plan (5W1H)',
        'slug': 'lesson-5w1h',
        'category': 'lesson',
        'emoji': '\U0001f4d6',
        'description': '6-slide lesson plan covering What, Why, Who, Where, When, How — ideal for structured teaching.',
        'structure_json': [
            {'layout': 'title', 'title_hint': 'Lesson Title', 'content_hint': 'Subject & Grade Level', 'emoji': '\U0001f3af'},
            {'layout': 'bullets', 'title_hint': 'Learning Objectives', 'content_hint': 'By the end of this lesson, students will be able to...', 'emoji': '\U0001f4cb'},
            {'layout': 'bullets', 'title_hint': 'Key Concepts', 'content_hint': 'Core ideas and definitions', 'emoji': '\U0001f4a1'},
            {'layout': 'two_col', 'title_hint': 'Examples vs Non-Examples', 'content_hint': 'Correct examples\\nWrong approaches', 'emoji': '\u2696\ufe0f'},
            {'layout': 'bullets', 'title_hint': 'Guided Practice', 'content_hint': 'Step-by-step activity for students', 'emoji': '\u270d\ufe0f'},
            {'layout': 'summary', 'title_hint': 'Summary & Homework', 'content_hint': 'Key takeaways and assignment', 'emoji': '\u2705'},
        ],
    },
    {
        'name': 'Science Experiment',
        'slug': 'science-experiment',
        'category': 'lesson',
        'emoji': '\U0001f52c',
        'description': '7-slide template for presenting a science experiment: hypothesis, method, results, conclusion.',
        'structure_json': [
            {'layout': 'title', 'title_hint': 'Experiment Title', 'content_hint': 'Science • Grade Level', 'emoji': '\U0001f52c'},
            {'layout': 'bullets', 'title_hint': 'Research Question & Hypothesis', 'content_hint': 'What are we investigating?\\nOur prediction...', 'emoji': '\u2753'},
            {'layout': 'bullets', 'title_hint': 'Materials Needed', 'content_hint': 'List all materials', 'emoji': '\U0001f9ea'},
            {'layout': 'bullets', 'title_hint': 'Procedure (Step by Step)', 'content_hint': 'Step 1\\nStep 2\\nStep 3', 'emoji': '\U0001f4dd'},
            {'layout': 'table', 'title_hint': 'Results & Data', 'content_hint': 'Record observations here', 'emoji': '\U0001f4ca'},
            {'layout': 'big_stat', 'title_hint': 'Key Finding', 'content_hint': 'Main result number\\nWhat it means', 'emoji': '\U0001f4a5'},
            {'layout': 'summary', 'title_hint': 'Conclusion', 'content_hint': 'What we learned\\nFuture questions', 'emoji': '\U0001f393'},
        ],
    },
    {
        'name': 'Storytelling Arc',
        'slug': 'storytelling-arc',
        'category': 'story',
        'emoji': '\U0001f4d6',
        'description': '8-slide narrative arc: hook, setting, characters, conflict, climax, resolution, theme, reflection.',
        'structure_json': [
            {'layout': 'title', 'title_hint': 'Story Title', 'content_hint': 'A story about...', 'emoji': '\U0001f4d6'},
            {'layout': 'image', 'title_hint': 'Setting & Context', 'content_hint': 'Where and when does this take place?', 'emoji': '\U0001f30d'},
            {'layout': 'two_col', 'title_hint': 'Characters', 'content_hint': 'Protagonist traits\\nAntagonist traits', 'emoji': '\U0001f465'},
            {'layout': 'bullets', 'title_hint': 'The Conflict', 'content_hint': 'What challenge arises?', 'emoji': '\u26a1'},
            {'layout': 'big_stat', 'title_hint': 'Turning Point', 'content_hint': 'The moment everything changed', 'emoji': '\U0001f525'},
            {'layout': 'bullets', 'title_hint': 'Resolution', 'content_hint': 'How was the conflict resolved?', 'emoji': '\U0001f54a\ufe0f'},
            {'layout': 'quote', 'title_hint': 'Theme & Message', 'content_hint': 'Author or character', 'emoji': '\U0001f4ac'},
            {'layout': 'summary', 'title_hint': 'Reflection Questions', 'content_hint': 'What would you do differently?\\nHow does this connect to your life?', 'emoji': '\U0001f914'},
        ],
    },
    {
        'name': 'Project Pitch',
        'slug': 'project-pitch',
        'category': 'pitch',
        'emoji': '\U0001f680',
        'description': '6-slide pitch deck: problem, solution, how it works, impact, timeline, call to action.',
        'structure_json': [
            {'layout': 'title', 'title_hint': 'Project Name', 'content_hint': 'One-line tagline', 'emoji': '\U0001f680'},
            {'layout': 'big_stat', 'title_hint': 'The Problem', 'content_hint': 'Key statistic\\nWhy this matters', 'emoji': '\U0001f6a8'},
            {'layout': 'bullets', 'title_hint': 'Our Solution', 'content_hint': 'How we solve it\\nKey features', 'emoji': '\U0001f4a1'},
            {'layout': 'two_col', 'title_hint': 'How It Works', 'content_hint': 'Step 1\\nStep 2\\nBefore\\nAfter', 'emoji': '\u2699\ufe0f'},
            {'layout': 'bullets', 'title_hint': 'Expected Impact', 'content_hint': 'Who benefits\\nMeasurable outcomes', 'emoji': '\U0001f4c8'},
            {'layout': 'title', 'title_hint': 'Get Involved', 'content_hint': 'Contact & next steps', 'emoji': '\U0001f91d'},
        ],
    },
    {
        'name': 'Book Report',
        'slug': 'book-report',
        'category': 'report',
        'emoji': '\U0001f4da',
        'description': '6-slide book report: title & author, summary, characters, themes, favourite part, recommendation.',
        'structure_json': [
            {'layout': 'title', 'title_hint': 'Book Title', 'content_hint': 'By Author Name', 'emoji': '\U0001f4da'},
            {'layout': 'bullets', 'title_hint': 'Plot Summary', 'content_hint': 'Beginning\\nMiddle\\nEnd', 'emoji': '\U0001f4d6'},
            {'layout': 'two_col', 'title_hint': 'Main Characters', 'content_hint': 'Hero traits\\nVillain traits', 'emoji': '\U0001f465'},
            {'layout': 'bullets', 'title_hint': 'Major Themes', 'content_hint': 'Theme 1\\nTheme 2\\nTheme 3', 'emoji': '\U0001f4a1'},
            {'layout': 'quote', 'title_hint': 'Favourite Quote', 'content_hint': 'Author Name', 'emoji': '\u2728'},
            {'layout': 'summary', 'title_hint': 'My Recommendation', 'content_hint': 'Who should read this\\nRating out of 5', 'emoji': '\u2b50'},
        ],
    },
    {
        'name': 'Workshop / Training',
        'slug': 'workshop-training',
        'category': 'workshop',
        'emoji': '\U0001f3d7\ufe0f',
        'description': '7-slide workshop structure: welcome, agenda, warm-up, content blocks, practice, debrief, resources.',
        'structure_json': [
            {'layout': 'title', 'title_hint': 'Workshop Title', 'content_hint': 'Facilitator Name • Date', 'emoji': '\U0001f3d7\ufe0f'},
            {'layout': 'bullets', 'title_hint': 'Session Agenda', 'content_hint': 'Topic 1\\nTopic 2\\nBreak\\nTopic 3\\nQ&A', 'emoji': '\U0001f4cb'},
            {'layout': 'big_stat', 'title_hint': 'Ice-Breaker', 'content_hint': 'Fun question or poll\\nto energize the room', 'emoji': '\U0001f3b2'},
            {'layout': 'bullets', 'title_hint': 'Core Content', 'content_hint': 'Key concept 1\\nKey concept 2\\nKey concept 3', 'emoji': '\U0001f4a1'},
            {'layout': 'two_col', 'title_hint': 'Hands-On Activity', 'content_hint': 'Instructions\\nExpected outcome', 'emoji': '\u270d\ufe0f'},
            {'layout': 'summary', 'title_hint': 'Debrief & Takeaways', 'content_hint': 'What did we learn?\\nAction items', 'emoji': '\U0001f4ad'},
            {'layout': 'title', 'title_hint': 'Resources & Thank You', 'content_hint': 'Links, references, contact info', 'emoji': '\U0001f64f'},
        ],
    },
]


def seed_templates(apps, schema_editor):
    DeckTemplate = apps.get_model('individual_users', 'DeckTemplate')
    for t in TEMPLATES:
        DeckTemplate.objects.update_or_create(
            slug=t['slug'],
            defaults={
                'name': t['name'],
                'category': t['category'],
                'emoji': t['emoji'],
                'description': t['description'],
                'structure_json': t['structure_json'],
                'is_active': True,
            },
        )


def unseed_templates(apps, schema_editor):
    DeckTemplate = apps.get_model('individual_users', 'DeckTemplate')
    DeckTemplate.objects.filter(slug__in=[t['slug'] for t in TEMPLATES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0031_batch14_charts_coaching_templates'),
    ]

    operations = [
        migrations.RunPython(seed_templates, unseed_templates),
    ]
