# Generated by Django 5.0 on 2026-04-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0032_seed_deck_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolslide',
            name='layout',
            field=models.CharField(choices=[('title', 'Title Slide'), ('bullets', 'Bullet List'), ('two_col', 'Two Column'), ('big_stat', 'Big Stat'), ('quote', 'Quote'), ('summary', 'Summary'), ('image', 'Image + Caption'), ('table', 'Table'), ('chart', 'Chart')], default='bullets', max_length=20),
        ),
    ]
