# Generated by Django 5.0 on 2026-04-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0033_batch14_chart_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolslide',
            name='bg_pattern',
            field=models.CharField(blank=True, default='', help_text='Named background pattern/gradient preset', max_length=40),
        ),
        migrations.CreateModel(
            name='SlideVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='Full slide state at this point')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='individual_users.toolslide')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_slides', to='individual_users.individualprofile')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='individual_users.toolslide')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'slide')},
            },
        ),
    ]
