# Generated by Django 5.0 on 2026-04-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0034_batch15_versions_favorites_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpresentation',
            name='share_password',
            field=models.CharField(blank=True, default='', help_text='Hashed password for shared link protection', max_length=128),
        ),
        migrations.CreateModel(
            name='AudienceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('author_name', models.CharField(blank=True, default='Anonymous', max_length=80)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_questions', to='individual_users.toolpresentation')),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('primary_color', models.CharField(blank=True, default='', max_length=30)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=30)),
                ('font_family', models.CharField(blank=True, default='', max_length=80)),
                ('lock_theme', models.BooleanField(default=False, help_text='Prevent theme changes on new decks')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='individual_users.individualprofile')),
            ],
        ),
    ]
