# Generated by Django 5.0 on 2026-04-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0035_batch16_brandkit_qa_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentersession',
            name='laser_x',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='presentersession',
            name='laser_y',
            field=models.FloatField(default=-1),
        ),
    ]
