# Generated by Django 5.0 on 2026-04-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0037_add_individualpushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('log_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('sel', 'SEL Check-in')], default='positive', max_length=10)),
                ('category', models.CharField(choices=[('participation', 'Participation'), ('respect', 'Respect'), ('homework', 'Homework'), ('punctuality', 'Punctuality'), ('disruption', 'Disruption'), ('bullying', 'Bullying'), ('achievement', 'Achievement'), ('kindness', 'Kindness'), ('anxiety', 'Anxiety'), ('withdrawal', 'Withdrawal'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualCPDEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('course', 'Course'), ('conference', 'Conference'), ('self_study', 'Self-Study'), ('mentoring', 'Mentoring'), ('other', 'Other')], default='workshop', max_length=20)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_entries', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndividualDifferentiatedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('target_class', models.CharField(blank=True, default='', max_length=100)),
                ('foundational_html', models.TextField(blank=True, default='', help_text='For struggling learners')),
                ('grade_level_html', models.TextField(blank=True, default='', help_text='For on-track learners')),
                ('extension_html', models.TextField(blank=True, default='', help_text='For advanced learners')),
                ('source_content', models.TextField(blank=True, default='', help_text='Original lesson or topic text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentiated_lessons', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualLiveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('target_class', models.CharField(blank=True, default='', max_length=100)),
                ('join_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_quizzes', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualLiveQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(blank=True, default='', max_length=300)),
                ('option_d', models.CharField(blank=True, default='', max_length=300)),
                ('correct', models.CharField(default='A', max_length=1)),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Seconds per question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='individual_users.individuallivequiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IndividualObservationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_class', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('strengths', models.TextField(blank=True, default='')),
                ('growth_areas', models.TextField(blank=True, default='')),
                ('action_plan', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_notes', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndividualRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('criteria', models.JSONField(default=list, help_text='[{"name":"…","levels":["Excellent","Good","Fair","Poor"]}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualStudyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('target_class', models.CharField(blank=True, default='', max_length=100)),
                ('content_html', models.TextField(blank=True, default='')),
                ('source_notes', models.TextField(blank=True, default='', help_text='Teacher notes used to generate guide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_guides', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualTaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('column', models.CharField(choices=[('todo', 'To Do'), ('doing', 'In Progress'), ('done', 'Done')], default='todo', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cards', to='individual_users.individualprofile')),
            ],
            options={
                'ordering': ['column', 'position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualLiveQuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='individual_users.individuallivequizquestion')),
            ],
            options={
                'unique_together': {('question', 'player_name')},
            },
        ),
    ]
