# Generated by Django 5.0 on 2026-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_users', '0038_individualbehaviorlog_individualcpdentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolquestion',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('knowledge', 'Knowledge'), ('comprehension', 'Comprehension'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis / Evaluation')], default='', help_text="Bloom's taxonomy level", max_length=15),
        ),
        migrations.AddField(
            model_name='toolquestion',
            name='indicator_code',
            field=models.CharField(blank=True, default='', help_text='NaCCA indicator e.g. B7.1.1.1.1', max_length=30),
        ),
        migrations.AddField(
            model_name='toolquestion',
            name='strand',
            field=models.CharField(blank=True, default='', help_text='GES strand e.g. Number, Algebra', max_length=200),
        ),
        migrations.AddField(
            model_name='toolquestion',
            name='sub_strand',
            field=models.CharField(blank=True, default='', help_text='GES sub-strand e.g. Number Operations', max_length=200),
        ),
    ]
