# Generated by Django 5.0 on 2026-04-07 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_conversation_message'),
        ('students', '0011_alter_student_aura_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('attendance_below', 'Attendance drops below %'), ('grade_below', 'Average grade drops below %'), ('fee_overdue', 'Fee unpaid after X days'), ('absent_streak', 'Consecutive absences reach X days')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Percentage for attendance/grade, or number of days for fee_overdue/absent_streak', max_digits=6)),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('sms', 'SMS'), ('all', 'All Channels')], default='in_app', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours between repeated alerts for the same student & rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communication.notificationrule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['rule', 'student', 'sent_at'], name='nrl_rule_student_sent_idx')],
            },
        ),
    ]
