# Generated by Django 5.0 on 2026-04-07 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_add_notificationrule_and_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'sender'], name='msg_conv_read_sender_idx'),
        ),
    ]
