# Generated by Django 5.0 on 2026-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_question_add_essay_type'),
        ('students', '0007_add_preferred_language_and_aura_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='homework',
            name='allow_retry',
            field=models.BooleanField(default=False, help_text='Allow students to retry if they scored below 50%'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('homework', 'student', 'attempt_number')},
        ),
    ]
