# Generated by Django 5.0 on 2026-04-07 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_classnote'),
        ('students', '0011_alter_student_aura_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "3-Day Warning"', max_length=200)),
                ('days_before', models.PositiveIntegerField(default=1, help_text='Number of days before due date to send the reminder')),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('sms', 'SMS'), ('all', 'All Channels')], default='in_app', max_length=10)),
                ('notify_parents', models.BooleanField(default=True, help_text='Also notify linked parents')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['days_before'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='homework.remindersetting')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['homework', 'student'], name='hwrl_hw_student_idx')],
                'unique_together': {('setting', 'homework', 'student')},
            },
        ),
    ]
