# Generated by Django 5.0 on 2026-02-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_fix_notification_table'),
    ]

    operations = [
        # Use ADD COLUMN IF NOT EXISTS so this migration is safe on DBs that
        # already received the columns from a previous (now-deleted) hand-written
        # version of this migration.
        migrations.RunSQL(
            sql="""
            ALTER TABLE announcements_notification
                ADD COLUMN IF NOT EXISTS announcement_id bigint
                    REFERENCES announcements_announcement(id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE announcements_notification
                ADD COLUMN IF NOT EXISTS link varchar(500) NOT NULL DEFAULT '';
            CREATE INDEX IF NOT EXISTS announcements_notification_announcement_id_idx
                ON announcements_notification (announcement_id);
            """,
            reverse_sql="""
            ALTER TABLE announcements_notification DROP COLUMN IF EXISTS announcement_id;
            ALTER TABLE announcements_notification DROP COLUMN IF EXISTS link;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='notification',
                    name='announcement',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='announcements.announcement'),
                ),
                migrations.AddField(
                    model_name='notification',
                    name='link',
                    field=models.CharField(blank=True, default='', max_length=500),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='alert_type',
            field=models.CharField(
                choices=[
                    ('45_min', '45 Minutes Before Class'),
                    ('10_min', '10 Minutes Before Class'),
                    ('announcement', 'Announcement'),
                    ('message', 'New Message'),
                    ('general', 'General'),
                ],
                default='general',
                max_length=20,
            ),
        ),
    ]
