# Generated by Django 5.0 on 2026-04-07 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_add_performance_indexes'),
        ('announcements', '0005_push_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'is_active', '-created_at'], name='ann_audience_active_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recip_read_idx'),
        ),
    ]
