"""
Career Technology (Creative Arts and Design / Pre-Technical Skills) BECE Question Bank
GES/NaCCA-aligned for JHS 1-3 (Basic 7-9)
Strands: Home Management, Textiles/Clothing, Woodwork, Metalwork/Electrical
"""

CAREER_TECH_QUESTION_BANK = [
    # ─── STRAND 1: HOME MANAGEMENT ───
    {
        "topic": "Kitchen Safety",
        "strand": "Home Management",
        "sub_strand": "Safety in the Kitchen",
        "ges_code": "B7.1.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following is a safety practice in the kitchen?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Leaving pot handles facing outward", "Keeping sharp knives in a drawer with a guard", "Cooking with loose-fitting clothes", "Leaving the gas on after cooking"],
        "correct_answer": "Keeping sharp knives in a drawer with a guard",
        "explanation": "Proper knife storage prevents cuts. Pot handles should face inward, loose clothes can catch fire, and gas should be turned off after cooking."
    },
    {
        "topic": "Nutrition",
        "strand": "Home Management",
        "sub_strand": "Food and Nutrition",
        "ges_code": "B7.1.2.1",
        "bloom": "Knowledge",
        "question_text": "Which class of food is the main source of energy for the body?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Proteins", "Carbohydrates", "Vitamins", "Minerals"],
        "correct_answer": "Carbohydrates",
        "explanation": "Carbohydrates are the body's main source of energy. Sources include rice, yam, cassava, bread, and plantain."
    },
    {
        "topic": "Nutrition",
        "strand": "Home Management",
        "sub_strand": "Food and Nutrition",
        "ges_code": "B7.1.2.1",
        "bloom": "Comprehension",
        "question_text": "Proteins are needed for the growth and repair of body tissues.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "True",
        "explanation": "Proteins are body-building foods essential for growth and repair. Sources include fish, meat, eggs, beans, and milk."
    },
    {
        "topic": "Nutrition",
        "strand": "Home Management",
        "sub_strand": "Food and Nutrition",
        "ges_code": "B7.1.2.2",
        "bloom": "Application",
        "question_text": "Plan a balanced breakfast meal using locally available Ghanaian foods. Include foods from each of the three main food groups.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "A balanced breakfast could include: (1) Energy-giving (carbohydrate): Hausa koko (millet porridge) or bread, (2) Body-building (protein): boiled egg or beans, (3) Protective (vitamins/minerals): sliced oranges or tomatoes. Alternative: Rice balls with groundnut soup (protein + carbohydrate) and a side of garden egg (vegetable).",
        "explanation": "A balanced meal should contain foods from the three main groups: energy-giving, body-building, and protective foods."
    },
    {
        "topic": "Food Preservation",
        "strand": "Home Management",
        "sub_strand": "Food Preservation",
        "ges_code": "B8.1.1.1",
        "bloom": "Comprehension",
        "question_text": "Which of the following is NOT a method of food preservation?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Smoking", "Refrigeration", "Frying for eating", "Salting"],
        "correct_answer": "Frying for eating",
        "explanation": "Frying food for immediate consumption is a cooking method, not preservation. Smoking, refrigeration, salting, drying, and canning are preservation methods."
    },
    {
        "topic": "Food Preservation",
        "strand": "Home Management",
        "sub_strand": "Food Preservation",
        "ges_code": "B8.1.1.1",
        "bloom": "Analysis",
        "question_text": "A farmer has harvested a large quantity of tomatoes that will spoil within a few days. Suggest TWO preservation methods and explain why each is suitable.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "(1) Drying/Sun-drying: Tomatoes can be sliced and dried in the sun. This removes moisture that bacteria need to grow, extending shelf life for months. Dried tomatoes can be ground into powder for later use. This is low-cost and suitable for rural areas. (2) Making tomato paste: Tomatoes can be blended and cooked down to make paste, then stored in sterilised jars. The heat treatment kills bacteria and the concentrated form takes less storage space. Both methods are affordable and practical for Ghanaian farmers.",
        "explanation": "Food preservation reduces post-harvest losses, which is a major challenge for Ghanaian farmers, especially with perishable crops like tomatoes."
    },
    {
        "topic": "Home Budgeting",
        "strand": "Home Management",
        "sub_strand": "Family Financial Planning",
        "ges_code": "B9.1.1.1",
        "bloom": "Application",
        "question_text": "A family earns GH₵3,000 per month. List FOUR items they should include in their monthly budget.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Food and groceries, (2) Rent or housing, (3) Children's school fees and supplies, (4) Utilities (electricity, water), (5) Transportation, (6) Healthcare, (7) Savings, (8) Communication (phone/data).",
        "explanation": "Budgeting helps families manage their income effectively and prioritise essential needs over wants."
    },
    {
        "topic": "Personal Hygiene",
        "strand": "Home Management",
        "sub_strand": "Health and Hygiene",
        "ges_code": "B7.1.3.1",
        "bloom": "Knowledge",
        "question_text": "Regular hand washing with soap helps prevent the spread of __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "diseases",
        "explanation": "Hand washing with soap removes germs and prevents the spread of diseases like diarrhoea, cholera, and respiratory infections."
    },
    # ─── STRAND 2: TEXTILES / CLOTHING ───
    {
        "topic": "Fibres",
        "strand": "Textiles and Clothing",
        "sub_strand": "Types of Fibres",
        "ges_code": "B7.2.1.1",
        "bloom": "Knowledge",
        "question_text": "Cotton is an example of a __________ fibre.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "natural",
        "explanation": "Cotton comes from the cotton plant and is a natural fibre. Other natural fibres include silk, wool, and linen. Synthetic fibres include nylon and polyester."
    },
    {
        "topic": "Fibres",
        "strand": "Textiles and Clothing",
        "sub_strand": "Types of Fibres",
        "ges_code": "B7.2.1.1",
        "bloom": "Comprehension",
        "question_text": "Which of the following is a synthetic (man-made) fibre?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Cotton", "Silk", "Nylon", "Wool"],
        "correct_answer": "Nylon",
        "explanation": "Nylon is a synthetic fibre made from chemical processes. Cotton, silk, and wool are all natural fibres."
    },
    {
        "topic": "Fabric Construction",
        "strand": "Textiles and Clothing",
        "sub_strand": "Fabric Making",
        "ges_code": "B8.2.1.1",
        "bloom": "Comprehension",
        "question_text": "State TWO differences between woven and knitted fabrics.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Woven fabrics are made by interlacing two sets of yarns (warp and weft) at right angles, while knitted fabrics are made by interlocking loops of yarn. (2) Woven fabrics are generally firm and do not stretch easily, while knitted fabrics are stretchy and flexible.",
        "explanation": "Understanding fabric construction helps in choosing the right fabric for different purposes."
    },
    {
        "topic": "Sewing",
        "strand": "Textiles and Clothing",
        "sub_strand": "Basic Sewing Skills",
        "ges_code": "B7.2.2.1",
        "bloom": "Knowledge",
        "question_text": "Which sewing tool is used for taking body measurements?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Scissors", "Tape measure", "Needle", "Thimble"],
        "correct_answer": "Tape measure",
        "explanation": "A tape measure (measuring tape) is flexible and used for taking body measurements for dressmaking."
    },
    {
        "topic": "Laundry",
        "strand": "Textiles and Clothing",
        "sub_strand": "Care of Clothing",
        "ges_code": "B8.2.2.1",
        "bloom": "Application",
        "question_text": "Explain why you should sort clothes before washing them.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Clothes should be sorted because: (1) White clothes should be washed separately to prevent colour transfer/staining, (2) Heavily soiled clothes need more vigorous washing, (3) Delicate fabrics need gentle handling, (4) Some fabrics require different water temperatures.",
        "explanation": "Sorting laundry is an important step that prevents damage and colour transfer between garments."
    },
    {
        "topic": "Tie and Dye",
        "strand": "Textiles and Clothing",
        "sub_strand": "Fabric Decoration",
        "ges_code": "B9.2.1.1",
        "bloom": "Application",
        "question_text": "Describe the steps involved in making a tie-and-dye fabric.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Steps: (1) Wash the fabric to remove starch, (2) Decide on the pattern/design (e.g., spiral, stripes, circles), (3) Fold, twist, scrunch, or tie sections of the fabric with string or rubber bands, (4) Prepare the dye solution (mix dye with water), (5) Dip or pour dye onto the tied fabric, (6) Leave the fabric in the dye for the required time, (7) Remove from dye and rinse in cold water, (8) Untie the strings/rubber bands to reveal the pattern, (9) Wash and dry the finished fabric.",
        "explanation": "Tie-and-dye (adire) is a popular fabric decoration technique in Ghana and West Africa that creates beautiful patterns using resist-dyeing."
    },
    # ─── STRAND 3: WOODWORK ───
    {
        "topic": "Types of Wood",
        "strand": "Woodwork",
        "sub_strand": "Wood Classification",
        "ges_code": "B7.3.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following is a hardwood tree found in Ghana?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Pine", "Cedar", "Mahogany", "Spruce"],
        "correct_answer": "Mahogany",
        "explanation": "Mahogany is a tropical hardwood commonly found in Ghana's forests. Pine, cedar, and spruce are softwood trees."
    },
    {
        "topic": "Woodwork Tools",
        "strand": "Woodwork",
        "sub_strand": "Tools and Equipment",
        "ges_code": "B7.3.2.1",
        "bloom": "Knowledge",
        "question_text": "A tool used for smoothing the surface of wood is called a __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "plane",
        "explanation": "A plane is a woodworking tool used for smoothing and shaping wood surfaces. Other smoothing tools include sandpaper and files."
    },
    {
        "topic": "Wood Joints",
        "strand": "Woodwork",
        "sub_strand": "Joints in Woodwork",
        "ges_code": "B8.3.1.1",
        "bloom": "Comprehension",
        "question_text": "Which type of wood joint is commonly used to make the corners of a picture frame?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Dovetail joint", "Mitre joint", "Mortise and tenon joint", "Butt joint"],
        "correct_answer": "Mitre joint",
        "explanation": "A mitre joint joins two pieces of wood at a 45° angle to form a 90° corner, making it ideal for picture frames."
    },
    {
        "topic": "Wood Joints",
        "strand": "Woodwork",
        "sub_strand": "Joints in Woodwork",
        "ges_code": "B8.3.1.1",
        "bloom": "Analysis",
        "question_text": "Compare the butt joint and the mortise and tenon joint in terms of strength and use.",
        "question_format": "short",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Butt joint: The simplest joint where two pieces are placed end-to-end or end-to-face. It is weak and relies on glue or nails for strength. Used for simple constructions like boxes. Mortise and tenon joint: A stronger joint where a projecting piece (tenon) fits into a hole (mortise). It is very strong and durable. Used for furniture legs, door frames, and heavy structures.",
        "explanation": "Understanding joint types helps in choosing the right one for the strength and purpose of the project."
    },
    {
        "topic": "Wood Finishing",
        "strand": "Woodwork",
        "sub_strand": "Surface Finishing",
        "ges_code": "B9.3.1.1",
        "bloom": "Application",
        "question_text": "State THREE reasons for applying a finish (paint or varnish) to wooden furniture.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) To protect the wood from moisture, insects, and decay, (2) To improve the appearance and beauty of the furniture, (3) To make the surface smooth and easy to clean, (4) To enhance the natural colour or grain of the wood.",
        "explanation": "Finishing is the final step in woodwork that protects and beautifies the product."
    },
    # ─── STRAND 4: METALWORK / ELECTRICAL ───
    {
        "topic": "Metals",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Types of Metals",
        "ges_code": "B7.4.1.1",
        "bloom": "Knowledge",
        "question_text": "Iron, copper, and aluminium are examples of __________ metals.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "ferrous and non-ferrous",
        "explanation": "Iron is a ferrous metal (contains iron). Copper and aluminium are non-ferrous metals (do not contain iron)."
    },
    {
        "topic": "Metals",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Properties of Metals",
        "ges_code": "B8.4.1.1",
        "bloom": "Comprehension",
        "question_text": "Which property of metals makes them suitable for making cooking pots?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Malleability", "Conductivity of heat", "Ductility", "Lustre"],
        "correct_answer": "Conductivity of heat",
        "explanation": "Metals conduct heat well, making them ideal for cooking vessels. Aluminium pots are common in Ghana because aluminium is a good heat conductor and is lightweight."
    },
    {
        "topic": "Metalwork Tools",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Tools and Equipment",
        "ges_code": "B7.4.2.1",
        "bloom": "Knowledge",
        "question_text": "A hacksaw is used specifically for cutting __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "metal",
        "explanation": "A hacksaw is a fine-toothed saw designed for cutting metal. It has a replaceable blade held in a C-shaped frame."
    },
    {
        "topic": "Electrical Safety",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Basic Electricity",
        "ges_code": "B9.4.1.1",
        "bloom": "Application",
        "question_text": "Which of the following is a safe electrical practice?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Using wet hands to plug in a device", "Overloading a power extension with many devices", "Replacing a blown fuse with the correct rating", "Using bare wires for connections"],
        "correct_answer": "Replacing a blown fuse with the correct rating",
        "explanation": "Using the correct fuse rating protects against electrical overload. Wet hands, overloaded extensions, and bare wires are all dangerous."
    },
    {
        "topic": "Simple Circuits",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Basic Electricity",
        "ges_code": "B9.4.1.2",
        "bloom": "Comprehension",
        "question_text": "In a simple electric circuit, what happens if the switch is open?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["The bulb lights up brighter", "Current flows through the circuit", "The circuit is broken and no current flows", "The battery gets charged"],
        "correct_answer": "The circuit is broken and no current flows",
        "explanation": "An open switch creates a break in the circuit, stopping the flow of current. The bulb will not light up."
    },
    {
        "topic": "Simple Circuits",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Basic Electricity",
        "ges_code": "B9.4.1.2",
        "bloom": "Analysis",
        "question_text": "Explain the difference between a series circuit and a parallel circuit. Which is better for wiring rooms in a house and why?",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Series circuit: Components are connected one after another in a single path. If one component fails, the whole circuit stops working. All components share the same current. Parallel circuit: Components are connected in separate branches. If one component fails, others continue to work. Each branch receives full voltage. Parallel circuits are better for wiring rooms because: (1) each light/appliance works independently, (2) if one light blows, others stay on, (3) each device receives the full voltage for proper operation.",
        "explanation": "Understanding series and parallel circuits is essential for basic electrical knowledge and home wiring."
    },
    {
        "topic": "Soldering",
        "strand": "Metalwork and Electrical",
        "sub_strand": "Joining Metals",
        "ges_code": "B9.4.2.1",
        "bloom": "Knowledge",
        "question_text": "Soldering is a method of joining metals using a filler material called __________.",
        "question_format": "fill",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "solder",
        "explanation": "Solder is a fusible metal alloy (usually tin-lead or tin-silver) used to join metallic surfaces, especially in electronics."
    },
]
