"""
Computing (ICT) BECE Question Bank
GES/NaCCA-aligned for JHS 1-3 (Basic 7-9)
Strands: Introduction to Computing, Presentation/Spreadsheet, Networking, Web Technologies, Programming
"""

COMPUTING_QUESTION_BANK = [
    # ─── STRAND 1: INTRODUCTION TO COMPUTING ───
    {
        "topic": "Computer Hardware",
        "strand": "Introduction to Computing",
        "sub_strand": "Components of a Computer",
        "ges_code": "B7.1.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following is an input device?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Monitor", "Printer", "Keyboard", "Speaker"],
        "correct_answer": "Keyboard",
        "explanation": "A keyboard is an input device used to enter data into the computer. Monitor, printer, and speaker are output devices."
    },
    {
        "topic": "Computer Hardware",
        "strand": "Introduction to Computing",
        "sub_strand": "Components of a Computer",
        "ges_code": "B7.1.1.1",
        "bloom": "Knowledge",
        "question_text": "The brain of the computer that processes data and instructions is called the __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "CPU",
        "explanation": "The Central Processing Unit (CPU) is often called the brain of the computer. It processes all data and instructions."
    },
    {
        "topic": "Computer Hardware",
        "strand": "Introduction to Computing",
        "sub_strand": "Components of a Computer",
        "ges_code": "B7.1.1.2",
        "bloom": "Comprehension",
        "question_text": "Explain the difference between RAM and ROM.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "RAM (Random Access Memory) is temporary memory that stores data being currently used. It is volatile — data is lost when the computer is turned off. ROM (Read Only Memory) is permanent memory that stores startup instructions. It is non-volatile — data is retained even when power is off.",
        "explanation": "RAM and ROM are both types of primary memory but serve different purposes in the computer system."
    },
    {
        "topic": "Computer Software",
        "strand": "Introduction to Computing",
        "sub_strand": "Types of Software",
        "ges_code": "B7.1.2.1",
        "bloom": "Comprehension",
        "question_text": "Which of the following is an example of system software?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Microsoft Word", "Windows 10", "Mozilla Firefox", "Adobe Photoshop"],
        "correct_answer": "Windows 10",
        "explanation": "Windows 10 is an operating system, which is a type of system software. The others are application software."
    },
    {
        "topic": "Computer Software",
        "strand": "Introduction to Computing",
        "sub_strand": "Types of Software",
        "ges_code": "B7.1.2.1",
        "bloom": "Analysis",
        "question_text": "A school needs to choose software for students to type assignments, create presentations, and browse the internet. Classify each of these as application or system software and give ONE example of each.",
        "question_format": "essay",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Typing assignments: Application software (e.g., Microsoft Word, Google Docs). Creating presentations: Application software (e.g., Microsoft PowerPoint, Google Slides). Browsing the internet: Application software (e.g., Google Chrome, Mozilla Firefox). All three are application software because they perform specific tasks for the user, unlike system software which manages the computer's hardware and resources.",
        "explanation": "Application software is designed for end users to perform specific tasks. System software (like OS) manages hardware."
    },
    {
        "topic": "Data and Information",
        "strand": "Introduction to Computing",
        "sub_strand": "Data Representation",
        "ges_code": "B8.1.1.1",
        "bloom": "Knowledge",
        "question_text": "The smallest unit of data in a computer is called a __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "bit",
        "explanation": "A bit (binary digit) is the smallest unit of data, representing either 0 or 1. Eight bits make one byte."
    },
    {
        "topic": "Storage Devices",
        "strand": "Introduction to Computing",
        "sub_strand": "Storage Media",
        "ges_code": "B8.1.2.1",
        "bloom": "Application",
        "question_text": "Kwaku wants to save a 3GB video file to carry to school. Which storage device is MOST appropriate?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Floppy disk (1.44MB)", "CD-ROM (700MB)", "USB flash drive (16GB)", "Memory card (512MB)"],
        "correct_answer": "USB flash drive (16GB)",
        "explanation": "A 16GB USB flash drive has enough capacity for a 3GB file. The floppy disk, CD-ROM, and 512MB memory card are all too small."
    },
    {
        "topic": "Operating Systems",
        "strand": "Introduction to Computing",
        "sub_strand": "System Software",
        "ges_code": "B8.1.3.1",
        "bloom": "Comprehension",
        "question_text": "State THREE functions of an operating system.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Managing hardware resources (CPU, memory, storage), (2) Providing a user interface for interaction, (3) Managing files and folders, (4) Running and managing application programs, (5) Providing security through user accounts and passwords.",
        "explanation": "The operating system is the most important system software that manages all computer resources and provides a platform for applications."
    },
    {
        "topic": "Computer Safety",
        "strand": "Introduction to Computing",
        "sub_strand": "Health and Safety",
        "ges_code": "B7.1.3.1",
        "bloom": "Application",
        "question_text": "Which of the following is a good health practice when using a computer?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Sitting close to the monitor", "Using the computer for 12 hours non-stop", "Taking regular breaks to rest the eyes", "Eating and drinking near the computer"],
        "correct_answer": "Taking regular breaks to rest the eyes",
        "explanation": "Taking regular breaks helps prevent eye strain, back pain, and repetitive strain injury. The 20-20-20 rule recommends looking at something 20 feet away for 20 seconds every 20 minutes."
    },
    {
        "topic": "Number Systems",
        "strand": "Introduction to Computing",
        "sub_strand": "Data Representation",
        "ges_code": "B9.1.1.1",
        "bloom": "Application",
        "question_text": "Convert the binary number 1101 to its decimal equivalent.",
        "question_format": "mcq",
        "difficulty": "hard",
        "options": ["11", "12", "13", "14"],
        "correct_answer": "13",
        "explanation": "1101 in binary = (1×8) + (1×4) + (0×2) + (1×1) = 8 + 4 + 0 + 1 = 13 in decimal."
    },
    # ─── STRAND 2: PRESENTATION / SPREADSHEET ───
    {
        "topic": "Word Processing",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Word Processing",
        "ges_code": "B7.2.1.1",
        "bloom": "Knowledge",
        "question_text": "In Microsoft Word, the keyboard shortcut Ctrl + B is used to __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "bold text",
        "explanation": "Ctrl + B applies bold formatting to selected text. Ctrl + I is for italics and Ctrl + U is for underline."
    },
    {
        "topic": "Word Processing",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Word Processing",
        "ges_code": "B7.2.1.2",
        "bloom": "Comprehension",
        "question_text": "Which of the following is NOT a text alignment option in a word processor?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Left align", "Centre align", "Diagonal align", "Justify"],
        "correct_answer": "Diagonal align",
        "explanation": "The four text alignment options are left, centre, right, and justify. Diagonal alignment does not exist in word processors."
    },
    {
        "topic": "Spreadsheets",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Spreadsheet Basics",
        "ges_code": "B8.2.1.1",
        "bloom": "Knowledge",
        "question_text": "In a spreadsheet, the intersection of a row and a column is called a __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "cell",
        "explanation": "A cell is the basic unit in a spreadsheet where a row and column intersect. Each cell has a unique address like A1, B2, etc."
    },
    {
        "topic": "Spreadsheets",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Formulas and Functions",
        "ges_code": "B8.2.2.1",
        "bloom": "Application",
        "question_text": "A teacher records test scores in cells B2 to B10 in a spreadsheet. Which formula will calculate the average score?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["=SUM(B2:B10)", "=AVERAGE(B2:B10)", "=COUNT(B2:B10)", "=MAX(B2:B10)"],
        "correct_answer": "=AVERAGE(B2:B10)",
        "explanation": "The AVERAGE function calculates the mean of a range. SUM adds values, COUNT counts entries, and MAX finds the highest value."
    },
    {
        "topic": "Spreadsheets",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Formulas and Functions",
        "ges_code": "B8.2.2.1",
        "bloom": "Application",
        "question_text": "If cell A1 contains 15 and cell A2 contains 5, what will be the result of the formula =A1*A2+10?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["30", "75", "85", "100"],
        "correct_answer": "85",
        "explanation": "Following the order of operations: A1*A2 = 15*5 = 75, then 75+10 = 85."
    },
    {
        "topic": "Presentations",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Presentation Software",
        "ges_code": "B9.2.1.1",
        "bloom": "Comprehension",
        "question_text": "State THREE features that make a good PowerPoint presentation.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Using clear and readable fonts (not too small), (2) Limiting text on each slide — using bullet points, (3) Using relevant images and graphics, (4) Maintaining a consistent slide design/theme, (5) Using appropriate slide transitions (not too many).",
        "explanation": "Effective presentations communicate information clearly with minimal text, good visuals, and consistent formatting."
    },
    {
        "topic": "Spreadsheets",
        "strand": "Presentation and Spreadsheet",
        "sub_strand": "Charts and Graphs",
        "ges_code": "B9.2.2.1",
        "bloom": "Analysis",
        "question_text": "A student has data showing the monthly rainfall in Accra for 12 months. Which type of chart is BEST for showing the trend over time?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Pie chart", "Bar chart", "Line graph", "Scatter plot"],
        "correct_answer": "Line graph",
        "explanation": "A line graph is best for showing trends over time. Pie charts show parts of a whole, bar charts compare categories, and scatter plots show correlations."
    },
    # ─── STRAND 3: NETWORKING ───
    {
        "topic": "Computer Networks",
        "strand": "Networking",
        "sub_strand": "Types of Networks",
        "ges_code": "B8.3.1.1",
        "bloom": "Knowledge",
        "question_text": "A network that covers a small area such as a single building or school is called a __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "LAN",
        "explanation": "LAN stands for Local Area Network. It covers a small geographical area like a room, building, or school campus."
    },
    {
        "topic": "Computer Networks",
        "strand": "Networking",
        "sub_strand": "Types of Networks",
        "ges_code": "B8.3.1.1",
        "bloom": "Comprehension",
        "question_text": "Which type of network connects computers across different cities and countries?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["LAN", "MAN", "WAN", "PAN"],
        "correct_answer": "WAN",
        "explanation": "WAN (Wide Area Network) covers a large geographical area, connecting computers across cities, countries, or continents. The internet is the largest WAN."
    },
    {
        "topic": "Internet",
        "strand": "Networking",
        "sub_strand": "Internet and Its Services",
        "ges_code": "B8.3.2.1",
        "bloom": "Knowledge",
        "question_text": "The World Wide Web (WWW) was invented by Tim Berners-Lee.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "True",
        "explanation": "Sir Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN. He created HTML, HTTP, and the first web browser."
    },
    {
        "topic": "Internet Safety",
        "strand": "Networking",
        "sub_strand": "Cyber Safety",
        "ges_code": "B9.3.1.1",
        "bloom": "Application",
        "question_text": "Which of the following is a safe online practice?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Sharing your password with friends", "Using the same password for all accounts", "Creating strong passwords with letters, numbers, and symbols", "Clicking on links from unknown senders"],
        "correct_answer": "Creating strong passwords with letters, numbers, and symbols",
        "explanation": "Strong passwords help protect your accounts. Never share passwords, use different passwords for different accounts, and avoid clicking suspicious links."
    },
    {
        "topic": "Internet Safety",
        "strand": "Networking",
        "sub_strand": "Cyber Safety",
        "ges_code": "B9.3.1.1",
        "bloom": "Analysis",
        "question_text": "Explain THREE dangers of sharing personal information on social media.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Identity theft — criminals can use your details to commit fraud, (2) Cyberbullying — personal information can be used to harass or bully you, (3) Stalking — sharing your location can put you in physical danger, (4) Scams — criminals can use your information to trick you or your contacts, (5) Permanent digital footprint — once shared, information is hard to remove.",
        "explanation": "Online safety is critical for JHS students who are increasingly using social media. Personal information should be kept private."
    },
    {
        "topic": "Email",
        "strand": "Networking",
        "sub_strand": "Internet Services",
        "ges_code": "B8.3.2.2",
        "bloom": "Application",
        "question_text": "Which part of an email address comes after the @ symbol?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["The user's name", "The domain name", "The password", "The subject line"],
        "correct_answer": "The domain name",
        "explanation": "In an email like student@gmail.com, 'student' is the username and 'gmail.com' is the domain name (after the @)."
    },
    # ─── STRAND 4: WEB TECHNOLOGIES ───
    {
        "topic": "HTML",
        "strand": "Web Technologies",
        "sub_strand": "Web Page Design",
        "ges_code": "B9.4.1.1",
        "bloom": "Knowledge",
        "question_text": "HTML stands for __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "HyperText Markup Language",
        "explanation": "HTML (HyperText Markup Language) is the standard language for creating web pages. It uses tags to structure content."
    },
    {
        "topic": "HTML",
        "strand": "Web Technologies",
        "sub_strand": "Web Page Design",
        "ges_code": "B9.4.1.1",
        "bloom": "Knowledge",
        "question_text": "Which HTML tag is used to create a heading on a web page?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["<p>", "<h1>", "<a>", "<img>"],
        "correct_answer": "<h1>",
        "explanation": "<h1> to <h6> are heading tags. <p> is for paragraphs, <a> for links, and <img> for images."
    },
    {
        "topic": "HTML",
        "strand": "Web Technologies",
        "sub_strand": "Web Page Design",
        "ges_code": "B9.4.1.2",
        "bloom": "Application",
        "question_text": "Write the HTML code to create a link to the website www.ges.gov.gh with the text 'Visit GES'.",
        "question_format": "short",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "<a href=\"https://www.ges.gov.gh\">Visit GES</a>",
        "explanation": "The <a> (anchor) tag creates hyperlinks. The href attribute specifies the URL, and the text between the tags is displayed."
    },
    {
        "topic": "Web Browsers",
        "strand": "Web Technologies",
        "sub_strand": "Internet Basics",
        "ges_code": "B8.4.1.1",
        "bloom": "Comprehension",
        "question_text": "Which of the following is NOT a web browser?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Google Chrome", "Mozilla Firefox", "Microsoft Word", "Safari"],
        "correct_answer": "Microsoft Word",
        "explanation": "Microsoft Word is a word processing application, not a web browser. Google Chrome, Firefox, and Safari are all web browsers."
    },
    {
        "topic": "Search Engines",
        "strand": "Web Technologies",
        "sub_strand": "Internet Basics",
        "ges_code": "B8.4.1.2",
        "bloom": "Comprehension",
        "question_text": "A search engine is used to browse the internet.",
        "question_format": "truefalse",
        "difficulty": "medium",
        "options": ["True", "False"],
        "correct_answer": "False",
        "explanation": "A search engine (like Google) is used to search for information on the internet. A web browser (like Chrome) is used to browse/access websites."
    },
    # ─── STRAND 5: PROGRAMMING / ALGORITHMS ───
    {
        "topic": "Algorithms",
        "strand": "Programming and Algorithms",
        "sub_strand": "Problem Solving",
        "ges_code": "B8.5.1.1",
        "bloom": "Knowledge",
        "question_text": "A step-by-step set of instructions to solve a problem is called an __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "algorithm",
        "explanation": "An algorithm is a finite sequence of well-defined instructions used to solve a problem or perform a computation."
    },
    {
        "topic": "Algorithms",
        "strand": "Programming and Algorithms",
        "sub_strand": "Problem Solving",
        "ges_code": "B8.5.1.1",
        "bloom": "Application",
        "question_text": "Arrange the following steps for making tea in the correct order:\n1. Pour hot water into the cup\n2. Boil water\n3. Put tea bag in the cup\n4. Add sugar and stir\n5. Get a cup",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "5 → 3 → 2 → 1 → 4 (Get a cup → Put tea bag in the cup → Boil water → Pour hot water into the cup → Add sugar and stir)",
        "explanation": "An algorithm requires steps to be in the correct logical order. This real-life example demonstrates algorithmic thinking."
    },
    {
        "topic": "Flowcharts",
        "strand": "Programming and Algorithms",
        "sub_strand": "Algorithm Representation",
        "ges_code": "B8.5.1.2",
        "bloom": "Knowledge",
        "question_text": "In a flowchart, the diamond shape represents a __________.",
        "question_format": "fill",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "decision",
        "explanation": "In flowcharts: oval = start/end, rectangle = process, diamond = decision, parallelogram = input/output."
    },
    {
        "topic": "Flowcharts",
        "strand": "Programming and Algorithms",
        "sub_strand": "Algorithm Representation",
        "ges_code": "B8.5.1.2",
        "bloom": "Comprehension",
        "question_text": "Which flowchart symbol is used to represent a process or action?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Oval", "Rectangle", "Diamond", "Parallelogram"],
        "correct_answer": "Rectangle",
        "explanation": "A rectangle represents a process/action in a flowchart. Ovals are for start/end, diamonds for decisions, and parallelograms for input/output."
    },
    {
        "topic": "Programming Basics",
        "strand": "Programming and Algorithms",
        "sub_strand": "Introduction to Programming",
        "ges_code": "B9.5.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following is a programming language?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Microsoft Excel", "Python", "Google Chrome", "Windows"],
        "correct_answer": "Python",
        "explanation": "Python is a popular programming language. Excel is a spreadsheet, Chrome is a browser, and Windows is an operating system."
    },
    {
        "topic": "Programming Basics",
        "strand": "Programming and Algorithms",
        "sub_strand": "Introduction to Programming",
        "ges_code": "B9.5.1.1",
        "bloom": "Comprehension",
        "question_text": "What is the output of the following Scratch/Python instruction: print(5 + 3)?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["5 + 3", "53", "8", "Error"],
        "correct_answer": "8",
        "explanation": "The print function outputs the result of the expression. 5 + 3 = 8, so the output is 8."
    },
    {
        "topic": "Programming Concepts",
        "strand": "Programming and Algorithms",
        "sub_strand": "Introduction to Programming",
        "ges_code": "B9.5.2.1",
        "bloom": "Analysis",
        "question_text": "Explain the difference between a variable and a constant in programming.",
        "question_format": "short",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "A variable is a named storage location whose value can change during program execution (e.g., score = 0, then score = score + 1). A constant is a named value that cannot be changed once set (e.g., PI = 3.14159). Variables are used for data that changes; constants are used for fixed values.",
        "explanation": "Understanding variables and constants is fundamental to programming. Variables hold changing data while constants hold fixed values."
    },
    {
        "topic": "Programming Concepts",
        "strand": "Programming and Algorithms",
        "sub_strand": "Control Structures",
        "ges_code": "B9.5.2.2",
        "bloom": "Synthesis",
        "question_text": "Write a simple algorithm (in pseudocode) that asks a user for their score and displays 'Pass' if the score is 50 or above, and 'Fail' if below 50.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "START\nINPUT score\nIF score >= 50 THEN\n    DISPLAY 'Pass'\nELSE\n    DISPLAY 'Fail'\nENDIF\nSTOP\n\nThis algorithm uses a selection (IF-ELSE) control structure to make a decision based on the user's input.",
        "explanation": "Selection control structures (IF-ELSE) allow programs to make decisions based on conditions. This is a fundamental programming concept."
    },
]
