# ─────────────────────────────────────────────────────────────────────────────
# JHS English Language BECE-Aligned Question Bank — 50 Items
# NaCCA Standards-Based Curriculum (Basic 7-9)
#
# Strands:
#   1. Oral Language (Listening & Speaking)
#   2. Reading
#   3. Grammar Usage
#   4. Writing
#   5. Literature
#
# Distribution:
#   Bloom's  → K 10, C 12, A 14, An 8, S/E 6
#   Format   → mcq 30, fill 8, short 8, truefalse 4
#   Difficulty → easy 15, medium 22, hard 13
# ─────────────────────────────────────────────────────────────────────────────

ENGLISH_QUESTION_BANK = [
    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 1: ORAL LANGUAGE (8 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Listening and Speaking',
        'strand': 'Oral Language',
        'sub_strand': 'Listening Comprehension',
        'ges_code': 'B7.1.1.1',
        'bloom': 'Comprehension',
        'question_text': 'When listening to a speech, which of the following helps you identify the main idea?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Focusing on every single word', 'B) Noting repeated key points and the conclusion', 'C) Writing down all the examples', 'D) Counting the number of paragraphs'],
        'correct_answer': 'B',
        'explanation': 'The main idea is usually reinforced through repetition of key points and summarised in the conclusion.',
    },
    {
        'topic': 'Listening and Speaking',
        'strand': 'Oral Language',
        'sub_strand': 'Listening Comprehension',
        'ges_code': 'B7.1.1.2',
        'bloom': 'Application',
        'question_text': 'Your headteacher announces a change in the school timetable. What is the most appropriate listening strategy?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Listen for dates, times, and affected subjects', 'B) Start discussing with your friend immediately', 'C) Write down only the first sentence', 'D) Wait for a friend to tell you later'],
        'correct_answer': 'A',
        'explanation': 'Active listening for specific details (dates, times, subjects) ensures you capture the key information accurately.',
    },
    {
        'topic': 'Oral Presentation',
        'strand': 'Oral Language',
        'sub_strand': 'Speaking',
        'ges_code': 'B8.1.2.1',
        'bloom': 'Application',
        'question_text': 'Which of the following is NOT a feature of a good oral presentation?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Eye contact with the audience', 'B) Speaking in a clear, audible voice', 'C) Reading every word from a script', 'D) Using appropriate gestures'],
        'correct_answer': 'C',
        'explanation': 'Good presenters use notes as prompts but maintain eye contact; reading every word makes a presentation dull.',
    },
    {
        'topic': 'Debate and Discussion',
        'strand': 'Oral Language',
        'sub_strand': 'Speaking',
        'ges_code': 'B9.1.2.2',
        'bloom': 'Analysis',
        'question_text': 'In a debate, the statement "All students should wear uniforms because it promotes equality" is an example of:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) A rhetorical question', 'B) An argument with a claim and reason', 'C) A counter-argument', 'D) An emotional appeal only'],
        'correct_answer': 'B',
        'explanation': 'The statement contains a claim ("students should wear uniforms") supported by a reason ("promotes equality").',
    },
    {
        'topic': 'Pronunciation and Stress',
        'strand': 'Oral Language',
        'sub_strand': 'Phonology',
        'ges_code': 'B7.1.3.1',
        'bloom': 'Knowledge',
        'question_text': 'The word "photograph" has the primary stress on which syllable?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) pho-TO-graph', 'B) PHO-to-graph', 'C) pho-to-GRAPH', 'D) All syllables are equally stressed'],
        'correct_answer': 'B',
        'explanation': 'In "photograph," the primary stress falls on the first syllable: PHO-to-graph.',
    },
    {
        'topic': 'Pronunciation and Stress',
        'strand': 'Oral Language',
        'sub_strand': 'Phonology',
        'ges_code': 'B8.1.3.2',
        'bloom': 'Knowledge',
        'question_text': 'How many syllables are in the word "examination"?',
        'question_format': 'short',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '5',
        'explanation': 'ex-am-i-na-tion has five syllables.',
    },
    {
        'topic': 'Listening and Speaking',
        'strand': 'Oral Language',
        'sub_strand': 'Listening Comprehension',
        'ges_code': 'B9.1.1.1',
        'bloom': 'Analysis',
        'question_text': 'A speaker says: "We must act now — tomorrow will be too late!" The tone of this statement is best described as:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Informative', 'B) Urgent and persuasive', 'C) Humorous', 'D) Narrative'],
        'correct_answer': 'B',
        'explanation': 'Words like "must act now" and "too late" convey urgency and seek to persuade the listener.',
    },
    {
        'topic': 'Oral Presentation',
        'strand': 'Oral Language',
        'sub_strand': 'Speaking',
        'ges_code': 'B8.1.2.2',
        'bloom': 'Synthesis',
        'question_text': 'You are asked to give a 2-minute speech on "The importance of trees." Write a suitable opening sentence for your speech.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Trees are essential to life on earth because they provide oxygen, shelter, and food for all living things.',
        'explanation': 'A strong opening states the topic clearly and hints at the key points to follow.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 2: READING (12 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Reading Comprehension',
        'strand': 'Reading',
        'sub_strand': 'Comprehension',
        'ges_code': 'B7.2.1.1',
        'bloom': 'Comprehension',
        'question_text': 'Read the passage: "Kofi woke up early, packed his bag, and rushed to the bus stop. He did not want to be late for the science fair." Why was Kofi in a hurry?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) He was going to the market', 'B) He did not want to be late for the science fair', 'C) He was running from rain', 'D) He forgot his homework'],
        'correct_answer': 'B',
        'explanation': 'The passage directly states he did not want to be late for the science fair.',
    },
    {
        'topic': 'Reading Comprehension',
        'strand': 'Reading',
        'sub_strand': 'Comprehension',
        'ges_code': 'B8.2.1.2',
        'bloom': 'Analysis',
        'question_text': '"The politician smiled warmly at the cameras, but his hands trembled slightly as he read the report." What can you infer about the politician?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) He was genuinely happy', 'B) He was cold', 'C) He was nervous despite appearing confident', 'D) He had a medical condition'],
        'correct_answer': 'C',
        'explanation': 'The contrast between smiling and trembling hands suggests hidden nervousness behind a confident exterior.',
    },
    {
        'topic': 'Vocabulary Development',
        'strand': 'Reading',
        'sub_strand': 'Vocabulary',
        'ges_code': 'B7.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The word "benevolent" most nearly means:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Angry', 'B) Kind and generous', 'C) Wealthy', 'D) Intelligent'],
        'correct_answer': 'B',
        'explanation': 'Benevolent means well-meaning, kind, and generous.',
    },
    {
        'topic': 'Vocabulary Development',
        'strand': 'Reading',
        'sub_strand': 'Vocabulary',
        'ges_code': 'B7.2.2.2',
        'bloom': 'Application',
        'question_text': 'Choose the word that best completes the sentence: "The _______ weather forced the farmers to stay indoors."',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) pleasant', 'B) harsh', 'C) beautiful', 'D) gentle'],
        'correct_answer': 'B',
        'explanation': '"Harsh" is the only option that logically explains why farmers would stay indoors.',
    },
    {
        'topic': 'Reading Comprehension',
        'strand': 'Reading',
        'sub_strand': 'Comprehension',
        'ges_code': 'B9.2.1.1',
        'bloom': 'Comprehension',
        'question_text': 'The phrase "reading between the lines" means:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Reading very quickly', 'B) Understanding the hidden or implied meaning', 'C) Reading out loud', 'D) Skipping some lines while reading'],
        'correct_answer': 'B',
        'explanation': '"Reading between the lines" means understanding what is implied but not directly stated.',
    },
    {
        'topic': 'Summary Writing',
        'strand': 'Reading',
        'sub_strand': 'Comprehension',
        'ges_code': 'B8.2.1.3',
        'bloom': 'Synthesis',
        'question_text': 'A good summary should contain:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) All the details from the original passage', 'B) Only the main ideas in your own words', 'C) Your personal opinion about the passage', 'D) Direct quotes from the passage'],
        'correct_answer': 'B',
        'explanation': 'Summaries capture only the main ideas, restated in the writer\'s own words.',
    },
    {
        'topic': 'Vocabulary Development',
        'strand': 'Reading',
        'sub_strand': 'Vocabulary',
        'ges_code': 'B8.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'An antonym of "generous" is:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'stingy',
        'explanation': 'Stingy (or miserly) is the opposite of generous.',
    },
    {
        'topic': 'Vocabulary Development',
        'strand': 'Reading',
        'sub_strand': 'Vocabulary',
        'ges_code': 'B9.2.2.2',
        'bloom': 'Application',
        'question_text': 'The prefix "un-" in the word "unhappy" indicates:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Very', 'B) Not', 'C) Again', 'D) Before'],
        'correct_answer': 'B',
        'explanation': 'The prefix "un-" means "not," so "unhappy" means "not happy."',
    },
    {
        'topic': 'Reading Comprehension',
        'strand': 'Reading',
        'sub_strand': 'Critical Reading',
        'ges_code': 'B9.2.1.2',
        'bloom': 'Analysis',
        'question_text': 'Which of these is a FACT rather than an OPINION?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Ghana is the best country in Africa', 'B) Accra is the capital of Ghana', 'C) Jollof rice tastes better than fried rice', 'D) Football is more exciting than basketball'],
        'correct_answer': 'B',
        'explanation': '"Accra is the capital of Ghana" is verifiable and objective; the others express personal preferences.',
    },
    {
        'topic': 'Vocabulary Development',
        'strand': 'Reading',
        'sub_strand': 'Vocabulary',
        'ges_code': 'B7.2.2.3',
        'bloom': 'Comprehension',
        'question_text': 'In the sentence "The man was so famished that he ate three plates of rice," the word "famished" means:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Tired', 'B) Angry', 'C) Extremely hungry', 'D) Excited'],
        'correct_answer': 'C',
        'explanation': 'Context clue: eating three plates of rice suggests extreme hunger. Famished means very hungry.',
    },
    {
        'topic': 'Reading Skills',
        'strand': 'Reading',
        'sub_strand': 'Comprehension',
        'ges_code': 'B8.2.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Skimming a text means:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Reading every word carefully', 'B) Reading quickly to get the general idea', 'C) Reading only the last paragraph', 'D) Reading aloud to a partner'],
        'correct_answer': 'B',
        'explanation': 'Skimming is reading quickly to get an overview or general idea of the content.',
    },
    {
        'topic': 'Reading Skills',
        'strand': 'Reading',
        'sub_strand': 'Comprehension',
        'ges_code': 'B8.2.1.4',
        'bloom': 'Application',
        'question_text': 'True or False: Scanning is used when you want to find specific information quickly in a text.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Scanning is the technique of searching for specific details like dates, names, or numbers.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 3: GRAMMAR USAGE (14 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Parts of Speech',
        'strand': 'Grammar Usage',
        'sub_strand': 'Nouns',
        'ges_code': 'B7.3.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Which of the following is an abstract noun?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Table', 'B) Happiness', 'C) Accra', 'D) Teacher'],
        'correct_answer': 'B',
        'explanation': 'Happiness cannot be touched or seen — it is an idea or feeling, making it an abstract noun.',
    },
    {
        'topic': 'Parts of Speech',
        'strand': 'Grammar Usage',
        'sub_strand': 'Verbs',
        'ges_code': 'B7.3.1.2',
        'bloom': 'Application',
        'question_text': 'Choose the correct verb form: "She _______ to school every day."',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'walks',
        'explanation': 'Third person singular ("she") in simple present tense requires the -s form: walks.',
    },
    {
        'topic': 'Tenses',
        'strand': 'Grammar Usage',
        'sub_strand': 'Tenses',
        'ges_code': 'B7.3.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The sentence "They have eaten the food" is in which tense?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Simple past', 'B) Present perfect', 'C) Past continuous', 'D) Future tense'],
        'correct_answer': 'B',
        'explanation': '"Have/has + past participle" forms the present perfect tense.',
    },
    {
        'topic': 'Tenses',
        'strand': 'Grammar Usage',
        'sub_strand': 'Tenses',
        'ges_code': 'B8.3.2.2',
        'bloom': 'Application',
        'question_text': 'Rewrite in the past continuous: "I eat rice."',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'I was eating rice.',
        'explanation': 'Past continuous = was/were + verb-ing. "I eat" becomes "I was eating."',
    },
    {
        'topic': 'Subject-Verb Agreement',
        'strand': 'Grammar Usage',
        'sub_strand': 'Concord',
        'ges_code': 'B8.3.3.1',
        'bloom': 'Application',
        'question_text': 'Choose the correct option: "Neither the teacher nor the students _______ present."',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) was', 'B) were', 'C) is', 'D) has been'],
        'correct_answer': 'B',
        'explanation': 'With "neither...nor," the verb agrees with the nearer subject ("students" — plural), so "were."',
    },
    {
        'topic': 'Sentence Types',
        'strand': 'Grammar Usage',
        'sub_strand': 'Sentence Construction',
        'ges_code': 'B7.3.4.1',
        'bloom': 'Comprehension',
        'question_text': '"Close the door!" is an example of which type of sentence?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Declarative', 'B) Interrogative', 'C) Imperative', 'D) Exclamatory'],
        'correct_answer': 'C',
        'explanation': 'Imperative sentences give commands or make requests.',
    },
    {
        'topic': 'Punctuation',
        'strand': 'Grammar Usage',
        'sub_strand': 'Punctuation',
        'ges_code': 'B7.3.5.1',
        'bloom': 'Application',
        'question_text': 'Which sentence is correctly punctuated?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ["A) Where are you going.", "B) Where are you going?", "C) Where are you going!", "D) Where, are you going"],
        'correct_answer': 'B',
        'explanation': 'Questions end with a question mark (?).',
    },
    {
        'topic': 'Active and Passive Voice',
        'strand': 'Grammar Usage',
        'sub_strand': 'Voice',
        'ges_code': 'B9.3.6.1',
        'bloom': 'Comprehension',
        'question_text': '"The ball was kicked by Ama." This sentence is in the:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Active voice', 'B) Passive voice', 'C) Imperative mood', 'D) Conditional mood'],
        'correct_answer': 'B',
        'explanation': 'In passive voice, the subject receives the action. "The ball" (subject) receives the kicking.',
    },
    {
        'topic': 'Active and Passive Voice',
        'strand': 'Grammar Usage',
        'sub_strand': 'Voice',
        'ges_code': 'B9.3.6.2',
        'bloom': 'Application',
        'question_text': 'Change to passive voice: "The cat caught the mouse."',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'The mouse was caught by the cat.',
        'explanation': 'Object becomes subject, verb becomes "was + past participle," and original subject follows "by."',
    },
    {
        'topic': 'Parts of Speech',
        'strand': 'Grammar Usage',
        'sub_strand': 'Adjectives',
        'ges_code': 'B7.3.1.3',
        'bloom': 'Comprehension',
        'question_text': 'In the sentence "The tall, dark man entered the room," the adjectives are:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'tall, dark',
        'explanation': '"Tall" and "dark" describe the noun "man" and are therefore adjectives.',
    },
    {
        'topic': 'Prepositions',
        'strand': 'Grammar Usage',
        'sub_strand': 'Prepositions',
        'ges_code': 'B8.3.7.1',
        'bloom': 'Application',
        'question_text': 'Choose the correct preposition: "She arrived _______ the airport at 6 a.m."',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) in', 'B) on', 'C) at', 'D) by'],
        'correct_answer': 'C',
        'explanation': '"At" is used with specific locations/points: at the airport, at the station.',
    },
    {
        'topic': 'Direct and Indirect Speech',
        'strand': 'Grammar Usage',
        'sub_strand': 'Reported Speech',
        'ges_code': 'B9.3.8.1',
        'bloom': 'Application',
        'question_text': 'Change to indirect speech: He said, "I am going to school."',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'He said that he was going to school.',
        'explanation': 'In indirect speech, "I am" becomes "he was" and quotation marks are removed.',
    },
    {
        'topic': 'Conditionals',
        'strand': 'Grammar Usage',
        'sub_strand': 'Conditionals',
        'ges_code': 'B9.3.9.1',
        'bloom': 'Analysis',
        'question_text': '"If I had studied harder, I would have passed the exam." This is an example of:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Zero conditional', 'B) First conditional', 'C) Second conditional', 'D) Third conditional'],
        'correct_answer': 'D',
        'explanation': 'Third conditional (if + past perfect, would have + past participle) expresses an unreal past situation.',
    },
    {
        'topic': 'Conjunctions',
        'strand': 'Grammar Usage',
        'sub_strand': 'Conjunctions',
        'ges_code': 'B8.3.10.1',
        'bloom': 'Knowledge',
        'question_text': 'True or False: "Although," "because," and "while" are all subordinating conjunctions.',
        'question_format': 'truefalse',
        'difficulty': 'medium',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'All three introduce dependent clauses and are subordinating conjunctions.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 4: WRITING (10 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Essay Writing',
        'strand': 'Writing',
        'sub_strand': 'Narrative Essay',
        'ges_code': 'B7.4.1.1',
        'bloom': 'Knowledge',
        'question_text': 'A narrative essay is best described as:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) An essay that tells a story', 'B) An essay that argues a point', 'C) An essay that describes a process', 'D) An essay that compares two things'],
        'correct_answer': 'A',
        'explanation': 'A narrative essay tells a story, usually based on personal experience, with a clear beginning, middle, and end.',
    },
    {
        'topic': 'Essay Writing',
        'strand': 'Writing',
        'sub_strand': 'Argumentative Essay',
        'ges_code': 'B9.4.1.2',
        'bloom': 'Comprehension',
        'question_text': 'In an argumentative essay, a thesis statement should:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Ask a question', 'B) State your position clearly', 'C) Tell a story', 'D) List all your points'],
        'correct_answer': 'B',
        'explanation': 'A thesis statement clearly states the writer\'s position or argument on the topic.',
    },
    {
        'topic': 'Letter Writing',
        'strand': 'Writing',
        'sub_strand': 'Formal Letter',
        'ges_code': 'B8.4.2.1',
        'bloom': 'Knowledge',
        'question_text': 'A formal letter should NOT contain:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) The sender\'s address', 'B) Slang and abbreviations', 'C) A subject line', 'D) A complimentary close'],
        'correct_answer': 'B',
        'explanation': 'Formal letters require standard English; slang and text abbreviations (e.g., "u" for "you") are inappropriate.',
    },
    {
        'topic': 'Letter Writing',
        'strand': 'Writing',
        'sub_strand': 'Formal Letter',
        'ges_code': 'B8.4.2.2',
        'bloom': 'Application',
        'question_text': 'The correct complimentary close for a formal letter addressed to "The Headmaster" is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Yours truly,', 'B) Yours faithfully,', 'C) With love,', 'D) Cheers,'],
        'correct_answer': 'B',
        'explanation': 'When the recipient is addressed by title (not by name), use "Yours faithfully."',
    },
    {
        'topic': 'Paragraph Writing',
        'strand': 'Writing',
        'sub_strand': 'Paragraph Development',
        'ges_code': 'B7.4.3.1',
        'bloom': 'Comprehension',
        'question_text': 'A topic sentence in a paragraph:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Ends the paragraph', 'B) Introduces the main idea', 'C) Provides an example only', 'D) Contains a question'],
        'correct_answer': 'B',
        'explanation': 'The topic sentence introduces the main idea that the rest of the paragraph supports and develops.',
    },
    {
        'topic': 'Essay Writing',
        'strand': 'Writing',
        'sub_strand': 'Descriptive Essay',
        'ges_code': 'B7.4.1.3',
        'bloom': 'Analysis',
        'question_text': 'Which of these sentences uses the most vivid descriptive language?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) The garden was nice.', 'B) The garden was full of colourful flowers.', 'C) The garden overflowed with crimson roses, golden sunflowers, and the sweet scent of jasmine.', 'D) The garden had many things in it.'],
        'correct_answer': 'C',
        'explanation': 'Option C uses specific colours, flower names, and sensory details (scent), making it the most vivid.',
    },
    {
        'topic': 'Composition',
        'strand': 'Writing',
        'sub_strand': 'Process Writing',
        'ges_code': 'B8.4.4.1',
        'bloom': 'Knowledge',
        'question_text': 'The correct order of the writing process is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Drafting, Planning, Editing, Publishing', 'B) Planning, Drafting, Revising, Editing', 'C) Editing, Drafting, Planning, Revising', 'D) Publishing, Editing, Drafting, Planning'],
        'correct_answer': 'B',
        'explanation': 'The writing process follows: Planning → Drafting → Revising → Editing (→ Publishing).',
    },
    {
        'topic': 'Speech Writing',
        'strand': 'Writing',
        'sub_strand': 'Speech',
        'ges_code': 'B9.4.5.1',
        'bloom': 'Synthesis',
        'question_text': 'Write a suitable closing sentence for a speech about keeping the school clean.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Let us all commit to keeping our school clean, because a clean environment is the foundation of good learning.',
        'explanation': 'A good closing sentence summarises the message and includes a call to action.',
    },
    {
        'topic': 'Letter Writing',
        'strand': 'Writing',
        'sub_strand': 'Informal Letter',
        'ges_code': 'B7.4.2.3',
        'bloom': 'Comprehension',
        'question_text': 'True or False: An informal letter to a friend can include "Dear Kofi" as the salutation.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Informal letters use the recipient\'s first name after "Dear."',
    },
    {
        'topic': 'Report Writing',
        'strand': 'Writing',
        'sub_strand': 'Report',
        'ges_code': 'B9.4.6.1',
        'bloom': 'Application',
        'question_text': 'A report on a school event should be written in:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) First person, present tense', 'B) Third person, past tense', 'C) Second person, future tense', 'D) First person, future tense'],
        'correct_answer': 'B',
        'explanation': 'Reports on past events use third person and past tense for objectivity and factual reporting.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 5: LITERATURE (6 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Figures of Speech',
        'strand': 'Literature',
        'sub_strand': 'Figures of Speech',
        'ges_code': 'B8.5.1.1',
        'bloom': 'Knowledge',
        'question_text': '"Life is a journey" is an example of:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Simile', 'B) Metaphor', 'C) Personification', 'D) Hyperbole'],
        'correct_answer': 'B',
        'explanation': 'A metaphor directly compares two unlike things without using "like" or "as."',
    },
    {
        'topic': 'Figures of Speech',
        'strand': 'Literature',
        'sub_strand': 'Figures of Speech',
        'ges_code': 'B8.5.1.2',
        'bloom': 'Comprehension',
        'question_text': '"The wind whispered through the trees." This figure of speech is called:',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'personification',
        'explanation': 'Personification gives human qualities (whispering) to non-human things (wind).',
    },
    {
        'topic': 'Literary Genres',
        'strand': 'Literature',
        'sub_strand': 'Prose',
        'ges_code': 'B7.5.2.1',
        'bloom': 'Knowledge',
        'question_text': 'A novel is an example of:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Poetry', 'B) Drama', 'C) Prose', 'D) Oral literature'],
        'correct_answer': 'C',
        'explanation': 'A novel is a long work of fiction written in prose (ordinary language, not verse).',
    },
    {
        'topic': 'Poetry',
        'strand': 'Literature',
        'sub_strand': 'Poetry',
        'ges_code': 'B9.5.3.1',
        'bloom': 'Analysis',
        'question_text': 'In the poem line "The cat sat on the mat," the rhyme scheme involves which words?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'cat, sat, mat',
        'explanation': 'Words that end with the same sound (-at) create the rhyme: cat, sat, mat.',
    },
    {
        'topic': 'Drama',
        'strand': 'Literature',
        'sub_strand': 'Drama',
        'ges_code': 'B9.5.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Stage directions in a play script are used to:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Tell the audience the moral of the story', 'B) Instruct actors on movement, tone, and setting', 'C) Summarise the entire plot', 'D) Replace dialogue'],
        'correct_answer': 'B',
        'explanation': 'Stage directions guide actors on how to move, speak, and what the setting looks like.',
    },
    {
        'topic': 'Figures of Speech',
        'strand': 'Literature',
        'sub_strand': 'Figures of Speech',
        'ges_code': 'B9.5.1.3',
        'bloom': 'Analysis',
        'question_text': '"I have told you a million times!" is an example of:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Metaphor', 'B) Simile', 'C) Hyperbole', 'D) Alliteration'],
        'correct_answer': 'C',
        'explanation': 'Hyperbole is deliberate exaggeration for emphasis. "A million times" exaggerates the real number.',
    },
]
