"""
French BECE Question Bank
GES/NaCCA-aligned for JHS 1-3 (Basic 7-9)
Strands: Oral Communication, Reading Comprehension, Grammar, Writing
"""

FRENCH_QUESTION_BANK = [
    # ─── STRAND 1: ORAL COMMUNICATION ───
    {
        "topic": "Greetings",
        "strand": "Oral Communication",
        "sub_strand": "Salutations et Présentations",
        "ges_code": "B7.1.1.1",
        "bloom": "Knowledge",
        "question_text": "How do you say 'Good morning' in French?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Bonsoir", "Bonjour", "Bonne nuit", "Salut"],
        "correct_answer": "Bonjour",
        "explanation": "'Bonjour' means 'Good morning/Good day'. 'Bonsoir' is 'Good evening', 'Bonne nuit' is 'Good night', and 'Salut' is informal 'Hi'."
    },
    {
        "topic": "Greetings",
        "strand": "Oral Communication",
        "sub_strand": "Salutations et Présentations",
        "ges_code": "B7.1.1.1",
        "bloom": "Knowledge",
        "question_text": "'Comment t'appelles-tu?' means 'How old are you?' in English.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "False",
        "explanation": "'Comment t'appelles-tu?' means 'What is your name?' 'How old are you?' is 'Quel âge as-tu?'"
    },
    {
        "topic": "Self-Introduction",
        "strand": "Oral Communication",
        "sub_strand": "Salutations et Présentations",
        "ges_code": "B7.1.1.2",
        "bloom": "Application",
        "question_text": "Complete the sentence: 'Je m'appelle Kofi. J'ai treize __________.'",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "ans",
        "explanation": "'J'ai treize ans' means 'I am thirteen years old'. 'Ans' means 'years' when talking about age."
    },
    {
        "topic": "Self-Introduction",
        "strand": "Oral Communication",
        "sub_strand": "Salutations et Présentations",
        "ges_code": "B7.1.1.2",
        "bloom": "Application",
        "question_text": "Write a short self-introduction in French including your name, age, and nationality.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Bonjour! Je m'appelle [name]. J'ai [age] ans. Je suis ghanéen(ne). J'habite à [city]. Je suis élève au collège. (Hello! My name is ___. I am ___ years old. I am Ghanaian. I live in ___. I am a student.)",
        "explanation": "Self-introduction is a basic oral communication skill. Note: ghanéen (male) / ghanéenne (female)."
    },
    {
        "topic": "Asking Directions",
        "strand": "Oral Communication",
        "sub_strand": "Les Directions",
        "ges_code": "B8.1.2.1",
        "bloom": "Comprehension",
        "question_text": "'Où est la bibliothèque?' means:",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Where is the hospital?", "Where is the library?", "Where is the school?", "Where is the market?"],
        "correct_answer": "Where is the library?",
        "explanation": "'Bibliothèque' means 'library'. 'Hôpital' = hospital, 'école' = school, 'marché' = market."
    },
    {
        "topic": "Daily Routine",
        "strand": "Oral Communication",
        "sub_strand": "La Vie Quotidienne",
        "ges_code": "B8.1.1.1",
        "bloom": "Application",
        "question_text": "Translate to English: 'Je me réveille à six heures du matin.'",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "I wake up at six o'clock in the morning.",
        "explanation": "'Se réveiller' = to wake up. 'Six heures du matin' = six o'clock in the morning. Reflexive verbs describe daily routines."
    },
    {
        "topic": "At the Market",
        "strand": "Oral Communication",
        "sub_strand": "Les Achats",
        "ges_code": "B8.1.3.1",
        "bloom": "Application",
        "question_text": "You are at a market in Lomé. How do you ask 'How much does this cost?' in French?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Qu'est-ce que c'est?", "Combien ça coûte?", "Où est le marché?", "Je voudrais acheter"],
        "correct_answer": "Combien ça coûte?",
        "explanation": "'Combien ça coûte?' means 'How much does that cost?' This is essential vocabulary for shopping."
    },
    {
        "topic": "Describing People",
        "strand": "Oral Communication",
        "sub_strand": "La Description",
        "ges_code": "B9.1.1.1",
        "bloom": "Comprehension",
        "question_text": "What does 'Il est grand et mince' mean?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["He is short and fat", "He is tall and thin", "He is small and round", "He is old and wise"],
        "correct_answer": "He is tall and thin",
        "explanation": "'Grand' means tall/big, 'mince' means thin/slim. 'Petit' = short/small, 'gros' = fat."
    },
    # ─── STRAND 2: READING COMPREHENSION ───
    {
        "topic": "Family Vocabulary",
        "strand": "Reading Comprehension",
        "sub_strand": "La Famille",
        "ges_code": "B7.2.1.1",
        "bloom": "Knowledge",
        "question_text": "The French word for 'mother' is __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "mère",
        "explanation": "'Mère' means mother. 'Père' = father, 'frère' = brother, 'sœur' = sister."
    },
    {
        "topic": "Family Vocabulary",
        "strand": "Reading Comprehension",
        "sub_strand": "La Famille",
        "ges_code": "B7.2.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following means 'brother' in French?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Père", "Frère", "Fils", "Oncle"],
        "correct_answer": "Frère",
        "explanation": "'Frère' means brother. 'Père' = father, 'fils' = son, 'oncle' = uncle."
    },
    {
        "topic": "School Vocabulary",
        "strand": "Reading Comprehension",
        "sub_strand": "L'École",
        "ges_code": "B7.2.2.1",
        "bloom": "Comprehension",
        "question_text": "Read the passage and answer: 'Ama va à l'école à sept heures. Elle aime les mathématiques et le français. Son professeur s'appelle Monsieur Mensah.' What subjects does Ama like?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["English and Science", "Mathematics and French", "History and French", "Mathematics and English"],
        "correct_answer": "Mathematics and French",
        "explanation": "'Les mathématiques et le français' means mathematics and French. 'Elle aime' means 'she likes'."
    },
    {
        "topic": "Days and Months",
        "strand": "Reading Comprehension",
        "sub_strand": "Le Calendrier",
        "ges_code": "B7.2.3.1",
        "bloom": "Knowledge",
        "question_text": "Which day of the week comes after 'mercredi' in French?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Mardi", "Vendredi", "Jeudi", "Lundi"],
        "correct_answer": "Jeudi",
        "explanation": "The days in order: lundi (Mon), mardi (Tue), mercredi (Wed), jeudi (Thu), vendredi (Fri), samedi (Sat), dimanche (Sun)."
    },
    {
        "topic": "Colours",
        "strand": "Reading Comprehension",
        "sub_strand": "Les Couleurs",
        "ges_code": "B7.2.4.1",
        "bloom": "Knowledge",
        "question_text": "'Le drapeau du Ghana est rouge, or et vert avec une étoile noire.' The colours of the Ghana flag mentioned are:",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Red (rouge), gold (or), and green (vert) with a black (noire) star.",
        "explanation": "Rouge = red, or = gold, vert = green, noir/noire = black, étoile = star, drapeau = flag."
    },
    {
        "topic": "Numbers",
        "strand": "Reading Comprehension",
        "sub_strand": "Les Nombres",
        "ges_code": "B7.2.5.1",
        "bloom": "Application",
        "question_text": "Write the number 'soixante-quinze' in digits.",
        "question_format": "fill",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "75",
        "explanation": "'Soixante' = 60, 'quinze' = 15. 'Soixante-quinze' = 60 + 15 = 75. French numbers 70-79 are based on 60 + teens."
    },
    {
        "topic": "Weather",
        "strand": "Reading Comprehension",
        "sub_strand": "Le Temps",
        "ges_code": "B8.2.1.1",
        "bloom": "Comprehension",
        "question_text": "'Il fait chaud' means:",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["It is cold", "It is hot", "It is raining", "It is windy"],
        "correct_answer": "It is hot",
        "explanation": "'Il fait chaud' = It is hot. 'Il fait froid' = cold, 'Il pleut' = it's raining, 'Il fait du vent' = it's windy."
    },
    {
        "topic": "Food Vocabulary",
        "strand": "Reading Comprehension",
        "sub_strand": "La Nourriture",
        "ges_code": "B8.2.2.1",
        "bloom": "Knowledge",
        "question_text": "'Le riz' in English is __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "rice",
        "explanation": "'Le riz' means rice. 'Le pain' = bread, 'le poulet' = chicken, 'le poisson' = fish."
    },
    # ─── STRAND 3: GRAMMAR ───
    {
        "topic": "Subject Pronouns",
        "strand": "Grammar",
        "sub_strand": "Les Pronoms Sujets",
        "ges_code": "B7.3.1.1",
        "bloom": "Knowledge",
        "question_text": "Which French subject pronoun means 'we'?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Vous", "Ils", "Nous", "Elles"],
        "correct_answer": "Nous",
        "explanation": "Je = I, Tu = you (informal), Il/Elle = he/she, Nous = we, Vous = you (formal/plural), Ils/Elles = they."
    },
    {
        "topic": "Articles",
        "strand": "Grammar",
        "sub_strand": "Les Articles",
        "ges_code": "B7.3.2.1",
        "bloom": "Comprehension",
        "question_text": "Choose the correct article: '__________ école est grande.'",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Le", "La", "L'", "Les"],
        "correct_answer": "L'",
        "explanation": "'L'' is used before a vowel. 'École' starts with a vowel sound, so we use 'L'école' instead of 'La école'."
    },
    {
        "topic": "Verb Conjugation",
        "strand": "Grammar",
        "sub_strand": "Les Verbes au Présent",
        "ges_code": "B7.3.3.1",
        "bloom": "Application",
        "question_text": "Conjugate the verb 'parler' (to speak) for 'nous': 'Nous __________'.",
        "question_format": "fill",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "parlons",
        "explanation": "For -er verbs in present tense: je parle, tu parles, il/elle parle, nous parlons, vous parlez, ils/elles parlent."
    },
    {
        "topic": "Verb Conjugation",
        "strand": "Grammar",
        "sub_strand": "Les Verbes au Présent",
        "ges_code": "B7.3.3.1",
        "bloom": "Application",
        "question_text": "Select the correct form of 'être' (to be): 'Elles __________ intelligentes.'",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["est", "es", "sont", "sommes"],
        "correct_answer": "sont",
        "explanation": "Être: je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont. 'Elles' = they (feminine), so 'sont'."
    },
    {
        "topic": "Adjective Agreement",
        "strand": "Grammar",
        "sub_strand": "Les Adjectifs",
        "ges_code": "B8.3.1.1",
        "bloom": "Analysis",
        "question_text": "In French, adjectives must agree in gender and number with the noun they describe. Make the adjective agree: 'Les filles sont __________ (intelligent).'",
        "question_format": "fill",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "intelligentes",
        "explanation": "'Les filles' = the girls (feminine plural). Add -e for feminine and -s for plural: intelligent → intelligente → intelligentes."
    },
    {
        "topic": "Negation",
        "strand": "Grammar",
        "sub_strand": "La Négation",
        "ges_code": "B8.3.2.1",
        "bloom": "Application",
        "question_text": "Make this sentence negative: 'Je parle français.'",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Je ne parle pas français.", "Je pas parle français.", "Je parle ne français pas.", "Ne je parle pas français."],
        "correct_answer": "Je ne parle pas français.",
        "explanation": "To make a sentence negative in French, place 'ne' before the verb and 'pas' after: ne + verb + pas."
    },
    {
        "topic": "Possessive Adjectives",
        "strand": "Grammar",
        "sub_strand": "Les Adjectifs Possessifs",
        "ges_code": "B8.3.3.1",
        "bloom": "Comprehension",
        "question_text": "'Mon père, ma mère et mes frères' translates to:",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["His father, his mother, his brothers", "My father, my mother, my brothers", "Your father, your mother, your brothers", "Our father, our mother, our brothers"],
        "correct_answer": "My father, my mother, my brothers",
        "explanation": "Mon (my, masc.), ma (my, fem.), mes (my, plural). They all mean 'my' but change based on the gender/number of the noun."
    },
    {
        "topic": "Past Tense",
        "strand": "Grammar",
        "sub_strand": "Le Passé Composé",
        "ges_code": "B9.3.1.1",
        "bloom": "Application",
        "question_text": "Complete with the correct passé composé form: 'J'__________ (manger) du riz hier.'",
        "question_format": "fill",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "ai mangé",
        "explanation": "Passé composé = avoir/être + past participle. Manger → mangé. 'J'ai mangé' = I ate/I have eaten."
    },
    {
        "topic": "Prepositions",
        "strand": "Grammar",
        "sub_strand": "Les Prépositions",
        "ges_code": "B9.3.2.1",
        "bloom": "Comprehension",
        "question_text": "Which preposition completes the sentence correctly? 'Le livre est __________ la table.'",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["dans", "sur", "sous", "devant"],
        "correct_answer": "sur",
        "explanation": "'Sur' means 'on'. The book is on the table. 'Dans' = in, 'sous' = under, 'devant' = in front of."
    },
    # ─── STRAND 4: WRITING ───
    {
        "topic": "Letter Writing",
        "strand": "Writing",
        "sub_strand": "La Correspondance",
        "ges_code": "B8.4.1.1",
        "bloom": "Knowledge",
        "question_text": "A formal letter in French typically begins with the greeting:",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Salut!", "Cher ami", "Monsieur/Madame", "Bonjour mon ami"],
        "correct_answer": "Monsieur/Madame",
        "explanation": "Formal French letters begin with 'Monsieur' or 'Madame'. 'Cher/Chère' is used for informal letters to friends and family."
    },
    {
        "topic": "Letter Writing",
        "strand": "Writing",
        "sub_strand": "La Correspondance",
        "ges_code": "B8.4.1.1",
        "bloom": "Synthesis",
        "question_text": "Write a short informal letter in French to your friend telling them about your school. Include at least 5 sentences.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Accra, le 15 mars 2025\n\nCher Kweku,\n\nComment vas-tu? Je vais bien. Je t'écris pour te parler de mon école. Mon école s'appelle Presbyterian Junior High School. Elle est grande et belle. Il y a beaucoup d'élèves dans mon école. Mon professeur de français est très gentil. J'aime beaucoup le français et les mathématiques. Écris-moi bientôt!\n\nTon ami(e),\n[Name]",
        "explanation": "Informal letters use 'Cher/Chère' + first name. Include the date, greeting, body, and closing (Ton ami/amie)."
    },
    {
        "topic": "Describing Places",
        "strand": "Writing",
        "sub_strand": "La Description",
        "ges_code": "B9.4.1.1",
        "bloom": "Application",
        "question_text": "Translate to French: 'My house is big. It has four rooms.'",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Ma maison est grande. Elle a quatre chambres.",
        "explanation": "'Ma maison' = my house (feminine). 'Grande' = big (feminine form). 'Chambres' = rooms."
    },
    {
        "topic": "Daily Activities",
        "strand": "Writing",
        "sub_strand": "La Vie Quotidienne",
        "ges_code": "B8.4.2.1",
        "bloom": "Application",
        "question_text": "Complete the dialogue:\nA: 'Qu'est-ce que tu fais le matin?'\nB: 'Le matin, je __________ à six heures.'",
        "question_format": "fill",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "me réveille",
        "explanation": "'Qu'est-ce que tu fais?' = What do you do? 'Se réveiller' = to wake up. 'Je me réveille' = I wake up."
    },
    {
        "topic": "Paragraph Writing",
        "strand": "Writing",
        "sub_strand": "La Rédaction",
        "ges_code": "B9.4.2.1",
        "bloom": "Synthesis",
        "question_text": "Write a paragraph of at least 5 sentences in French about your favourite hobby (passe-temps préféré).",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Mon passe-temps préféré est le football. Je joue au football avec mes amis après l'école. Nous jouons au terrain de sport. J'aime le football parce que c'est amusant et bon pour la santé. Mon joueur préféré est Thomas Partey parce qu'il est ghanéen et très talentueux. Le week-end, je regarde les matchs de football à la télévision avec ma famille.",
        "explanation": "Writing about hobbies in French practises vocabulary (sports, leisure) and verb conjugation (jouer, aimer, regarder)."
    },
    {
        "topic": "Filling Forms",
        "strand": "Writing",
        "sub_strand": "Les Formulaires",
        "ges_code": "B7.4.1.1",
        "bloom": "Application",
        "question_text": "On a French form, 'Nom' asks for your:",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["First name", "Surname/Last name", "Nickname", "Date of birth"],
        "correct_answer": "Surname/Last name",
        "explanation": "'Nom' = surname/last name. 'Prénom' = first name. 'Date de naissance' = date of birth. 'Adresse' = address."
    },
    {
        "topic": "Sentence Construction",
        "strand": "Writing",
        "sub_strand": "La Construction de Phrases",
        "ges_code": "B9.4.3.1",
        "bloom": "Analysis",
        "question_text": "Rearrange the words to form a correct French sentence: 'français / le / aime / J' / beaucoup'",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "J'aime beaucoup le français.",
        "explanation": "French sentence structure: Subject + Verb + Adverb + Article + Noun. 'J'aime beaucoup le français' = I like French a lot."
    },
]
