# ─────────────────────────────────────────────────────────────────────────────
# JHS Mathematics BECE-Aligned Question Bank — 200 Items
# NaCCA Standards-Based Curriculum (Basic 7-9)
# Code format: B{level}.{strand}.{sub_strand}.{content_std}.{indicator}
#
# Distribution:
#   Strand   → Number 70, Algebra 40, Geometry 50, Data 40
#   Bloom's  → K 40, C 50, A 60, An 30, S/E 20
#   Format   → mcq ~120, fill ~30, short ~30, truefalse ~20
#   Difficulty → easy ~60, medium ~90, hard ~50
# ─────────────────────────────────────────────────────────────────────────────

MATH_QUESTION_BANK = [
    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 1: NUMBER (70 items)
    # ═══════════════════════════════════════════════════════════════════════════

    # ── Number and Numeration Systems ──────────────────────────
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'What is the place value of 5 in the number 3,562?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 5', 'B) 50', 'C) 500', 'D) 5000'],
        'correct_answer': 'C',
        'explanation': 'In 3,562 the digit 5 is in the hundreds place, so its place value is 500.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.1.2',
        'bloom': 'Comprehension',
        'question_text': 'Write 4,307 in expanded form.',
        'question_format': 'short',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '4000 + 300 + 7',
        'explanation': '4,307 = 4×1000 + 3×100 + 0×10 + 7×1 = 4000 + 300 + 7.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.2.1',
        'bloom': 'Knowledge',
        'question_text': 'Which of the following is a prime number?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 15', 'B) 21', 'C) 23', 'D) 27'],
        'correct_answer': 'C',
        'explanation': '23 has exactly two factors: 1 and 23. The others are divisible by 3.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B8.1.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'The number 48 can be expressed as a product of prime factors as:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 2⁴ × 3', 'B) 2³ × 6', 'C) 4 × 12', 'D) 2² × 12'],
        'correct_answer': 'A',
        'explanation': '48 = 2 × 24 = 2 × 2 × 12 = 2 × 2 × 2 × 6 = 2 × 2 × 2 × 2 × 3 = 2⁴ × 3.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B8.1.1.2.1',
        'bloom': 'Application',
        'question_text': 'Find the LCM of 12 and 18.',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '36',
        'explanation': '12 = 2² × 3, 18 = 2 × 3². LCM = 2² × 3² = 36.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B9.1.1.1.1',
        'bloom': 'Analysis',
        'question_text': 'Two bells ring at intervals of 15 and 20 minutes. If they ring together at 8:00 AM, at what time will they next ring together?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '9:00 AM',
        'explanation': 'LCM(15, 20) = 60 minutes. They ring together again after 60 min → 9:00 AM.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.3.1',
        'bloom': 'Knowledge',
        'question_text': 'An integer is a whole number that can be positive, negative, or zero.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Integers include …, −3, −2, −1, 0, 1, 2, 3, … They can be positive, negative, or zero.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B8.1.1.3.1',
        'bloom': 'Comprehension',
        'question_text': 'Arrange the following integers in ascending order: −5, 3, −1, 0, 7.',
        'question_format': 'short',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '-5, -1, 0, 3, 7',
        'explanation': 'On the number line, values increase from left to right: −5 < −1 < 0 < 3 < 7.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B9.1.1.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Express 0.375 as a fraction in its simplest form.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '3/8',
        'explanation': '0.375 = 375/1000. GCD(375,1000)=125. 375÷125=3, 1000÷125=8 → 3/8.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B9.1.1.3.1',
        'bloom': 'Analysis',
        'question_text': 'Which statement is FALSE about rational numbers?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': [
            'A) Every integer is a rational number',
            'B) Every rational number can be expressed as a/b where b ≠ 0',
            'C) √2 is a rational number',
            'D) 0.333… (recurring) is a rational number',
        ],
        'correct_answer': 'C',
        'explanation': '√2 is irrational — it cannot be expressed as a fraction of two integers.',
    },

    # ── Number Operations ──────────────────────────────────────
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.1.1',
        'bloom': 'Application',
        'question_text': 'Evaluate: (−8) + (+5) − (−3).',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '0',
        'explanation': '(−8) + 5 = −3; −3 − (−3) = −3 + 3 = 0.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.1.2',
        'bloom': 'Application',
        'question_text': 'A trader bought 45 oranges at GH₵0.50 each and sold them at GH₵0.80 each. What is her profit?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵13.50', 'B) GH₵22.50', 'C) GH₵36.00', 'D) GH₵9.00'],
        'correct_answer': 'A',
        'explanation': 'Cost = 45 × 0.50 = 22.50. Revenue = 45 × 0.80 = 36.00. Profit = 36.00 − 22.50 = GH₵13.50.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'Use BODMAS: the correct order of operations is Brackets, Orders, Division/Multiplication, Addition/Subtraction.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'BODMAS defines the hierarchy of operations used in Ghana\'s mathematics curriculum.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.1.1',
        'bloom': 'Application',
        'question_text': 'Evaluate: 3 + 4 × 2 − (6 ÷ 3).',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 9', 'B) 12', 'C) 7', 'D) 5'],
        'correct_answer': 'A',
        'explanation': 'Brackets: 6÷3=2. Multiply: 4×2=8. Then: 3+8−2=9.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.2.1',
        'bloom': 'Comprehension',
        'question_text': 'What does "commutative property" mean in addition?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': [
            'A) Changing the order of addends does not change the sum',
            'B) Grouping numbers differently changes the result',
            'C) Adding zero changes the number',
            'D) The order of subtraction does not matter',
        ],
        'correct_answer': 'A',
        'explanation': 'Commutative property of addition: a + b = b + a.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.1.1',
        'bloom': 'Application',
        'question_text': 'Simplify: (−4)² + 3(−2).',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '10',
        'explanation': '(−4)² = 16. 3×(−2) = −6. 16 + (−6) = 10.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.2.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A student claims that (−2)³ = 8. Explain with working whether the student is correct.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'The student is incorrect. (−2)³ = (−2)×(−2)×(−2) = 4×(−2) = −8, not 8.',
        'explanation': 'A negative number raised to an odd power gives a negative result. (−2)³ = −8.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.3.1',
        'bloom': 'Application',
        'question_text': 'Kofi has GH₵120. He spends ¼ on books and ⅓ on food. How much does he have left?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵50', 'B) GH₵70', 'C) GH₵80', 'D) GH₵40'],
        'correct_answer': 'A',
        'explanation': 'Books: 120×¼=30. Food: 120×⅓=40. Spent=70. Left=120−70=GH₵50.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.3.1',
        'bloom': 'Analysis',
        'question_text': 'Without calculating, explain why (−1)²⁰ must be positive.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'An even exponent means pairs of negative factors multiply to positive. (−1)²⁰ = [(−1)²]¹⁰ = 1¹⁰ = 1.',
        'explanation': 'Any negative number raised to an even power is positive because negatives cancel in pairs.',
    },

    # ── Fractions, Decimals and Percentages ────────────────────
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.1.1',
        'bloom': 'Knowledge',
        'question_text': 'What is ¾ as a decimal?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '0.75',
        'explanation': '¾ = 3 ÷ 4 = 0.75.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.1.2',
        'bloom': 'Comprehension',
        'question_text': 'Convert 0.6 to a percentage.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 6%', 'B) 0.6%', 'C) 60%', 'D) 600%'],
        'correct_answer': 'C',
        'explanation': '0.6 × 100 = 60%.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.2.1',
        'bloom': 'Application',
        'question_text': 'Simplify: 2/5 + 1/3.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '11/15',
        'explanation': 'LCD = 15. 2/5 = 6/15, 1/3 = 5/15. 6/15 + 5/15 = 11/15.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B8.1.3.1.1',
        'bloom': 'Application',
        'question_text': 'Find 15% of GH₵240.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵36', 'B) GH₵24', 'C) GH₵48', 'D) GH₵30'],
        'correct_answer': 'A',
        'explanation': '15/100 × 240 = 36.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B8.1.3.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Arrange from smallest to largest: ⅔, 0.6, 70%.',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '0.6, ⅔, 70%',
        'explanation': '0.6 = 60%. ⅔ ≈ 66.7%. 70% = 70%. Order: 60% < 66.7% < 70%.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B9.1.3.1.1',
        'bloom': 'Application',
        'question_text': 'A dress costs GH₵200. After a 20% discount, what is the sale price?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵160', 'B) GH₵180', 'C) GH₵240', 'D) GH₵150'],
        'correct_answer': 'A',
        'explanation': 'Discount = 20% of 200 = 40. Sale price = 200 − 40 = GH₵160.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B9.1.3.2.1',
        'bloom': 'Analysis',
        'question_text': 'A school\'s population increased from 400 to 480. What is the percentage increase?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 20%', 'B) 80%', 'C) 16.7%', 'D) 25%'],
        'correct_answer': 'A',
        'explanation': 'Increase = 80. % increase = (80/400) × 100 = 20%.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B9.1.3.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A shopkeeper increases prices by 25%, then offers a 25% discount. Is the final price the same as the original? Explain.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'No. If original = 100, after 25% increase = 125. 25% discount on 125 = 31.25. Final = 93.75 ≠ 100.',
        'explanation': 'Percentage increase and equal percentage decrease do not cancel because they are computed on different base values.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.3.1',
        'bloom': 'Comprehension',
        'question_text': '⅜ is equivalent to which percentage?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 38%', 'B) 37.5%', 'C) 3.75%', 'D) 33.3%'],
        'correct_answer': 'B',
        'explanation': '3 ÷ 8 = 0.375 = 37.5%.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B8.1.3.3.1',
        'bloom': 'Application',
        'question_text': 'Ama scored 42 out of 60 in a test. What is her percentage score?',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '70%',
        'explanation': '(42/60) × 100 = 70%.',
    },

    # ── Ratio and Proportion ───────────────────────────────────
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B7.1.4.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Express the ratio 15:25 in its simplest form.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '3:5',
        'explanation': 'GCD(15,25) = 5. 15÷5 : 25÷5 = 3:5.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B7.1.4.1.2',
        'bloom': 'Application',
        'question_text': 'Divide GH₵180 in the ratio 2:3:4.',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'GH₵40, GH₵60, GH₵80',
        'explanation': 'Total parts = 9. Each part = 180÷9 = 20. Shares: 2×20=40, 3×20=60, 4×20=80.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B8.1.4.1.1',
        'bloom': 'Application',
        'question_text': 'If 5 books cost GH₵75, how much do 8 books cost?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵120', 'B) GH₵100', 'C) GH₵96', 'D) GH₵150'],
        'correct_answer': 'A',
        'explanation': 'Unit cost = 75÷5 = 15. Cost of 8 = 8×15 = GH₵120.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B8.1.4.2.1',
        'bloom': 'Comprehension',
        'question_text': 'In direct proportion, as one quantity increases the other:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Decreases', 'B) Stays the same', 'C) Increases', 'D) Becomes zero'],
        'correct_answer': 'C',
        'explanation': 'Direct proportion means both quantities change in the same direction.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B9.1.4.1.1',
        'bloom': 'Application',
        'question_text': 'A map has a scale of 1:50,000. Two towns are 6 cm apart on the map. What is the actual distance in km?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) 3 km', 'B) 30 km', 'C) 300 km', 'D) 0.3 km'],
        'correct_answer': 'A',
        'explanation': '6 cm × 50,000 = 300,000 cm = 3,000 m = 3 km.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B9.1.4.2.1',
        'bloom': 'Analysis',
        'question_text': 'If 6 workers can build a wall in 10 days, how many days will 15 workers take? (Assume inverse proportion.)',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '4 days',
        'explanation': 'Inverse proportion: 6 × 10 = 15 × d → d = 60/15 = 4 days.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B9.1.4.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A recipe serves 4 people using 600 g flour. Explain how to adjust it for 10 people and find the flour needed.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Scale factor = 10/4 = 2.5. Flour = 600 × 2.5 = 1,500 g.',
        'explanation': 'Direct proportion: multiply all quantities by the ratio of new servings to original.',
    },

    # ── Additional Number items to reach 70 ────────────────────
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.4.1',
        'bloom': 'Knowledge',
        'question_text': 'What is the product of (−3) and (+7)?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '-21',
        'explanation': 'A negative times a positive gives a negative: −3 × 7 = −21.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Round 3,476 to the nearest hundred.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 3,400', 'B) 3,500', 'C) 3,470', 'D) 3,480'],
        'correct_answer': 'B',
        'explanation': 'The tens digit is 7 (≥5), so round up: 3,476 → 3,500.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.4.1',
        'bloom': 'Application',
        'question_text': 'A farmer harvested 1,250 kg of maize. He sold ⅗ of it. How many kg did he sell?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 750 kg', 'B) 500 kg', 'C) 625 kg', 'D) 250 kg'],
        'correct_answer': 'A',
        'explanation': '⅗ × 1250 = 750 kg.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.4.1',
        'bloom': 'Application',
        'question_text': 'Multiply: ⅔ × ⁹⁄₁₀.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '3/5',
        'explanation': '(2×9)/(3×10) = 18/30 = 3/5.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.3.1',
        'bloom': 'Analysis',
        'question_text': 'Kwame says "subtracting a negative number is the same as adding." Is he correct? Justify with an example.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Yes. e.g. 5 − (−3) = 5 + 3 = 8. Subtracting a negative is equivalent to adding the positive.',
        'explanation': 'By definition, a − (−b) = a + b.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B9.1.1.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Express 0.000045 in standard form.',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) 4.5 × 10⁻⁵', 'B) 45 × 10⁻⁶', 'C) 4.5 × 10⁻⁶', 'D) 4.5 × 10⁵'],
        'correct_answer': 'A',
        'explanation': '0.000045 = 4.5 × 10⁻⁵ (move decimal 5 places right).',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B8.1.4.3.1',
        'bloom': 'Comprehension',
        'question_text': 'If a car travels 240 km on 30 litres of fuel, how far can it travel on 1 litre?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '8 km',
        'explanation': '240 ÷ 30 = 8 km per litre.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.5.1',
        'bloom': 'Knowledge',
        'question_text': 'What is the square of 9?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '81',
        'explanation': '9² = 9 × 9 = 81.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.5.1',
        'bloom': 'Application',
        'question_text': 'Find √144.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 11', 'B) 12', 'C) 13', 'D) 14'],
        'correct_answer': 'B',
        'explanation': '12 × 12 = 144, so √144 = 12.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B9.1.3.4.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A worker\'s salary increased by 10% in 2024 and then by another 10% in 2025. If the original salary was GH₵2,000, show that the total increase is NOT 20% of the original.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'After 2024: 2000×1.1=2200. After 2025: 2200×1.1=2420. Total increase=420, which is 21% of 2000, not 20%.',
        'explanation': 'Compound percentage increases yield more than the simple sum because the second increase is on a larger base.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.4.1',
        'bloom': 'Comprehension',
        'question_text': 'What is the cube root of 27?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 3', 'B) 9', 'C) 6', 'D) 27'],
        'correct_answer': 'A',
        'explanation': '3³ = 3 × 3 × 3 = 27, so ∛27 = 3.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B8.1.1.4.1',
        'bloom': 'Application',
        'question_text': 'Convert the binary number 1101₂ to base 10.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '13',
        'explanation': '1×2³ + 1×2² + 0×2¹ + 1×2⁰ = 8 + 4 + 0 + 1 = 13.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.6.1',
        'bloom': 'Application',
        'question_text': 'A bus carries 48 passengers per trip. How many passengers can it carry in 7 trips?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 336', 'B) 384', 'C) 296', 'D) 348'],
        'correct_answer': 'A',
        'explanation': '48 × 7 = 336.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B8.1.3.4.1',
        'bloom': 'Analysis',
        'question_text': 'If a shirt costs GH₵80 and VAT is 12.5%, what is the total price?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵90', 'B) GH₵92.50', 'C) GH₵92', 'D) GH₵85'],
        'correct_answer': 'A',
        'explanation': 'VAT = 12.5% of 80 = 10. Total = 80 + 10 = GH₵90.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B7.1.4.2.1',
        'bloom': 'Comprehension',
        'question_text': 'In a class, the ratio of boys to girls is 3:5. If there are 24 boys, how many girls are there?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 40', 'B) 30', 'C) 48', 'D) 15'],
        'correct_answer': 'A',
        'explanation': '3 parts = 24 → 1 part = 8. Girls = 5 × 8 = 40.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.6.1',
        'bloom': 'Analysis',
        'question_text': 'Explain why division by zero is undefined.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'If a ÷ 0 = b, then b × 0 = a. But b × 0 = 0 for all b, which contradicts a ≠ 0. Hence undefined.',
        'explanation': 'No number multiplied by 0 gives a non-zero result, making division by zero impossible.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.5.1',
        'bloom': 'Knowledge',
        'question_text': 'A factor of a number divides it exactly with no remainder.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'By definition, a factor of n divides n with remainder 0.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.5.1',
        'bloom': 'Application',
        'question_text': 'Divide: ⁴⁄₅ ÷ ²⁄₃.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '6/5 or 1⅕',
        'explanation': '⁴⁄₅ ÷ ²⁄₃ = ⁴⁄₅ × ³⁄₂ = 12/10 = 6/5.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.5.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'Design a word problem that requires finding both the HCF and LCM of two numbers. State the problem and solve it.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'E.g.: Two ropes are 24 m and 36 m. Cut into equal pieces as long as possible (HCF=12 m). How often do length multiples coincide? (LCM=72 m).',
        'explanation': 'Open-ended; marks for clear problem statement, correct HCF/LCM computation, and logical narrative.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B9.1.4.4.1',
        'bloom': 'Application',
        'question_text': 'The cost of 12 pencils is GH₵18. What is the cost of 20 pencils?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) GH₵25', 'B) GH₵30', 'C) GH₵28', 'D) GH₵36'],
        'correct_answer': 'B',
        'explanation': 'Unit cost = 18/12 = 1.50. 20 × 1.50 = GH₵30.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 2: ALGEBRA (40 items)
    # ═══════════════════════════════════════════════════════════════════════════

    # ── Patterns and Relations ─────────────────────────────────
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B7.2.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'What is the next number in the sequence: 2, 5, 8, 11, …?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '14',
        'explanation': 'Common difference = 3. 11 + 3 = 14.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B7.2.1.1.2',
        'bloom': 'Comprehension',
        'question_text': 'The first four terms of a pattern are 1, 4, 9, 16. The rule is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Add 3', 'B) Multiply by 2', 'C) Square the position number', 'D) Add consecutive odd numbers'],
        'correct_answer': 'C',
        'explanation': '1², 2², 3², 4² = 1, 4, 9, 16.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B8.2.1.1.1',
        'bloom': 'Application',
        'question_text': 'Find the 10th term of the arithmetic sequence: 3, 7, 11, 15, …',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 39', 'B) 43', 'C) 37', 'D) 41'],
        'correct_answer': 'A',
        'explanation': 'a = 3, d = 4. T₁₀ = 3 + (10−1)×4 = 3 + 36 = 39.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B9.2.1.1.1',
        'bloom': 'Analysis',
        'question_text': 'A sequence is defined by Tₙ = 2n + 5. Is the term 50 in this sequence? Explain.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'If 2n + 5 = 50, then n = 22.5, which is not a natural number. So 50 is NOT in the sequence.',
        'explanation': 'A term is in the sequence only if n is a positive integer.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B8.2.1.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Describe the pattern: 1, 1, 2, 3, 5, 8, 13, …',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'Fibonacci sequence — each term is the sum of the two preceding terms.',
        'explanation': '1+1=2, 1+2=3, 2+3=5, 3+5=8, 5+8=13.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B7.2.1.2.1',
        'bloom': 'Knowledge',
        'question_text': 'In a number pattern with constant difference, the pattern is called:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Geometric sequence', 'B) Arithmetic sequence', 'C) Fibonacci sequence', 'D) Harmonic sequence'],
        'correct_answer': 'B',
        'explanation': 'An arithmetic sequence has a constant common difference between successive terms.',
    },

    # ── Algebraic Expressions ──────────────────────────────────
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B7.2.2.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Simplify: 3x + 5x.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '8x',
        'explanation': 'Like terms: 3x + 5x = 8x.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B7.2.2.1.2',
        'bloom': 'Application',
        'question_text': 'If a = 3 and b = −2, find the value of 2a − 3b.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 0', 'B) 12', 'C) 6', 'D) −12'],
        'correct_answer': 'B',
        'explanation': '2(3) − 3(−2) = 6 + 6 = 12.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B8.2.2.1.1',
        'bloom': 'Application',
        'question_text': 'Expand: 3(2x − 5).',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '6x - 15',
        'explanation': '3 × 2x = 6x, 3 × (−5) = −15.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B8.2.2.2.1',
        'bloom': 'Application',
        'question_text': 'Factorise: 12x + 18.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 6(2x + 3)', 'B) 3(4x + 6)', 'C) 2(6x + 9)', 'D) 12(x + 1.5)'],
        'correct_answer': 'A',
        'explanation': 'GCF = 6. 12x ÷ 6 = 2x, 18 ÷ 6 = 3. → 6(2x + 3).',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B9.2.2.1.1',
        'bloom': 'Application',
        'question_text': 'Expand and simplify: (x + 3)(x − 2).',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'x² + x − 6',
        'explanation': 'x² − 2x + 3x − 6 = x² + x − 6.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B9.2.2.2.1',
        'bloom': 'Analysis',
        'question_text': 'Factorise completely: x² − 9.',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) (x−3)(x+3)', 'B) (x−9)(x+1)', 'C) (x−3)²', 'D) x(x−9)'],
        'correct_answer': 'A',
        'explanation': 'Difference of two squares: x² − 9 = (x)² − (3)² = (x−3)(x+3).',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B7.2.2.2.1',
        'bloom': 'Comprehension',
        'question_text': 'In the expression 4x² + 3x − 7, the coefficient of x is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 4', 'B) 3', 'C) −7', 'D) x'],
        'correct_answer': 'B',
        'explanation': 'The coefficient is the number multiplying x, which is 3.',
    },

    # ── Equations and Inequalities ─────────────────────────────
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B7.2.3.1.1',
        'bloom': 'Application',
        'question_text': 'Solve: 2x + 7 = 15.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'x = 4',
        'explanation': '2x = 15 − 7 = 8. x = 8 ÷ 2 = 4.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B7.2.3.1.2',
        'bloom': 'Application',
        'question_text': 'Solve: x/3 = 5.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 8', 'B) 15', 'C) 2', 'D) 35'],
        'correct_answer': 'B',
        'explanation': 'Multiply both sides by 3: x = 15.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B8.2.3.1.1',
        'bloom': 'Application',
        'question_text': 'Solve: 3(x − 2) = 12.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) x = 6', 'B) x = 4', 'C) x = 2', 'D) x = 8'],
        'correct_answer': 'A',
        'explanation': '3x − 6 = 12. 3x = 18. x = 6.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B8.2.3.2.1',
        'bloom': 'Application',
        'question_text': 'Solve the inequality: 2x − 3 > 7.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'x > 5',
        'explanation': '2x > 10. x > 5.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B9.2.3.1.1',
        'bloom': 'Application',
        'question_text': 'Solve simultaneously: x + y = 10 and x − y = 4.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'x = 7, y = 3',
        'explanation': 'Adding: 2x = 14 → x = 7. From x + y = 10: y = 3.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B9.2.3.2.1',
        'bloom': 'Analysis',
        'question_text': 'The sum of three consecutive integers is 72. Find the integers.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '23, 24, 25',
        'explanation': 'Let integers be n, n+1, n+2. 3n+3=72 → n=23. Integers: 23, 24, 25.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B9.2.3.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'Create a real-life problem that can be modelled by the equation 5x + 20 = 70 and solve it.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'E.g.: A plumber charges GH₵20 call-out fee + GH₵5 per hour. Total bill is GH₵70. Hours worked? 5x+20=70 → x=10 hours.',
        'explanation': 'Marks for realistic context, correct equation, and solution.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B7.2.3.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The solution to x + 9 = 9 is x = 0.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'x + 9 = 9 → x = 9 − 9 = 0.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B8.2.2.3.1',
        'bloom': 'Comprehension',
        'question_text': 'What does it mean to "factorise" an expression?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': [
            'A) Expand the brackets',
            'B) Write it as a product of its factors',
            'C) Solve for x',
            'D) Substitute values',
        ],
        'correct_answer': 'B',
        'explanation': 'Factorising means expressing an expression as a product of its factors.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B9.2.1.2.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A pattern of matchsticks forms squares: 4, 7, 10, 13, … sticks. Write a formula for the nth term and predict how many sticks are needed for the 50th figure.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Tₙ = 3n + 1. T₅₀ = 3(50) + 1 = 151 sticks.',
        'explanation': 'First term a=4, d=3. Tₙ = a + (n−1)d = 4 + 3n − 3 = 3n + 1.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B8.2.3.3.1',
        'bloom': 'Comprehension',
        'question_text': 'What does the inequality symbol ≤ mean?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Less than', 'B) Greater than or equal to', 'C) Less than or equal to', 'D) Not equal to'],
        'correct_answer': 'C',
        'explanation': '≤ means "less than or equal to."',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B9.2.2.3.1',
        'bloom': 'Analysis',
        'question_text': 'Simplify: (3x²y)(2xy³).',
        'question_format': 'fill',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '6x³y⁴',
        'explanation': 'Coefficients: 3×2=6. x: x²×x=x³. y: y×y³=y⁴. → 6x³y⁴.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B9.2.3.4.1',
        'bloom': 'Application',
        'question_text': 'Solve: x² − 5x + 6 = 0.',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) x=2, x=3', 'B) x=−2, x=−3', 'C) x=1, x=6', 'D) x=−1, x=−6'],
        'correct_answer': 'A',
        'explanation': 'Factorise: (x−2)(x−3)=0. x=2 or x=3.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B7.2.1.3.1',
        'bloom': 'Application',
        'question_text': 'Complete the pattern: 64, 32, 16, ___, 4.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '8',
        'explanation': 'Each term is halved: 64÷2=32, 32÷2=16, 16÷2=8, 8÷2=4.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 3: GEOMETRY AND MEASUREMENT (50 items)
    # ═══════════════════════════════════════════════════════════════════════════

    # ── Shapes and Space ───────────────────────────────────────
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'How many sides does a hexagon have?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 5', 'B) 6', 'C) 7', 'D) 8'],
        'correct_answer': 'B',
        'explanation': 'A hexagon has 6 sides.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.1.2',
        'bloom': 'Knowledge',
        'question_text': 'The sum of angles in a triangle is 180°.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'The angle-sum property of a triangle states that interior angles add up to 180°.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.2.1',
        'bloom': 'Application',
        'question_text': 'Two angles of a triangle are 65° and 50°. Find the third angle.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '65°',
        'explanation': '180 − 65 − 50 = 65°.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B8.3.1.1.1',
        'bloom': 'Comprehension',
        'question_text': 'What type of triangle has all three sides equal?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Isosceles', 'B) Scalene', 'C) Equilateral', 'D) Right-angled'],
        'correct_answer': 'C',
        'explanation': 'An equilateral triangle has all three sides (and angles) equal.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B8.3.1.2.1',
        'bloom': 'Application',
        'question_text': 'Find the sum of interior angles of a pentagon.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 360°', 'B) 540°', 'C) 720°', 'D) 180°'],
        'correct_answer': 'B',
        'explanation': 'Sum = (5−2) × 180 = 3 × 180 = 540°.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.1.1',
        'bloom': 'Application',
        'question_text': 'Find each interior angle of a regular octagon.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '135°',
        'explanation': 'Sum = (8−2)×180 = 1080°. Each angle = 1080÷8 = 135°.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.2.1',
        'bloom': 'Analysis',
        'question_text': 'A quadrilateral has angles 90°, 80°, and 110°. What is the fourth angle and what type of quadrilateral could it be?',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '4th angle = 360−280 = 80°. It is an irregular quadrilateral (no parallel sides implied).',
        'explanation': 'Sum of angles in any quadrilateral = 360°.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.3.1',
        'bloom': 'Knowledge',
        'question_text': 'A line segment joining the centre of a circle to any point on the circle is called a:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Diameter', 'B) Chord', 'C) Radius', 'D) Arc'],
        'correct_answer': 'C',
        'explanation': 'The radius is the distance from the centre to the circumference.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B8.3.1.3.1',
        'bloom': 'Comprehension',
        'question_text': 'The diameter of a circle is always _______ the radius.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'twice',
        'explanation': 'Diameter = 2 × radius.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'Explain why all radii of a circle are equal. How does this definition help in constructing a circle with a compass?',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'A circle is defined as the set of all points equidistant from the centre. The compass keeps a fixed distance (radius), tracing all points at that distance.',
        'explanation': 'The definition of a circle guarantees equal radii, which is the principle behind compass construction.',
    },

    # ── Measurement (Length, Area, Volume) ─────────────────────
    {
        'topic': 'Measurement',
        'ges_code': 'B7.3.2.1.1',
        'bloom': 'Application',
        'question_text': 'Find the perimeter of a rectangle with length 12 cm and width 8 cm.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 20 cm', 'B) 40 cm', 'C) 96 cm', 'D) 32 cm'],
        'correct_answer': 'B',
        'explanation': 'P = 2(l + w) = 2(12 + 8) = 2 × 20 = 40 cm.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B7.3.2.1.2',
        'bloom': 'Application',
        'question_text': 'Find the area of a triangle with base 10 cm and height 6 cm.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '30 cm²',
        'explanation': 'A = ½ × b × h = ½ × 10 × 6 = 30 cm².',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B7.3.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'How many centimetres are in 1 metre?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 10', 'B) 100', 'C) 1000', 'D) 1'],
        'correct_answer': 'B',
        'explanation': '1 m = 100 cm.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.1.1',
        'bloom': 'Application',
        'question_text': 'Find the circumference of a circle with radius 7 cm. (Use π = 22/7.)',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 22 cm', 'B) 44 cm', 'C) 154 cm', 'D) 14 cm'],
        'correct_answer': 'B',
        'explanation': 'C = 2πr = 2 × 22/7 × 7 = 44 cm.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.1.2',
        'bloom': 'Application',
        'question_text': 'Find the area of a circle with diameter 14 cm. (π = 22/7.)',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '154 cm²',
        'explanation': 'r = 7. A = πr² = 22/7 × 49 = 154 cm².',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.2.1',
        'bloom': 'Application',
        'question_text': 'Find the volume of a cuboid with length 5 cm, width 4 cm, and height 3 cm.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 12 cm³', 'B) 60 cm³', 'C) 24 cm³', 'D) 47 cm³'],
        'correct_answer': 'B',
        'explanation': 'V = l × w × h = 5 × 4 × 3 = 60 cm³.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B9.3.2.1.1',
        'bloom': 'Application',
        'question_text': 'Find the volume of a cylinder with radius 7 cm and height 10 cm. (π = 22/7.)',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '1540 cm³',
        'explanation': 'V = πr²h = 22/7 × 49 × 10 = 1540 cm³.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B9.3.2.2.1',
        'bloom': 'Analysis',
        'question_text': 'A cylindrical water tank has radius 1.4 m and height 2 m. How many litres of water can it hold? (1 m³ = 1000 L, π = 22/7.)',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'V = 22/7 × 1.96 × 2 = 12.32 m³. 12.32 × 1000 = 12,320 litres.',
        'explanation': 'Real-life application of cylinder volume with unit conversion.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B9.3.2.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A school wants to paint a rectangular wall 10 m by 3 m. One tin of paint covers 8 m². How many tins are needed? Should you round up or down? Explain.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Area = 30 m². Tins = 30/8 = 3.75. Must round UP to 4 tins (you cannot buy 0.75 of a tin).',
        'explanation': 'Real-world rounding: always round up for materials to ensure full coverage.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B7.3.2.3.1',
        'bloom': 'Comprehension',
        'question_text': 'Area is measured in square units while volume is measured in cubic units.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Area = 2D (square units like cm²). Volume = 3D (cubic units like cm³).',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.3.1',
        'bloom': 'Application',
        'question_text': 'Convert 2.5 km to metres.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '2500 m',
        'explanation': '2.5 × 1000 = 2500 m.',
    },

    # ── Position, Transformation and Symmetry ──────────────────
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B7.3.3.1.1',
        'bloom': 'Knowledge',
        'question_text': 'How many lines of symmetry does a square have?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 1', 'B) 2', 'C) 4', 'D) 8'],
        'correct_answer': 'C',
        'explanation': 'A square has 4 lines of symmetry: 2 diagonal and 2 through midpoints of opposite sides.',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B7.3.3.1.2',
        'bloom': 'Comprehension',
        'question_text': 'An equilateral triangle has 3 lines of symmetry.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Each line passes through a vertex and the midpoint of the opposite side.',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B8.3.3.1.1',
        'bloom': 'Comprehension',
        'question_text': 'A reflection is a transformation that "flips" a shape over a mirror line.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Reflection produces a mirror image of the original shape across the line of reflection.',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B8.3.3.2.1',
        'bloom': 'Application',
        'question_text': 'Triangle A has vertices (1,1), (3,1), (2,3). Translate it 4 units right and 2 units up. What are the new vertices?',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '(5,3), (7,3), (6,5)',
        'explanation': 'Add (4,2) to each vertex: (1+4,1+2)=(5,3), (3+4,1+2)=(7,3), (2+4,3+2)=(6,5).',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B9.3.3.1.1',
        'bloom': 'Application',
        'question_text': 'Rotate point (3, 0) by 90° anticlockwise about the origin. What are the new coordinates?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) (0, 3)', 'B) (−3, 0)', 'C) (0, −3)', 'D) (3, 3)'],
        'correct_answer': 'A',
        'explanation': '90° anticlockwise rotation: (x, y) → (−y, x). (3, 0) → (0, 3).',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B9.3.3.2.1',
        'bloom': 'Analysis',
        'question_text': 'A shape is enlarged by scale factor 2. By what factor does its area increase?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) 2', 'B) 4', 'C) 8', 'D) 16'],
        'correct_answer': 'B',
        'explanation': 'Area scales by the square of the linear scale factor: 2² = 4.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.4.1',
        'bloom': 'Knowledge',
        'question_text': 'Angles on a straight line add up to:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 90°', 'B) 180°', 'C) 270°', 'D) 360°'],
        'correct_answer': 'B',
        'explanation': 'Supplementary angles on a straight line sum to 180°.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B8.3.1.4.1',
        'bloom': 'Application',
        'question_text': 'Two parallel lines are cut by a transversal. One alternate angle is 55°. What is the other alternate angle?',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '55°',
        'explanation': 'Alternate angles are equal when lines are parallel.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.4.1',
        'bloom': 'Application',
        'question_text': 'In the figure, angle ABD = 35° and angle DBC = 40°. Find angle ABC.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '75°',
        'explanation': 'ABC = ABD + DBC = 35 + 40 = 75°.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B7.3.2.4.1',
        'bloom': 'Comprehension',
        'question_text': 'The area of a square with side 5 cm is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 20 cm²', 'B) 10 cm²', 'C) 25 cm²', 'D) 15 cm²'],
        'correct_answer': 'C',
        'explanation': 'Area = side² = 5² = 25 cm².',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.5.1',
        'bloom': 'Comprehension',
        'question_text': 'A right angle measures exactly:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 45°', 'B) 180°', 'C) 90°', 'D) 360°'],
        'correct_answer': 'C',
        'explanation': 'A right angle = 90°.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B9.3.2.4.1',
        'bloom': 'Analysis',
        'question_text': 'A cone has radius 3 cm and slant height 5 cm. Find its curved surface area. (CSA = πrl.)',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'CSA = π × 3 × 5 = 15π ≈ 47.1 cm²',
        'explanation': 'Apply CSA = πrl with r=3 and l=5.',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B9.3.3.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A company logo needs to look the same after a 120° rotation. What is the minimum order of rotational symmetry? Give an example of a shape with this property.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Order 3 (360°/120° = 3). Example: equilateral triangle.',
        'explanation': 'Rotational symmetry of order n means the shape maps onto itself n times in a full rotation.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.4.1',
        'bloom': 'Application',
        'question_text': 'Find the total surface area of a cube with side 4 cm.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 64 cm²', 'B) 96 cm²', 'C) 16 cm²', 'D) 24 cm²'],
        'correct_answer': 'B',
        'explanation': 'SA = 6 × side² = 6 × 16 = 96 cm².',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.5.1',
        'bloom': 'Application',
        'question_text': 'Using Pythagoras\' theorem, find the hypotenuse of a right triangle with legs 6 cm and 8 cm.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 14 cm', 'B) 10 cm', 'C) 12 cm', 'D) 100 cm'],
        'correct_answer': 'B',
        'explanation': 'c² = 6² + 8² = 36 + 64 = 100. c = 10 cm.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.6.1',
        'bloom': 'Analysis',
        'question_text': 'A ladder 5 m long leans against a wall with its foot 3 m from the base. How high up the wall does it reach?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': '4 m',
        'explanation': 'h² = 5² − 3² = 25 − 9 = 16. h = 4 m. (Pythagorean triple: 3-4-5.)',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 4: DATA (40 items)
    # ═══════════════════════════════════════════════════════════════════════════

    # ── Data Collection and Organisation ───────────────────────
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B7.4.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'A tally chart uses groups of _____ marks.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '5',
        'explanation': 'Tally marks are grouped in fives (four vertical lines crossed by a diagonal).',
    },
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B7.4.1.1.2',
        'bloom': 'Knowledge',
        'question_text': 'Primary data is data collected by the researcher themselves.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Primary data is first-hand, collected directly. Secondary data comes from existing sources.',
    },
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B8.4.1.1.1',
        'bloom': 'Comprehension',
        'question_text': 'Which data collection method is MOST suitable for finding students\' favourite subjects?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Observation', 'B) Experiment', 'C) Questionnaire', 'D) Measuring'],
        'correct_answer': 'C',
        'explanation': 'A questionnaire or survey efficiently gathers opinions from many students.',
    },
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B8.4.1.2.1',
        'bloom': 'Application',
        'question_text': 'Given the data set: 4, 7, 2, 9, 7, 3, 7, 5 — construct a frequency table.',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '2:1, 3:1, 4:1, 5:1, 7:3, 9:1',
        'explanation': 'Count each value\'s frequency: 7 appears 3 times, all others once.',
    },
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B9.4.1.1.1',
        'bloom': 'Analysis',
        'question_text': 'A researcher wants to know if screen time affects exam performance. What type of data collection is most appropriate and why?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'A structured questionnaire/survey combined with exam records — quantitative data allows correlation analysis.',
        'explanation': 'Requires both variables measured numerically for statistical comparison.',
    },

    # ── Data Representation (Graphs, Charts) ───────────────────
    {
        'topic': 'Data Representation',
        'ges_code': 'B7.4.2.1.1',
        'bloom': 'Knowledge',
        'question_text': 'A bar chart uses rectangular bars to represent data.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Bar charts display categorical data using bars of varying heights.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B7.4.2.1.2',
        'bloom': 'Comprehension',
        'question_text': 'Which type of graph is best for showing change over time?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Pie chart', 'B) Line graph', 'C) Bar chart', 'D) Pictogram'],
        'correct_answer': 'B',
        'explanation': 'Line graphs show trends and changes over time effectively.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B8.4.2.1.1',
        'bloom': 'Comprehension',
        'question_text': 'In a pie chart, the total angle at the centre is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 180°', 'B) 90°', 'C) 360°', 'D) 270°'],
        'correct_answer': 'C',
        'explanation': 'A full circle = 360° and a pie chart represents the whole data set.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B8.4.2.2.1',
        'bloom': 'Application',
        'question_text': 'In a survey, 45 students chose Maths, 30 chose English, and 15 chose Science. What angle represents Maths on a pie chart?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 180°', 'B) 120°', 'C) 90°', 'D) 60°'],
        'correct_answer': 'A',
        'explanation': 'Total = 90. Maths angle = (45/90) × 360 = 180°.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B9.4.2.1.1',
        'bloom': 'Application',
        'question_text': 'The table shows test scores: 40-49 (5), 50-59 (12), 60-69 (18), 70-79 (10), 80-89 (5). Draw a suitable graph for this data.',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'A histogram (continuous grouped data with class intervals on x-axis, frequency on y-axis).',
        'explanation': 'Grouped continuous data is best represented by a histogram.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B9.4.2.2.1',
        'bloom': 'Analysis',
        'question_text': 'A newspaper shows a bar chart where the y-axis starts at 50 instead of 0. How might this mislead readers?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Starting at 50 exaggerates differences between bars, making small variations appear large and potentially misleading readers about the magnitude of change.',
        'explanation': 'Critical data literacy: truncated axes can distort visual perception of data.',
    },

    # ── Measures of Central Tendency ───────────────────────────
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B7.4.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The mean of a data set is found by dividing the sum of all values by the number of values.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Mean = Sum of values ÷ Number of values.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B7.4.2.3.1',
        'bloom': 'Application',
        'question_text': 'Find the mean of: 12, 15, 18, 20, 25.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '18',
        'explanation': 'Sum = 90. Mean = 90 ÷ 5 = 18.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B7.4.2.3.2',
        'bloom': 'Application',
        'question_text': 'Find the median of: 3, 8, 1, 7, 5.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 3', 'B) 5', 'C) 7', 'D) 8'],
        'correct_answer': 'B',
        'explanation': 'Arrange: 1, 3, 5, 7, 8. Middle value = 5.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B8.4.2.3.1',
        'bloom': 'Application',
        'question_text': 'Find the mode of: 4, 7, 2, 7, 9, 3, 7, 5.',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '7',
        'explanation': '7 appears 3 times, more than any other value.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B8.4.2.4.1',
        'bloom': 'Application',
        'question_text': 'The ages of 6 students are: 12, 14, 13, 12, 15, 14. Find the range.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 2', 'B) 3', 'C) 12', 'D) 15'],
        'correct_answer': 'B',
        'explanation': 'Range = 15 − 12 = 3.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B9.4.2.3.1',
        'bloom': 'Application',
        'question_text': 'The mean of five numbers is 24. Four of the numbers are 20, 22, 25, 30. Find the fifth number.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 23', 'B) 24', 'C) 25', 'D) 27'],
        'correct_answer': 'A',
        'explanation': 'Sum = 5 × 24 = 120. Known sum = 97. Fifth = 120 − 97 = 23.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B9.4.2.4.1',
        'bloom': 'Analysis',
        'question_text': 'Two classes have mean scores of 65 (30 students) and 70 (20 students). Find the combined mean.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Combined mean = (30×65 + 20×70) ÷ 50 = (1950+1400) ÷ 50 = 3350 ÷ 50 = 67.',
        'explanation': 'Weighted mean considers the number of students in each class.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B9.4.2.5.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A teacher reports the "average" mark as 72. Explain why this could be misleading if a few students scored very high marks.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Outliers (very high scores) pull the mean upward, making it unrepresentative of most students. The median would give a better picture of typical performance.',
        'explanation': 'Critical understanding of mean vs. median and the effect of outliers.',
    },

    # ── Probability and Chance ─────────────────────────────────
    {
        'topic': 'Probability',
        'ges_code': 'B7.4.3.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Probability of an event ranges from:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) −1 to 1', 'B) 0 to 1', 'C) 0 to 100', 'D) 1 to 10'],
        'correct_answer': 'B',
        'explanation': 'Probability is always between 0 (impossible) and 1 (certain), inclusive.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B7.4.3.1.2',
        'bloom': 'Application',
        'question_text': 'A fair die is thrown. What is the probability of getting a number greater than 4?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 1/6', 'B) 2/6', 'C) 4/6', 'D) 1/2'],
        'correct_answer': 'B',
        'explanation': 'Numbers greater than 4: {5, 6} → 2 outcomes. P = 2/6 = 1/3.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B8.4.3.1.1',
        'bloom': 'Application',
        'question_text': 'A bag has 3 red, 5 blue, and 2 green balls. What is the probability of picking a blue ball?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 3/10', 'B) 5/10', 'C) 2/10', 'D) 1/10'],
        'correct_answer': 'B',
        'explanation': 'Total = 10. P(blue) = 5/10 = 1/2.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B8.4.3.2.1',
        'bloom': 'Comprehension',
        'question_text': 'If the probability of rain tomorrow is 0.3, the probability of no rain is:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '0.7',
        'explanation': 'P(not rain) = 1 − P(rain) = 1 − 0.3 = 0.7.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B9.4.3.1.1',
        'bloom': 'Application',
        'question_text': 'Two coins are tossed. What is the probability of getting exactly one head?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 1/4', 'B) 1/2', 'C) 3/4', 'D) 1/3'],
        'correct_answer': 'B',
        'explanation': 'Sample space: {HH, HT, TH, TT}. Exactly one head: {HT, TH} = 2 out of 4 = 1/2.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B9.4.3.2.1',
        'bloom': 'Analysis',
        'question_text': 'A spinner has sections: Red (120°), Blue (90°), Green (60°), Yellow (90°). Which colour is LEAST likely?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Red', 'B) Blue', 'C) Green', 'D) Yellow'],
        'correct_answer': 'C',
        'explanation': 'Green has the smallest angle (60°/360° = 1/6), so it is least likely.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B9.4.3.3.1',
        'bloom': 'Analysis',
        'question_text': 'In 50 coin tosses, 32 were heads. What is the experimental probability of heads? How does it compare to the theoretical probability?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Experimental P(H) = 32/50 = 0.64. Theoretical P(H) = 0.5. The experimental is higher, but with more tosses it should approach 0.5 (Law of Large Numbers).',
        'explanation': 'Distinguishes experimental vs. theoretical probability and references convergence.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B9.4.3.4.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'Design a simple probability experiment using a bag of coloured beads. State the sample space, one event, and calculate its theoretical probability.',
        'question_format': 'essay',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'E.g.: Bag with 4 red, 3 blue, 3 green beads. Event: picking red. P(red)=4/10=2/5. Sample space = {R,R,R,R,B,B,B,G,G,G}.',
        'explanation': 'Open-ended; marks for clear setup, correct sample space, valid probability calculation.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B7.4.2.4.1',
        'bloom': 'Application',
        'question_text': 'In a pictogram, one symbol represents 5 students. If 35 students chose football, how many symbols should be drawn?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '7',
        'explanation': '35 ÷ 5 = 7 symbols.',
    },
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B7.4.1.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Data that can be counted (e.g. number of students) is called:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Continuous data', 'B) Discrete data', 'C) Qualitative data', 'D) Secondary data'],
        'correct_answer': 'B',
        'explanation': 'Discrete data takes distinct countable values. Continuous data can take any value in a range.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B8.4.2.5.1',
        'bloom': 'Comprehension',
        'question_text': 'Which measure of central tendency is affected most by extreme values (outliers)?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Mean', 'B) Median', 'C) Mode', 'D) Range'],
        'correct_answer': 'A',
        'explanation': 'The mean uses all values in its calculation, so outliers pull it up or down significantly.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B9.4.2.3.1',
        'bloom': 'Synthesis/Evaluation',
        'question_text': 'A school has attendance data for 12 months. Recommend the best graph type and explain your choice.',
        'question_format': 'short',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'A line graph — it shows trends over time clearly, allowing the school to identify seasonal patterns in attendance.',
        'explanation': 'Time-series data is best displayed with line graphs to show trends.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B7.4.3.2.1',
        'bloom': 'Knowledge',
        'question_text': 'An event with probability 0 is called:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Certain', 'B) Likely', 'C) Impossible', 'D) Unlikely'],
        'correct_answer': 'C',
        'explanation': 'P = 0 means the event cannot happen (impossible).',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # ADDITIONAL ITEMS — fill distribution gaps (48 items)
    # ═══════════════════════════════════════════════════════════════════════════

    # ── Number +14 ─────────────────────────────────────────────
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.6.1',
        'bloom': 'Knowledge',
        'question_text': 'Every even number is divisible by 2.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'By definition, even numbers are exactly those divisible by 2.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B8.1.1.5.1',
        'bloom': 'Comprehension',
        'question_text': 'What is the HCF of 24 and 36?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 6', 'B) 8', 'C) 12', 'D) 18'],
        'correct_answer': 'C',
        'explanation': '24 = 2³×3, 36 = 2²×3². HCF = 2²×3 = 12.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B7.1.2.7.1',
        'bloom': 'Knowledge',
        'question_text': 'What is 0 divided by 5?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '0',
        'explanation': '0 ÷ any non-zero number = 0.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B8.1.3.5.1',
        'bloom': 'Comprehension',
        'question_text': 'Which fraction is equivalent to 0.2?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 1/2', 'B) 1/5', 'C) 2/3', 'D) 1/4'],
        'correct_answer': 'B',
        'explanation': '0.2 = 2/10 = 1/5.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B7.1.4.3.1',
        'bloom': 'Knowledge',
        'question_text': 'A ratio compares two or more quantities of the same kind.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Ratios express the relative sizes of quantities and require the same units.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.6.1',
        'bloom': 'Comprehension',
        'question_text': 'Which of the following is the correct interpretation of 2⁵?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 2 + 5', 'B) 2 × 5', 'C) 2 × 2 × 2 × 2 × 2', 'D) 5 × 5'],
        'correct_answer': 'C',
        'explanation': '2⁵ means 2 multiplied by itself 5 times = 32.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B9.1.1.5.1',
        'bloom': 'Knowledge',
        'question_text': 'List all prime numbers between 10 and 20.',
        'question_format': 'short',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '11, 13, 17, 19',
        'explanation': '11, 13, 17, 19 are divisible only by 1 and themselves.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B9.1.3.5.1',
        'bloom': 'Comprehension',
        'question_text': 'Express 7/20 as a percentage.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '35%',
        'explanation': '7/20 × 100 = 35%.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.7.1',
        'bloom': 'Comprehension',
        'question_text': 'The additive inverse of −7 is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) −7', 'B) 7', 'C) 0', 'D) 1/7'],
        'correct_answer': 'B',
        'explanation': 'The additive inverse of −7 is 7 because −7 + 7 = 0.',
    },
    {
        'topic': 'Ratio and Proportion',
        'ges_code': 'B8.1.4.4.1',
        'bloom': 'Comprehension',
        'question_text': 'If the ratio of teachers to students is 1:30, and there are 8 teachers, how many students are there?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 200', 'B) 240', 'C) 300', 'D) 38'],
        'correct_answer': 'B',
        'explanation': '1 part = 8 teachers. Students = 30 × 8 = 240.',
    },
    {
        'topic': 'Number and Numeration Systems',
        'ges_code': 'B7.1.1.7.1',
        'bloom': 'Knowledge',
        'question_text': 'What is the value of |−12| (absolute value)?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '12',
        'explanation': 'Absolute value measures distance from 0: |−12| = 12.',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B9.1.2.7.1',
        'bloom': 'Analysis',
        'question_text': 'A shopkeeper makes a 25% profit on cost price. If he sells an item for GH₵500, what was the cost price?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) GH₵375', 'B) GH₵400', 'C) GH₵450', 'D) GH₵475'],
        'correct_answer': 'B',
        'explanation': 'Selling price = 1.25 × CP. CP = 500/1.25 = GH₵400.',
    },
    {
        'topic': 'Fractions, Decimals and Percentages',
        'ges_code': 'B7.1.3.6.1',
        'bloom': 'Knowledge',
        'question_text': 'A proper fraction has a numerator smaller than its denominator.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'In a proper fraction, numerator < denominator (e.g. 3/4).',
    },
    {
        'topic': 'Number Operations',
        'ges_code': 'B8.1.2.8.1',
        'bloom': 'Comprehension',
        'question_text': 'Estimate 398 × 21 by rounding each number to the nearest ten.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 8000', 'B) 8400', 'C) 8200', 'D) 7800'],
        'correct_answer': 'A',
        'explanation': '400 × 20 = 8,000.',
    },

    # ── Algebra +13 ────────────────────────────────────────────
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B8.2.1.3.1',
        'bloom': 'Knowledge',
        'question_text': 'In the sequence 5, 10, 20, 40, … the common ratio is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 5', 'B) 2', 'C) 10', 'D) 3'],
        'correct_answer': 'B',
        'explanation': '10/5 = 2, 20/10 = 2, 40/20 = 2. Common ratio = 2.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B7.2.2.3.1',
        'bloom': 'Knowledge',
        'question_text': 'An expression with one term is called a monomial.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Monomial = 1 term, binomial = 2 terms, trinomial = 3 terms.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B7.2.3.3.1',
        'bloom': 'Comprehension',
        'question_text': 'What is the value of y if 5y = 35?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '7',
        'explanation': 'y = 35 ÷ 5 = 7.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B8.2.2.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Simplify: 5a − 2b + 3a + 4b.',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': '8a + 2b',
        'explanation': 'Like terms: 5a+3a = 8a, −2b+4b = 2b.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B8.2.3.4.1',
        'bloom': 'Knowledge',
        'question_text': 'In an equation, the left-hand side must equal the right-hand side.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'An equation is a statement that two expressions are equal.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B9.2.1.3.1',
        'bloom': 'Comprehension',
        'question_text': 'A sequence where each term is obtained by multiplying the previous term by a constant is called:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Arithmetic', 'B) Fibonacci', 'C) Geometric', 'D) Harmonic'],
        'correct_answer': 'C',
        'explanation': 'A geometric sequence has a constant common ratio between consecutive terms.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B9.2.2.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Simplify: 2x/6.',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) x/3', 'B) 2x/3', 'C) x/6', 'D) 3x'],
        'correct_answer': 'A',
        'explanation': '2x/6 = x/3 (divide numerator and denominator by 2).',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B9.2.3.5.1',
        'bloom': 'Analysis',
        'question_text': 'A rectangle has perimeter 36 cm and length 3 cm more than width. Find the dimensions.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Width = 7.5 cm, Length = 10.5 cm',
        'explanation': '2(w + w+3) = 36 → 4w+6 = 36 → w = 7.5, l = 10.5.',
    },
    {
        'topic': 'Patterns and Relations',
        'ges_code': 'B7.2.1.4.1',
        'bloom': 'Comprehension',
        'question_text': 'What is the common difference in the sequence: 10, 7, 4, 1, …?',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '-3',
        'explanation': '7−10 = −3, 4−7 = −3. The common difference is −3.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B8.2.2.5.1',
        'bloom': 'Knowledge',
        'question_text': 'What is the degree of the polynomial 3x² + 5x − 7?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 1', 'B) 2', 'C) 3', 'D) 7'],
        'correct_answer': 'B',
        'explanation': 'The highest power of x is 2, so the degree is 2.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B9.2.3.6.1',
        'bloom': 'Analysis',
        'question_text': 'For what values of x is the expression (x−3)/(x+2) undefined?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) x = 3', 'B) x = −2', 'C) x = 0', 'D) x = 2'],
        'correct_answer': 'B',
        'explanation': 'The expression is undefined when the denominator = 0: x+2 = 0 → x = −2.',
    },
    {
        'topic': 'Algebraic Expressions',
        'ges_code': 'B7.2.2.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Write an algebraic expression for: "5 more than twice a number n."',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '2n + 5',
        'explanation': 'Twice n = 2n. Five more = +5. Expression: 2n + 5.',
    },
    {
        'topic': 'Equations and Inequalities',
        'ges_code': 'B8.2.3.5.1',
        'bloom': 'Comprehension',
        'question_text': 'Which of the following is an inequality?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) x + 3 = 7', 'B) 2x − 1 > 5', 'C) 3 × 4 = 12', 'D) y = 2x + 1'],
        'correct_answer': 'B',
        'explanation': 'An inequality uses <, >, ≤, or ≥. Only B uses >.',
    },

    # ── Geometry +13 ───────────────────────────────────────────
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.6.1',
        'bloom': 'Knowledge',
        'question_text': 'Vertically opposite angles are always equal.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'When two lines intersect, the vertically opposite angles formed are equal.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B7.3.2.5.1',
        'bloom': 'Knowledge',
        'question_text': 'The perimeter of a circle is called its:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Diameter', 'B) Radius', 'C) Circumference', 'D) Area'],
        'correct_answer': 'C',
        'explanation': 'The distance around a circle is its circumference.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B8.3.1.5.1',
        'bloom': 'Comprehension',
        'question_text': 'A parallelogram has opposite sides that are:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Perpendicular', 'B) Unequal', 'C) Equal and parallel', 'D) Curved'],
        'correct_answer': 'C',
        'explanation': 'In a parallelogram, opposite sides are equal in length and parallel.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B9.3.2.5.1',
        'bloom': 'Comprehension',
        'question_text': 'The formula for the area of a trapezium is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) l × w', 'B) ½(a+b)h', 'C) πr²', 'D) s²'],
        'correct_answer': 'B',
        'explanation': 'Trapezium area = ½ × (sum of parallel sides) × height.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.7.1',
        'bloom': 'Comprehension',
        'question_text': 'How many faces does a triangular prism have?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 3', 'B) 4', 'C) 5', 'D) 6'],
        'correct_answer': 'C',
        'explanation': '2 triangular faces + 3 rectangular faces = 5 faces.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.5.1',
        'bloom': 'Knowledge',
        'question_text': 'The area of a parallelogram is base × height.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Area of parallelogram = base × perpendicular height.',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B7.3.3.2.1',
        'bloom': 'Knowledge',
        'question_text': 'How many lines of symmetry does a circle have?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 1', 'B) 2', 'C) 4', 'D) Infinite'],
        'correct_answer': 'D',
        'explanation': 'Any diameter of a circle is a line of symmetry, and there are infinitely many diameters.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B8.3.1.6.1',
        'bloom': 'Analysis',
        'question_text': 'Co-interior (allied) angles between parallel lines add up to:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 90°', 'B) 180°', 'C) 270°', 'D) 360°'],
        'correct_answer': 'B',
        'explanation': 'Co-interior angles formed between parallel lines sum to 180°.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B9.3.2.6.1',
        'bloom': 'Analysis',
        'question_text': 'A sector of a circle has angle 90° and radius 14 cm. Find its area. (π = 22/7.)',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Area = (90/360) × πr² = ¼ × 22/7 × 196 = 154 cm²',
        'explanation': 'Sector area = (θ/360) × πr².',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B7.3.1.7.1',
        'bloom': 'Comprehension',
        'question_text': 'An acute angle is less than 90°.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Acute angles measure between 0° and 90°.',
    },
    {
        'topic': 'Measurement',
        'ges_code': 'B8.3.2.6.1',
        'bloom': 'Comprehension',
        'question_text': 'How many millilitres are in 1 litre?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) 10', 'B) 100', 'C) 1000', 'D) 10000'],
        'correct_answer': 'C',
        'explanation': '1 litre = 1000 millilitres.',
    },
    {
        'topic': 'Shapes and Space',
        'ges_code': 'B9.3.1.8.1',
        'bloom': 'Analysis',
        'question_text': 'Triangle PQR has sides 5 cm, 12 cm, and 13 cm. Is it a right triangle? Justify.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Yes. 5²+12² = 25+144 = 169 = 13². Pythagoras\' theorem holds, so it is a right triangle.',
        'explanation': 'If a²+b² = c² where c is the longest side, the triangle is right-angled.',
    },
    {
        'topic': 'Transformation and Symmetry',
        'ges_code': 'B8.3.3.3.1',
        'bloom': 'Comprehension',
        'question_text': 'A translation moves every point of a shape the same distance in the same direction.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Translation is a rigid transformation — it slides a shape without rotating or resizing.',
    },

    # ── Data +8 ────────────────────────────────────────────────
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B9.4.1.2.1',
        'bloom': 'Knowledge',
        'question_text': 'A sample is a subset of the population used in a survey.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Sampling selects a representative group from the entire population for study.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B7.4.2.5.1',
        'bloom': 'Knowledge',
        'question_text': 'The mode is the value that appears most frequently in a data set.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'The mode is the most common value. A data set can have more than one mode.',
    },
    {
        'topic': 'Data Representation',
        'ges_code': 'B8.4.2.3.1',
        'bloom': 'Comprehension',
        'question_text': 'Which graph uses sectors of a circle to represent data?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Bar chart', 'B) Histogram', 'C) Pie chart', 'D) Line graph'],
        'correct_answer': 'C',
        'explanation': 'A pie chart divides a circle into sectors proportional to each category.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B8.4.3.3.1',
        'bloom': 'Comprehension',
        'question_text': 'The probability of an event and the probability of its complement always add up to:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': '1',
        'explanation': 'P(A) + P(not A) = 1.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B9.4.2.6.1',
        'bloom': 'Analysis',
        'question_text': 'Find the median of: 12, 15, 11, 18, 14, 20.',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 14', 'B) 14.5', 'C) 15', 'D) 13'],
        'correct_answer': 'B',
        'explanation': 'Sorted: 11,12,14,15,18,20. Middle pair: 14,15. Median = (14+15)/2 = 14.5.',
    },
    {
        'topic': 'Data Collection and Organisation',
        'ges_code': 'B8.4.1.3.1',
        'bloom': 'Comprehension',
        'question_text': 'Which of the following is qualitative data?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Height in cm', 'B) Favourite colour', 'C) Age in years', 'D) Number of siblings'],
        'correct_answer': 'B',
        'explanation': 'Qualitative (categorical) data describes qualities. Favourite colour is non-numerical.',
    },
    {
        'topic': 'Probability',
        'ges_code': 'B9.4.3.5.1',
        'bloom': 'Analysis',
        'question_text': 'A card is drawn from a standard deck of 52 cards. What is the probability of drawing a King?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 1/52', 'B) 4/52', 'C) 1/4', 'D) 13/52'],
        'correct_answer': 'B',
        'explanation': 'There are 4 Kings in a deck. P(King) = 4/52 = 1/13.',
    },
    {
        'topic': 'Measures of Central Tendency',
        'ges_code': 'B8.4.2.6.1',
        'bloom': 'Comprehension',
        'question_text': 'The range of a data set measures the:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Most common value', 'B) Middle value', 'C) Spread between highest and lowest values', 'D) Sum of all values'],
        'correct_answer': 'C',
        'explanation': 'Range = Maximum value − Minimum value. It measures data spread.',
    },
]


def get_distribution_summary():
    """Return a summary dict of the bank's distribution for verification."""
    from collections import Counter
    strands = Counter()
    blooms = Counter()
    formats = Counter()
    difficulties = Counter()
    levels = Counter()

    strand_map = {
        'Number and Numeration Systems': 'Number',
        'Number Operations': 'Number',
        'Fractions, Decimals and Percentages': 'Number',
        'Ratio and Proportion': 'Number',
        'Patterns and Relations': 'Algebra',
        'Algebraic Expressions': 'Algebra',
        'Equations and Inequalities': 'Algebra',
        'Shapes and Space': 'Geometry and Measurement',
        'Measurement': 'Geometry and Measurement',
        'Transformation and Symmetry': 'Geometry and Measurement',
        'Data Collection and Organisation': 'Data',
        'Data Representation': 'Data',
        'Measures of Central Tendency': 'Data',
        'Probability': 'Data',
    }

    for q in MATH_QUESTION_BANK:
        strand = strand_map.get(q['topic'], 'Unknown')
        strands[strand] += 1
        blooms[q['bloom']] += 1
        formats[q['question_format']] += 1
        difficulties[q['difficulty']] += 1
        code = q['ges_code']
        level = code.split('.')[0]  # B7, B8, B9
        levels[level] += 1

    return {
        'total': len(MATH_QUESTION_BANK),
        'strands': dict(strands),
        'blooms': dict(blooms),
        'formats': dict(formats),
        'difficulties': dict(difficulties),
        'levels': dict(levels),
    }
