"""
Religious and Moral Education (RME) BECE Question Bank
GES/NaCCA-aligned for JHS 1-3 (Basic 7-9)
Strands: God's Creation and Stewardship, Religious Practices, Moral Teachings, Unity in Diversity
"""

RME_QUESTION_BANK = [
    # ─── STRAND 1: GOD'S CREATION AND STEWARDSHIP ───
    {
        "topic": "God as Creator",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "God the Creator",
        "ges_code": "B7.1.1.1",
        "bloom": "Knowledge",
        "question_text": "According to the Bible, how many days did God use to create the heavens and the earth?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Five days", "Six days", "Seven days", "Eight days"],
        "correct_answer": "Six days",
        "explanation": "According to Genesis 1, God created the heavens and the earth in six days and rested on the seventh day."
    },
    {
        "topic": "God as Creator",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "God the Creator",
        "ges_code": "B7.1.1.1",
        "bloom": "Comprehension",
        "question_text": "In Islam, what is the term used to describe God as the Creator of all things?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Al-Rahman", "Al-Khaliq", "Al-Malik", "Al-Hakeem"],
        "correct_answer": "Al-Khaliq",
        "explanation": "Al-Khaliq is one of the 99 names of Allah meaning 'The Creator'. It emphasises God's role in creating all that exists."
    },
    {
        "topic": "God as Creator",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "God the Creator",
        "ges_code": "B7.1.1.1",
        "bloom": "Comprehension",
        "question_text": "Explain how the African Traditional Religion views God as the Creator.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "In African Traditional Religion, God is seen as the Supreme Being who created the universe and everything in it. He is known by various names such as Onyame (Akan), Mawu (Ewe), and is revered as the source of all life.",
        "explanation": "ATR recognises God as the ultimate creator, though worship often involves intermediaries like ancestors and lesser deities."
    },
    {
        "topic": "Stewardship",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "Caring for God's Creation",
        "ges_code": "B7.1.2.1",
        "bloom": "Application",
        "question_text": "Which of the following is the BEST way a student can show stewardship of God's creation?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Throwing rubbish into the gutter", "Planting trees in the school compound", "Breaking branches off trees for fun", "Wasting water in the school"],
        "correct_answer": "Planting trees in the school compound",
        "explanation": "Stewardship means taking care of God's creation. Planting trees helps the environment and shows responsible care for nature."
    },
    {
        "topic": "Stewardship",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "Caring for God's Creation",
        "ges_code": "B7.1.2.1",
        "bloom": "Analysis",
        "question_text": "A factory dumps chemical waste into a river that a community uses for drinking water. Analyse how this action goes against the principle of stewardship.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "The factory's action violates stewardship because: (1) It destroys God's creation (the river ecosystem), (2) It endangers human life which is sacred, (3) It shows selfishness and disregard for the common good, (4) It fails the responsibility God gave humans to care for the earth. True stewardship requires protecting natural resources for current and future generations.",
        "explanation": "Stewardship involves responsible management of resources. Pollution destroys the environment and harms others, directly opposing stewardship principles."
    },
    {
        "topic": "God as Creator",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "The Uniqueness of Human Beings",
        "ges_code": "B7.1.1.2",
        "bloom": "Knowledge",
        "question_text": "According to the Bible, human beings were created in the __________ of God.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "image",
        "explanation": "Genesis 1:27 states that God created man in His own image. This makes human beings unique among all creation."
    },
    {
        "topic": "Stewardship",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "Caring for God's Creation",
        "ges_code": "B8.1.2.1",
        "bloom": "Application",
        "question_text": "State THREE practical ways you can care for the environment in your community.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Organising community clean-up exercises, (2) Planting trees and flowers, (3) Proper disposal of waste in dustbins, (4) Avoiding bush burning, (5) Recycling materials where possible.",
        "explanation": "Caring for God's creation involves practical steps to keep our environment clean and sustainable."
    },
    {
        "topic": "God's Attributes",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "Attributes of God",
        "ges_code": "B8.1.1.1",
        "bloom": "Comprehension",
        "question_text": "Which attribute of God means He is present everywhere at the same time?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Omnipotence", "Omniscience", "Omnipresence", "Benevolence"],
        "correct_answer": "Omnipresence",
        "explanation": "Omnipresence means God is present everywhere at the same time. Omnipotence means all-powerful, and omniscience means all-knowing."
    },
    {
        "topic": "God's Attributes",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "Attributes of God",
        "ges_code": "B8.1.1.1",
        "bloom": "Knowledge",
        "question_text": "God is omniscient. This means God is all-knowing.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "True",
        "explanation": "Omniscient comes from Latin 'omni' (all) and 'scientia' (knowledge). It means God knows everything."
    },
    {
        "topic": "God as Creator",
        "strand": "God's Creation and Stewardship",
        "sub_strand": "God the Creator",
        "ges_code": "B9.1.1.1",
        "bloom": "Synthesis",
        "question_text": "Compare and contrast how Christianity, Islam, and African Traditional Religion explain the origin of the world.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Similarities: All three religions believe in a Supreme Being who created the world. God is seen as all-powerful and the source of life. Differences: Christianity and Islam have written scriptures (Bible and Quran) with specific creation accounts, while ATR relies on oral tradition. Christianity teaches creation in six days, Islam describes creation through Allah's command 'Be', and ATR uses myths and legends passed down through generations. All three agree that humans have a special place in creation.",
        "explanation": "Comparing creation stories across the three major religions in Ghana helps students appreciate religious diversity and find common ground."
    },
    # ─── STRAND 2: RELIGIOUS PRACTICES ───
    {
        "topic": "Prayer",
        "strand": "Religious Practices",
        "sub_strand": "Forms of Worship",
        "ges_code": "B7.2.1.1",
        "bloom": "Knowledge",
        "question_text": "How many times a day does a Muslim pray (Salat)?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Three times", "Four times", "Five times", "Six times"],
        "correct_answer": "Five times",
        "explanation": "Muslims are required to pray five times daily: Fajr (dawn), Dhuhr (noon), Asr (afternoon), Maghrib (sunset), and Isha (night)."
    },
    {
        "topic": "Prayer",
        "strand": "Religious Practices",
        "sub_strand": "Forms of Worship",
        "ges_code": "B7.2.1.1",
        "bloom": "Knowledge",
        "question_text": "The Lord's Prayer was taught by __________ to His disciples.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "Jesus",
        "explanation": "Jesus Christ taught the Lord's Prayer (Our Father) to His disciples as recorded in Matthew 6:9-13."
    },
    {
        "topic": "Religious Festivals",
        "strand": "Religious Practices",
        "sub_strand": "Religious Festivals",
        "ges_code": "B7.2.2.1",
        "bloom": "Comprehension",
        "question_text": "Which Christian festival celebrates the resurrection of Jesus Christ?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Christmas", "Easter", "Pentecost", "Good Friday"],
        "correct_answer": "Easter",
        "explanation": "Easter celebrates the resurrection of Jesus Christ from the dead on the third day after His crucifixion."
    },
    {
        "topic": "Religious Festivals",
        "strand": "Religious Practices",
        "sub_strand": "Religious Festivals",
        "ges_code": "B7.2.2.1",
        "bloom": "Comprehension",
        "question_text": "Explain the significance of the Eid-ul-Fitr festival in Islam.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Eid-ul-Fitr marks the end of Ramadan, the month of fasting. Muslims celebrate by offering special prayers, giving charity (Zakat al-Fitr), wearing new clothes, sharing meals with family and friends, and thanking Allah for the strength to complete the fast.",
        "explanation": "Eid-ul-Fitr is one of the two major Islamic festivals, marking the successful completion of the Ramadan fast."
    },
    {
        "topic": "Rites of Passage",
        "strand": "Religious Practices",
        "sub_strand": "Rites of Passage",
        "ges_code": "B8.2.3.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following is a naming ceremony practice in Ghanaian tradition?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Dropping water and alcohol on the baby's lips", "Shaving the baby's head completely", "Bathing the baby in a river", "Giving the baby solid food"],
        "correct_answer": "Dropping water and alcohol on the baby's lips",
        "explanation": "In many Ghanaian traditions, during the naming ceremony (outdooring), drops of water and alcohol are placed on the baby's lips to teach truth (water) and distinguish it from falsehood (alcohol)."
    },
    {
        "topic": "Rites of Passage",
        "strand": "Religious Practices",
        "sub_strand": "Rites of Passage",
        "ges_code": "B8.2.3.1",
        "bloom": "Analysis",
        "question_text": "Compare the naming ceremony practices in Christianity and African Traditional Religion in Ghana.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Christianity: The naming ceremony (christening/baptism) is performed in church by a minister. The baby is sprinkled with or immersed in water, godparents are chosen, and a Christian name is given. ATR: The outdooring happens on the 8th day, performed by the family elder. Water and alcohol are used symbolically, the father names the child, and there is a feast. Similarities: Both give the child an identity and welcome them into the community. Differences: Christian naming is a church sacrament; ATR naming is a family-led cultural event.",
        "explanation": "Understanding both practices helps students appreciate cultural and religious diversity in Ghana."
    },
    {
        "topic": "Sacred Places",
        "strand": "Religious Practices",
        "sub_strand": "Sacred Places",
        "ges_code": "B7.2.4.1",
        "bloom": "Knowledge",
        "question_text": "The Muslim place of worship is called a __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "mosque",
        "explanation": "Muslims worship in a mosque (masjid). Christians worship in a church, and in ATR, sacred groves and shrines serve as worship sites."
    },
    {
        "topic": "Sacred Scriptures",
        "strand": "Religious Practices",
        "sub_strand": "Sacred Writings",
        "ges_code": "B8.2.1.1",
        "bloom": "Comprehension",
        "question_text": "Which of the following is the holy book of Islam?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["The Bible", "The Torah", "The Quran", "The Vedas"],
        "correct_answer": "The Quran",
        "explanation": "The Quran is the holy book of Islam, believed to be the word of Allah revealed to Prophet Muhammad (PBUH) through Angel Jibril."
    },
    {
        "topic": "Religious Leadership",
        "strand": "Religious Practices",
        "sub_strand": "Religious Leaders",
        "ges_code": "B9.2.1.1",
        "bloom": "Application",
        "question_text": "Kofi wants to learn about traditional religious practices in his community. Which religious leader should he consult?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["A pastor", "An imam", "A traditional priest", "A catechist"],
        "correct_answer": "A traditional priest",
        "explanation": "Traditional priests (e.g., Okomfo in Akan) are the religious leaders in African Traditional Religion who can teach about traditional practices and rituals."
    },
    {
        "topic": "Pilgrimage",
        "strand": "Religious Practices",
        "sub_strand": "Pilgrimage",
        "ges_code": "B9.2.2.1",
        "bloom": "Comprehension",
        "question_text": "The Hajj pilgrimage to Mecca is one of the Five Pillars of Islam.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "True",
        "explanation": "Hajj is the fifth pillar of Islam. Every able-bodied Muslim who can afford it must perform Hajj at least once in their lifetime."
    },
    {
        "topic": "Fasting",
        "strand": "Religious Practices",
        "sub_strand": "Religious Practices in Daily Life",
        "ges_code": "B9.2.3.1",
        "bloom": "Analysis",
        "question_text": "Explain TWO reasons why fasting is important in religious life.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Fasting helps believers develop self-discipline and self-control over bodily desires. (2) It brings believers closer to God by focusing on spiritual matters rather than physical needs. (3) It teaches empathy for the poor and hungry. (4) It is an act of obedience to God's command.",
        "explanation": "Fasting is practised in Christianity (Lent), Islam (Ramadan), and some traditional religions as a form of spiritual discipline."
    },
    # ─── STRAND 3: MORAL TEACHINGS ───
    {
        "topic": "Truthfulness",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B7.3.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following is a moral value that promotes trust in society?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Greed", "Truthfulness", "Dishonesty", "Laziness"],
        "correct_answer": "Truthfulness",
        "explanation": "Truthfulness builds trust, strengthens relationships, and promotes harmony in society."
    },
    {
        "topic": "Respect",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B7.3.1.1",
        "bloom": "Application",
        "question_text": "Ama's elderly neighbour is carrying heavy bags from the market. What should Ama do to show respect for the elderly?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Ignore the neighbour and walk away", "Laugh at the neighbour", "Help the neighbour carry the bags", "Tell the neighbour to hire someone"],
        "correct_answer": "Help the neighbour carry the bags",
        "explanation": "Showing respect for the elderly includes helping them when they need assistance. This is a core Ghanaian cultural value."
    },
    {
        "topic": "Honesty",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B7.3.1.2",
        "bloom": "Analysis",
        "question_text": "Kwame finds a wallet containing GH₵500 on the school compound. The wallet has the owner's ID card. Discuss what Kwame should do and why.",
        "question_format": "essay",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "Kwame should return the wallet to the owner or hand it to school authorities. Reasons: (1) Honesty is a fundamental moral value taught by all religions, (2) Keeping someone's property is stealing, (3) The owner may need the money urgently, (4) Being honest builds a good reputation and earns trust, (5) It sets a good example for others.",
        "explanation": "Honesty requires doing the right thing even when no one is watching. All three major religions in Ghana teach the importance of honesty."
    },
    {
        "topic": "Obedience",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B7.3.1.3",
        "bloom": "Comprehension",
        "question_text": "State TWO benefits of obedience to parents and elders.",
        "question_format": "short",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "(1) It promotes peace and harmony in the family, (2) It helps children learn from the experience and wisdom of elders, (3) It earns blessings and respect from the community, (4) It builds good character and discipline.",
        "explanation": "Obedience to parents and elders is emphasised in Christianity (Ephesians 6:1), Islam (Quran 17:23-24), and African Traditional Religion."
    },
    {
        "topic": "Tolerance",
        "strand": "Moral Teachings",
        "sub_strand": "Living Together in Harmony",
        "ges_code": "B8.3.2.1",
        "bloom": "Comprehension",
        "question_text": "What does religious tolerance mean?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Forcing others to follow your religion", "Accepting and respecting other people's religious beliefs", "Ignoring all religious practices", "Believing all religions are wrong"],
        "correct_answer": "Accepting and respecting other people's religious beliefs",
        "explanation": "Religious tolerance means respecting the right of others to practise their religion, even if it differs from yours."
    },
    {
        "topic": "Patience",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B8.3.1.1",
        "bloom": "Application",
        "question_text": "Describe a situation where a student can show the moral value of patience in school.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "A student can show patience by: waiting for their turn to speak during class discussions, not getting angry when a classmate accidentally bumps into them, waiting calmly in the lunch queue, or persevering with a difficult homework without giving up.",
        "explanation": "Patience is the ability to endure difficulties calmly without complaining. It is valued in all religions and cultures."
    },
    {
        "topic": "Contentment",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B8.3.1.2",
        "bloom": "Knowledge",
        "question_text": "Contentment means being __________ with what one has.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "satisfied",
        "explanation": "Contentment is the state of being happy and satisfied with what one has, rather than always wanting more."
    },
    {
        "topic": "Good and Evil",
        "strand": "Moral Teachings",
        "sub_strand": "Consequences of Good and Bad Deeds",
        "ges_code": "B9.3.2.1",
        "bloom": "Analysis",
        "question_text": "Explain how the concept of reward and punishment for good and bad deeds is taught in Christianity and Islam.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Christianity: The Bible teaches that good deeds will be rewarded in heaven (Matthew 25:34-40) and bad deeds will be punished. Jesus taught about the Final Judgement. Islam: The Quran teaches that on the Day of Judgement (Yawm al-Qiyamah), everyone's deeds will be weighed. Good deeds lead to Paradise (Jannah) while bad deeds lead to Hell (Jahannam). Both religions teach that God is just and merciful.",
        "explanation": "Both Christianity and Islam teach accountability for one's actions, encouraging believers to do good and avoid evil."
    },
    {
        "topic": "Forgiveness",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B9.3.1.1",
        "bloom": "Synthesis",
        "question_text": "Using examples from Christianity, Islam, and African Traditional Religion, discuss the importance of forgiveness in building peaceful communities.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Christianity: Jesus taught believers to forgive seventy times seven (Matthew 18:22) and demonstrated forgiveness on the cross. Islam: Allah is described as Al-Ghafur (The Forgiving) and Muslims are encouraged to forgive others. ATR: Reconciliation rituals involve confession, forgiveness, and restoration of relationships. Importance: Forgiveness heals broken relationships, prevents revenge cycles, promotes peace, and reflects the character of God. Communities that practise forgiveness experience harmony and progress.",
        "explanation": "Forgiveness is a universal moral value emphasised across all three religions studied in the GES RME curriculum."
    },
    {
        "topic": "Commitment",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B8.3.1.3",
        "bloom": "Comprehension",
        "question_text": "A committed person is one who gives up easily when faced with challenges.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "False",
        "explanation": "Commitment means being dedicated and determined to achieve your goals. A committed person perseveres even when faced with challenges."
    },
    {
        "topic": "Kindness",
        "strand": "Moral Teachings",
        "sub_strand": "Moral Values",
        "ges_code": "B7.3.1.4",
        "bloom": "Application",
        "question_text": "Give TWO examples of how a JHS student can show kindness to classmates.",
        "question_format": "short",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "(1) Sharing learning materials with a classmate who doesn't have them, (2) Helping a sick classmate carry their bag, (3) Explaining a difficult topic to a struggling classmate, (4) Speaking kindly and not bullying others.",
        "explanation": "Kindness involves showing care and concern for others through words and actions."
    },
    # ─── STRAND 4: UNITY IN DIVERSITY ───
    {
        "topic": "Religious Tolerance",
        "strand": "Unity in Diversity",
        "sub_strand": "Religious Co-existence",
        "ges_code": "B7.4.1.1",
        "bloom": "Knowledge",
        "question_text": "Which of the following religions is NOT practised widely in Ghana?",
        "question_format": "mcq",
        "difficulty": "easy",
        "options": ["Christianity", "Islam", "Hinduism", "African Traditional Religion"],
        "correct_answer": "Hinduism",
        "explanation": "The three main religions in Ghana are Christianity, Islam, and African Traditional Religion. Hinduism is not widely practised in Ghana."
    },
    {
        "topic": "Ethnic Groups",
        "strand": "Unity in Diversity",
        "sub_strand": "Cultural Diversity in Ghana",
        "ges_code": "B7.4.2.1",
        "bloom": "Knowledge",
        "question_text": "The largest ethnic group in Ghana is the __________.",
        "question_format": "fill",
        "difficulty": "easy",
        "options": [],
        "correct_answer": "Akan",
        "explanation": "The Akan ethnic group is the largest in Ghana, making up about 47.5% of the population. It includes sub-groups like Ashanti, Fante, Akyem, and Bono."
    },
    {
        "topic": "National Unity",
        "strand": "Unity in Diversity",
        "sub_strand": "Promoting National Unity",
        "ges_code": "B8.4.1.1",
        "bloom": "Comprehension",
        "question_text": "State THREE ways by which Ghana promotes national unity despite its diverse ethnic and religious groups.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) The use of English as an official language for communication across ethnic groups, (2) National festivals and holidays like Independence Day that unite all Ghanaians, (3) Inter-marriage between different ethnic groups, (4) The national motto 'Freedom and Justice' and national symbols that represent all Ghanaians, (5) The Chieftaincy institution and National House of Chiefs.",
        "explanation": "Ghana is a multi-ethnic and multi-religious country that uses various strategies to promote unity and peaceful co-existence."
    },
    {
        "topic": "Conflict Resolution",
        "strand": "Unity in Diversity",
        "sub_strand": "Peaceful Co-existence",
        "ges_code": "B8.4.2.1",
        "bloom": "Application",
        "question_text": "Two students from different ethnic groups are fighting over which tribe is superior. As a prefect, how would you resolve this conflict?",
        "question_format": "essay",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "As a prefect, I would: (1) Separate the students and calm them down, (2) Listen to both sides fairly, (3) Explain that no tribe is superior to another — all tribes contribute to Ghana's rich culture, (4) Remind them of Ghana's motto 'Freedom and Justice' and the importance of unity, (5) Encourage them to learn about each other's culture, (6) Report to a teacher if the conflict is serious. I would use mediation skills to help them understand and respect their differences.",
        "explanation": "Conflict resolution is an important life skill. Students should learn to resolve disputes peacefully and respect cultural diversity."
    },
    {
        "topic": "Inter-religious Dialogue",
        "strand": "Unity in Diversity",
        "sub_strand": "Religious Co-existence",
        "ges_code": "B9.4.1.1",
        "bloom": "Analysis",
        "question_text": "Explain why inter-religious dialogue is important for national development in Ghana.",
        "question_format": "short",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "Inter-religious dialogue is important because: (1) It promotes understanding and reduces religious conflicts, (2) It helps different religious groups work together for national development, (3) It creates an atmosphere of peace and tolerance necessary for economic growth, (4) It prevents religious extremism and radicalisation.",
        "explanation": "Ghana is known for its religious tolerance. Inter-religious dialogue helps maintain this peace and promotes national development."
    },
    {
        "topic": "Cultural Practices",
        "strand": "Unity in Diversity",
        "sub_strand": "Cultural Diversity in Ghana",
        "ges_code": "B7.4.2.2",
        "bloom": "Comprehension",
        "question_text": "Which of the following is a cultural festival of the Ga people of Ghana?",
        "question_format": "mcq",
        "difficulty": "medium",
        "options": ["Hogbetsotso", "Homowo", "Akwasidae", "Damba"],
        "correct_answer": "Homowo",
        "explanation": "Homowo is the harvest festival of the Ga people of Accra. Hogbetsotso is Anlo-Ewe, Akwasidae is Ashanti, and Damba is celebrated by the Dagomba."
    },
    {
        "topic": "National Symbols",
        "strand": "Unity in Diversity",
        "sub_strand": "Promoting National Unity",
        "ges_code": "B8.4.1.2",
        "bloom": "Application",
        "question_text": "Explain how the Ghana coat of arms promotes national unity.",
        "question_format": "short",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "The coat of arms features symbols that unite all Ghanaians: the cocoa tree represents agricultural wealth, the gold mine represents mineral wealth, the eagle represents protection, and the two eagles holding the shield represent the strength of the nation. The motto 'Freedom and Justice' applies to all citizens regardless of ethnicity or religion.",
        "explanation": "National symbols serve as unifying identifiers that all citizens can rally around regardless of their ethnic or religious background."
    },
    {
        "topic": "Human Rights",
        "strand": "Unity in Diversity",
        "sub_strand": "Rights and Responsibilities",
        "ges_code": "B9.4.2.1",
        "bloom": "Synthesis",
        "question_text": "Discuss how respect for human rights can promote unity in a diverse society like Ghana.",
        "question_format": "essay",
        "difficulty": "hard",
        "options": [],
        "correct_answer": "When human rights are respected: (1) All citizens feel valued regardless of ethnicity, religion, or gender, (2) Freedom of religion and worship allows peaceful co-existence, (3) Right to education ensures all ethnic groups have equal opportunities, (4) Freedom of expression allows diverse views to be heard, (5) The right to non-discrimination prevents marginalisation of minority groups. When people's rights are protected, they feel included in the nation's progress, reducing conflict and promoting unity.",
        "explanation": "Human rights form the foundation for peaceful co-existence in diverse societies. Ghana's 1992 Constitution protects fundamental human rights."
    },
    {
        "topic": "Chieftaincy",
        "strand": "Unity in Diversity",
        "sub_strand": "Traditional Authority",
        "ges_code": "B9.4.3.1",
        "bloom": "Comprehension",
        "question_text": "The chieftaincy institution in Ghana helps to preserve the cultural heritage of various ethnic groups.",
        "question_format": "truefalse",
        "difficulty": "easy",
        "options": ["True", "False"],
        "correct_answer": "True",
        "explanation": "Chiefs play a vital role in preserving customs, traditions, and cultural practices. The National House of Chiefs advises the government on traditional matters."
    },
    {
        "topic": "Religious Tolerance",
        "strand": "Unity in Diversity",
        "sub_strand": "Religious Co-existence",
        "ges_code": "B8.4.1.3",
        "bloom": "Analysis",
        "question_text": "Identify THREE factors that contribute to religious peace in Ghana.",
        "question_format": "short",
        "difficulty": "medium",
        "options": [],
        "correct_answer": "(1) Interfaith marriages and friendships between people of different religions, (2) The National Peace Council that mediates religious disputes, (3) Constitutional protection of freedom of worship, (4) Joint participation in national celebrations regardless of religion, (5) Inter-religious organisations that promote dialogue.",
        "explanation": "Ghana is globally recognised for its religious tolerance and peaceful co-existence among Christians, Muslims, and Traditional worshippers."
    },
]
