# ─────────────────────────────────────────────────────────────────────────────
# JHS Integrated Science BECE-Aligned Question Bank — 50 Items
# NaCCA Standards-Based Curriculum (Basic 7-9)
#
# Strands:
#   1. Diversity of Matter
#   2. Cycles
#   3. Systems
#   4. Forces and Energy
#   5. Humans and the Environment
#
# Distribution:
#   Bloom's  → K 12, C 10, A 14, An 8, S/E 6
#   Format   → mcq 30, fill 8, short 8, truefalse 4
#   Difficulty → easy 15, medium 22, hard 13
# ─────────────────────────────────────────────────────────────────────────────

SCIENCE_QUESTION_BANK = [
    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 1: DIVERSITY OF MATTER (10 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Materials',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Living and Non-living Things',
        'ges_code': 'B7.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Which of the following is a characteristic of all living things?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) They can move from place to place', 'B) They respire', 'C) They are green in colour', 'D) They all have legs'],
        'correct_answer': 'B',
        'explanation': 'All living things respire (exchange gases). Not all move locomotively, are green, or have legs.',
    },
    {
        'topic': 'Materials',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Materials',
        'ges_code': 'B7.1.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Metals are generally good conductors of heat. Which property explains this?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) They are shiny', 'B) They have free-moving electrons', 'C) They are heavy', 'D) They are solid at room temperature'],
        'correct_answer': 'B',
        'explanation': 'Free-moving electrons in metals transfer kinetic energy quickly, making them good conductors.',
    },
    {
        'topic': 'Mixtures',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Mixtures',
        'ges_code': 'B8.1.3.1',
        'bloom': 'Application',
        'question_text': 'Which method would you use to separate a mixture of sand and salt?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Filtration only', 'B) Dissolving in water, filtering, then evaporating', 'C) Using a magnet', 'D) Distillation'],
        'correct_answer': 'B',
        'explanation': 'Dissolve salt in water, filter out sand, then evaporate to recover salt crystals.',
    },
    {
        'topic': 'Acids and Bases',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Acids and Bases',
        'ges_code': 'B9.1.4.1',
        'bloom': 'Knowledge',
        'question_text': 'Blue litmus paper turns red in the presence of:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'acid',
        'explanation': 'Acids turn blue litmus paper red. Bases turn red litmus paper blue.',
    },
    {
        'topic': 'Acids and Bases',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Acids and Bases',
        'ges_code': 'B9.1.4.2',
        'bloom': 'Comprehension',
        'question_text': 'A substance with pH 3 is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) A strong base', 'B) Neutral', 'C) A weak acid', 'D) A strong acid'],
        'correct_answer': 'D',
        'explanation': 'pH 3 is well below 7, indicating a strong acid. pH 7 is neutral; above 7 is basic.',
    },
    {
        'topic': 'Matter and Change',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Physical and Chemical Changes',
        'ges_code': 'B8.1.5.1',
        'bloom': 'Analysis',
        'question_text': 'Which of the following is a chemical change?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Melting ice', 'B) Dissolving sugar in water', 'C) Rusting of iron', 'D) Breaking a glass'],
        'correct_answer': 'C',
        'explanation': 'Rusting forms a new substance (iron oxide) — a chemical change. The others are physical changes.',
    },
    {
        'topic': 'States of Matter',
        'strand': 'Diversity of Matter',
        'sub_strand': 'States of Matter',
        'ges_code': 'B7.1.6.1',
        'bloom': 'Knowledge',
        'question_text': 'The process of a liquid changing to a gas is called:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'evaporation',
        'explanation': 'Evaporation is the process where a liquid changes to a gas, usually at the surface.',
    },
    {
        'topic': 'States of Matter',
        'strand': 'Diversity of Matter',
        'sub_strand': 'States of Matter',
        'ges_code': 'B7.1.6.2',
        'bloom': 'Comprehension',
        'question_text': 'True or False: In solids, particles are closely packed and vibrate in fixed positions.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Solid particles have strong intermolecular forces, keeping them closely packed and vibrating in place.',
    },
    {
        'topic': 'Elements and Compounds',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Elements and Compounds',
        'ges_code': 'B9.1.7.1',
        'bloom': 'Knowledge',
        'question_text': 'The chemical symbol for sodium is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) S', 'B) So', 'C) Na', 'D) Sd'],
        'correct_answer': 'C',
        'explanation': 'Na comes from the Latin name "Natrium" for sodium.',
    },
    {
        'topic': 'Elements and Compounds',
        'strand': 'Diversity of Matter',
        'sub_strand': 'Elements and Compounds',
        'ges_code': 'B9.1.7.2',
        'bloom': 'Application',
        'question_text': 'Water (H₂O) is classified as a compound because:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) It is a liquid', 'B) It contains two different elements chemically combined', 'C) It is found in nature', 'D) It can be poured'],
        'correct_answer': 'B',
        'explanation': 'A compound is a substance made of two or more elements chemically bonded together.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 2: CYCLES (8 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Water Cycle',
        'strand': 'Cycles',
        'sub_strand': 'Water Cycle',
        'ges_code': 'B7.2.1.1',
        'bloom': 'Comprehension',
        'question_text': 'In the water cycle, what process turns water vapour into liquid water?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Evaporation', 'B) Condensation', 'C) Transpiration', 'D) Precipitation'],
        'correct_answer': 'B',
        'explanation': 'Condensation is the process where water vapour cools and changes back into liquid water.',
    },
    {
        'topic': 'Life Cycles',
        'strand': 'Cycles',
        'sub_strand': 'Life Cycles of Organisms',
        'ges_code': 'B7.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The correct sequence of a mosquito\'s life cycle is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Egg → Pupa → Larva → Adult', 'B) Egg → Larva → Pupa → Adult', 'C) Larva → Egg → Pupa → Adult', 'D) Adult → Egg → Pupa → Larva'],
        'correct_answer': 'B',
        'explanation': 'Mosquitoes undergo complete metamorphosis: Egg → Larva → Pupa → Adult.',
    },
    {
        'topic': 'Crop Production',
        'strand': 'Cycles',
        'sub_strand': 'Crop Husbandry',
        'ges_code': 'B8.2.3.1',
        'bloom': 'Application',
        'question_text': 'Which farming practice helps to maintain soil fertility?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Mono-cropping every year', 'B) Bush burning', 'C) Crop rotation', 'D) Removing all organic matter'],
        'correct_answer': 'C',
        'explanation': 'Crop rotation alternates different crops to prevent nutrient depletion and break pest cycles.',
    },
    {
        'topic': 'Reproduction in Plants',
        'strand': 'Cycles',
        'sub_strand': 'Plant Reproduction',
        'ges_code': 'B8.2.4.1',
        'bloom': 'Knowledge',
        'question_text': 'The part of a flower that produces pollen is the:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'anther',
        'explanation': 'The anther, part of the stamen, produces pollen grains containing male gametes.',
    },
    {
        'topic': 'Reproduction in Humans',
        'strand': 'Cycles',
        'sub_strand': 'Human Reproduction',
        'ges_code': 'B9.2.5.1',
        'bloom': 'Comprehension',
        'question_text': 'The process by which a sperm cell fuses with an egg cell is called:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'fertilisation',
        'explanation': 'Fertilisation occurs when a sperm cell fuses with an egg cell to form a zygote.',
    },
    {
        'topic': 'Reproduction in Humans',
        'strand': 'Cycles',
        'sub_strand': 'Human Reproduction',
        'ges_code': 'B9.2.5.2',
        'bloom': 'Analysis',
        'question_text': 'Adolescent boys experience voice deepening because of:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Increased oestrogen', 'B) Increased testosterone', 'C) Decreased growth hormone', 'D) Increased insulin'],
        'correct_answer': 'B',
        'explanation': 'Testosterone causes the larynx to grow, making the vocal cords longer and the voice deeper.',
    },
    {
        'topic': 'Carbon Cycle',
        'strand': 'Cycles',
        'sub_strand': 'Nutrient Cycling',
        'ges_code': 'B9.2.6.1',
        'bloom': 'Comprehension',
        'question_text': 'Plants remove carbon dioxide from the atmosphere through:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Respiration', 'B) Photosynthesis', 'C) Transpiration', 'D) Decomposition'],
        'correct_answer': 'B',
        'explanation': 'During photosynthesis, plants absorb CO₂ and convert it to glucose using sunlight.',
    },
    {
        'topic': 'Menstrual Cycle',
        'strand': 'Cycles',
        'sub_strand': 'Human Reproduction',
        'ges_code': 'B9.2.5.3',
        'bloom': 'Knowledge',
        'question_text': 'The average length of the menstrual cycle is approximately:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) 14 days', 'B) 21 days', 'C) 28 days', 'D) 35 days'],
        'correct_answer': 'C',
        'explanation': 'The average menstrual cycle lasts about 28 days, though it can vary between individuals.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 3: SYSTEMS (8 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'The Human Body',
        'strand': 'Systems',
        'sub_strand': 'The Human Body Systems',
        'ges_code': 'B7.3.1.1',
        'bloom': 'Knowledge',
        'question_text': 'The organ responsible for pumping blood around the body is the:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'heart',
        'explanation': 'The heart is a muscular organ that pumps blood through the circulatory system.',
    },
    {
        'topic': 'Digestive System',
        'strand': 'Systems',
        'sub_strand': 'The Human Body Systems',
        'ges_code': 'B8.3.1.2',
        'bloom': 'Comprehension',
        'question_text': 'Digestion of starch begins in the:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Stomach', 'B) Mouth', 'C) Small intestine', 'D) Large intestine'],
        'correct_answer': 'B',
        'explanation': 'Salivary amylase in the mouth begins breaking down starch into maltose.',
    },
    {
        'topic': 'The Solar System',
        'strand': 'Systems',
        'sub_strand': 'The Solar System',
        'ges_code': 'B7.3.2.1',
        'bloom': 'Knowledge',
        'question_text': 'Which planet is closest to the Sun?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Venus', 'B) Earth', 'C) Mercury', 'D) Mars'],
        'correct_answer': 'C',
        'explanation': 'Mercury is the first planet from the Sun, at an average distance of about 58 million km.',
    },
    {
        'topic': 'Respiratory System',
        'strand': 'Systems',
        'sub_strand': 'The Human Body Systems',
        'ges_code': 'B8.3.1.3',
        'bloom': 'Application',
        'question_text': 'During inhalation, the diaphragm:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Moves up and relaxes', 'B) Contracts and moves down', 'C) Stays in the same position', 'D) Moves sideways'],
        'correct_answer': 'B',
        'explanation': 'When the diaphragm contracts, it flattens and moves down, increasing lung volume and drawing air in.',
    },
    {
        'topic': 'Ecosystem',
        'strand': 'Systems',
        'sub_strand': 'Ecosystem',
        'ges_code': 'B8.3.3.1',
        'bloom': 'Comprehension',
        'question_text': 'In a food chain: Grass → Grasshopper → Frog → Snake. The frog is a:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Producer', 'B) Primary consumer', 'C) Secondary consumer', 'D) Tertiary consumer'],
        'correct_answer': 'C',
        'explanation': 'The frog eats the grasshopper (primary consumer), making it a secondary consumer.',
    },
    {
        'topic': 'Circulatory System',
        'strand': 'Systems',
        'sub_strand': 'The Human Body Systems',
        'ges_code': 'B9.3.1.4',
        'bloom': 'Analysis',
        'question_text': 'Arteries differ from veins because arteries:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Carry deoxygenated blood only', 'B) Have valves throughout their length', 'C) Have thick, muscular walls and carry blood away from the heart', 'D) Are always closer to the skin surface'],
        'correct_answer': 'C',
        'explanation': 'Arteries have thick, elastic walls to withstand high pressure and carry blood away from the heart.',
    },
    {
        'topic': 'Excretory System',
        'strand': 'Systems',
        'sub_strand': 'The Human Body Systems',
        'ges_code': 'B9.3.1.5',
        'bloom': 'Knowledge',
        'question_text': 'The main organ of excretion that produces urine is the:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'kidney',
        'explanation': 'The kidneys filter blood and remove waste products as urine.',
    },
    {
        'topic': 'Nervous System',
        'strand': 'Systems',
        'sub_strand': 'The Human Body Systems',
        'ges_code': 'B9.3.1.6',
        'bloom': 'Application',
        'question_text': 'A person accidentally touches a hot pan and quickly pulls their hand away. This is an example of:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Voluntary action', 'B) Reflex action', 'C) Learned behaviour', 'D) Conditioned response'],
        'correct_answer': 'B',
        'explanation': 'Reflex actions are automatic, rapid responses to stimuli that do not involve conscious thought.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 4: FORCES AND ENERGY (12 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Forms of Energy',
        'strand': 'Forces and Energy',
        'sub_strand': 'Forms of Energy',
        'ges_code': 'B7.4.1.1',
        'bloom': 'Knowledge',
        'question_text': 'The energy stored in food is called:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Kinetic energy', 'B) Light energy', 'C) Chemical energy', 'D) Sound energy'],
        'correct_answer': 'C',
        'explanation': 'Food stores chemical energy which is released during digestion and cellular respiration.',
    },
    {
        'topic': 'Electricity',
        'strand': 'Forces and Energy',
        'sub_strand': 'Electricity',
        'ges_code': 'B8.4.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The SI unit of electric current is the:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'ampere',
        'explanation': 'Electric current is measured in amperes (A), named after André-Marie Ampère.',
    },
    {
        'topic': 'Electricity',
        'strand': 'Forces and Energy',
        'sub_strand': 'Electricity',
        'ges_code': 'B8.4.2.2',
        'bloom': 'Application',
        'question_text': 'In a simple electric circuit, the function of a switch is to:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Increase the current', 'B) Store energy', 'C) Open or close the circuit', 'D) Convert energy'],
        'correct_answer': 'C',
        'explanation': 'A switch controls the flow of current by making (closing) or breaking (opening) the circuit.',
    },
    {
        'topic': 'Light',
        'strand': 'Forces and Energy',
        'sub_strand': 'Light Energy',
        'ges_code': 'B8.4.3.1',
        'bloom': 'Comprehension',
        'question_text': 'True or False: Light travels in straight lines.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Light travels in straight lines (rectilinear propagation), which explains the formation of shadows.',
    },
    {
        'topic': 'Light',
        'strand': 'Forces and Energy',
        'sub_strand': 'Light Energy',
        'ges_code': 'B9.4.3.2',
        'bloom': 'Application',
        'question_text': 'When light passes from air into water, it bends. This phenomenon is called:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Reflection', 'B) Refraction', 'C) Diffraction', 'D) Absorption'],
        'correct_answer': 'B',
        'explanation': 'Refraction is the bending of light when it passes from one medium to another of different density.',
    },
    {
        'topic': 'Sound',
        'strand': 'Forces and Energy',
        'sub_strand': 'Sound Energy',
        'ges_code': 'B7.4.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Sound cannot travel through:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Air', 'B) Water', 'C) A vacuum', 'D) Steel'],
        'correct_answer': 'C',
        'explanation': 'Sound requires a medium (solid, liquid, or gas) to travel; it cannot travel through a vacuum.',
    },
    {
        'topic': 'Simple Machines',
        'strand': 'Forces and Energy',
        'sub_strand': 'Simple Machines',
        'ges_code': 'B8.4.5.1',
        'bloom': 'Application',
        'question_text': 'A wheelbarrow is an example of which class of lever?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) First class', 'B) Second class', 'C) Third class', 'D) Not a lever'],
        'correct_answer': 'B',
        'explanation': 'In a wheelbarrow, the load is between the fulcrum (wheel) and effort (handles) — second class lever.',
    },
    {
        'topic': 'Simple Machines',
        'strand': 'Forces and Energy',
        'sub_strand': 'Simple Machines',
        'ges_code': 'B8.4.5.2',
        'bloom': 'Synthesis',
        'question_text': 'Explain why it is easier to push a heavy box up a long ramp than to lift it straight up.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'A ramp (inclined plane) reduces the effort needed by increasing the distance over which the force is applied, so less force is required at any point.',
        'explanation': 'An inclined plane trades distance for force — the longer the ramp, the less effort needed.',
    },
    {
        'topic': 'Heat Energy',
        'strand': 'Forces and Energy',
        'sub_strand': 'Heat Transfer',
        'ges_code': 'B9.4.6.1',
        'bloom': 'Analysis',
        'question_text': 'A metal spoon in hot soup becomes hot quickly while a wooden spoon does not. This is because:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Metal is heavier than wood', 'B) Metal is a better conductor of heat than wood', 'C) Wood repels heat', 'D) The spoon is smaller'],
        'correct_answer': 'B',
        'explanation': 'Metals conduct heat much faster than wood due to free electrons. Wood is an insulator.',
    },
    {
        'topic': 'Forces',
        'strand': 'Forces and Energy',
        'sub_strand': 'Types of Forces',
        'ges_code': 'B7.4.7.1',
        'bloom': 'Knowledge',
        'question_text': 'The force that opposes motion between two surfaces in contact is called:',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'friction',
        'explanation': 'Friction acts between surfaces in contact and opposes the direction of motion.',
    },
    {
        'topic': 'Forces',
        'strand': 'Forces and Energy',
        'sub_strand': 'Types of Forces',
        'ges_code': 'B7.4.7.2',
        'bloom': 'Application',
        'question_text': 'True or False: Gravitational force pulls objects towards the centre of the Earth.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Gravity is a force that attracts objects with mass towards each other; on Earth it pulls towards the centre.',
    },
    {
        'topic': 'Density',
        'strand': 'Forces and Energy',
        'sub_strand': 'Density and Floating',
        'ges_code': 'B9.4.8.1',
        'bloom': 'Application',
        'question_text': 'A block of wood floats on water because:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) It is flat', 'B) It is less dense than water', 'C) It has no mass', 'D) Water pushes it sideways'],
        'correct_answer': 'B',
        'explanation': 'Objects float when their density is less than the density of the liquid they are placed in.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 5: HUMANS AND THE ENVIRONMENT (12 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Personal Hygiene',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Personal Hygiene and Sanitation',
        'ges_code': 'B7.5.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Which of the following diseases is caused by drinking contaminated water?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Malaria', 'B) Cholera', 'C) Measles', 'D) Asthma'],
        'correct_answer': 'B',
        'explanation': 'Cholera is caused by the bacterium Vibrio cholerae, transmitted through contaminated water.',
    },
    {
        'topic': 'Diseases',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Diseases',
        'ges_code': 'B8.5.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Malaria is transmitted to humans through the bite of:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Housefly', 'B) Female Anopheles mosquito', 'C) Tsetse fly', 'D) Cockroach'],
        'correct_answer': 'B',
        'explanation': 'The female Anopheles mosquito transmits the Plasmodium parasite that causes malaria.',
    },
    {
        'topic': 'Diseases',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Diseases',
        'ges_code': 'B8.5.2.2',
        'bloom': 'Application',
        'question_text': 'Which of these is the most effective way to prevent malaria?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Eating healthy food', 'B) Sleeping under an insecticide-treated net', 'C) Boiling drinking water', 'D) Exercising regularly'],
        'correct_answer': 'B',
        'explanation': 'Insecticide-treated nets prevent mosquito bites while sleeping, the primary transmission time.',
    },
    {
        'topic': 'Nutrition',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Food and Nutrition',
        'ges_code': 'B7.5.3.1',
        'bloom': 'Knowledge',
        'question_text': 'Which class of food is the main source of energy?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Proteins', 'B) Vitamins', 'C) Carbohydrates', 'D) Minerals'],
        'correct_answer': 'C',
        'explanation': 'Carbohydrates (rice, bread, yam) are the body\'s primary and preferred source of energy.',
    },
    {
        'topic': 'Nutrition',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Food and Nutrition',
        'ges_code': 'B7.5.3.2',
        'bloom': 'Application',
        'question_text': 'A child suffering from kwashiorkor most likely lacks sufficient:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Carbohydrates', 'B) Proteins', 'C) Fats', 'D) Water'],
        'correct_answer': 'B',
        'explanation': 'Kwashiorkor is caused by severe protein deficiency, common in children with carbohydrate-rich but protein-poor diets.',
    },
    {
        'topic': 'Environmental Pollution',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Pollution',
        'ges_code': 'B9.5.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Burning fossil fuels contributes to air pollution by releasing:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Oxygen', 'B) Carbon dioxide and sulphur dioxide', 'C) Nitrogen only', 'D) Water vapour only'],
        'correct_answer': 'B',
        'explanation': 'Burning fossil fuels releases CO₂ (greenhouse gas) and SO₂ (causes acid rain) into the atmosphere.',
    },
    {
        'topic': 'Environmental Pollution',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Pollution',
        'ges_code': 'B9.5.4.2',
        'bloom': 'Synthesis',
        'question_text': 'Suggest two ways a community can reduce water pollution.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Proper disposal of waste (not dumping into rivers) and treating industrial effluents before releasing into water bodies.',
        'explanation': 'Preventing waste from entering water sources and treating wastewater are key pollution control strategies.',
    },
    {
        'topic': 'Conservation',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Conservation of Natural Resources',
        'ges_code': 'B9.5.5.1',
        'bloom': 'Analysis',
        'question_text': 'Deforestation leads to all of the following EXCEPT:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Soil erosion', 'B) Loss of biodiversity', 'C) Increased oxygen production', 'D) Climate change'],
        'correct_answer': 'C',
        'explanation': 'Deforestation decreases oxygen production (fewer trees). It causes erosion, biodiversity loss, and climate change.',
    },
    {
        'topic': 'Adolescent Health',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Adolescent Reproductive Health',
        'ges_code': 'B8.5.6.1',
        'bloom': 'Comprehension',
        'question_text': 'True or False: Abstinence is the most effective way for adolescents to prevent sexually transmitted infections (STIs).',
        'question_format': 'truefalse',
        'difficulty': 'medium',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Abstinence (not engaging in sexual activity) is 100% effective in preventing STIs and pregnancy.',
    },
    {
        'topic': 'Drug Abuse',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Substance Abuse',
        'ges_code': 'B9.5.7.1',
        'bloom': 'Analysis',
        'question_text': 'Which of the following is a long-term effect of alcohol abuse?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Improved memory', 'B) Liver damage (cirrhosis)', 'C) Stronger bones', 'D) Better eyesight'],
        'correct_answer': 'B',
        'explanation': 'Chronic alcohol abuse damages the liver, leading to cirrhosis, and impairs brain function.',
    },
    {
        'topic': 'First Aid',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Safety and First Aid',
        'ges_code': 'B7.5.8.1',
        'bloom': 'Application',
        'question_text': 'The first thing to do when someone gets a minor burn is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Apply butter', 'B) Run cool water over the burn for at least 10 minutes', 'C) Cover it with a dry cloth immediately', 'D) Pop any blisters'],
        'correct_answer': 'B',
        'explanation': 'Cool running water reduces the temperature of the burn, minimising tissue damage.',
    },
    {
        'topic': 'Sanitation',
        'strand': 'Humans and the Environment',
        'sub_strand': 'Personal Hygiene and Sanitation',
        'ges_code': 'B7.5.1.2',
        'bloom': 'Synthesis',
        'question_text': 'Explain why hand washing with soap is important after using the toilet.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Soap removes germs and bacteria from the hands that can cause diseases like diarrhoea and cholera if transferred to food or the mouth.',
        'explanation': 'Hand washing breaks the faecal-oral transmission route of many infectious diseases.',
    },
]
