# ─────────────────────────────────────────────────────────────────────────────
# JHS Social Studies BECE-Aligned Question Bank — 50 Items
# NaCCA Standards-Based Curriculum (Basic 7-9)
#
# Strands:
#   1. Environment
#   2. Governance, Politics and Stability
#   3. Socio-Economic Development
#   4. Our Nationhood
#
# Distribution:
#   Bloom's  → K 12, C 12, A 12, An 8, S/E 6
#   Format   → mcq 30, fill 6, short 10, truefalse 4
#   Difficulty → easy 15, medium 22, hard 13
# ─────────────────────────────────────────────────────────────────────────────

SOCIAL_STUDIES_QUESTION_BANK = [
    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 1: ENVIRONMENT (12 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'The Environment',
        'strand': 'Environment',
        'sub_strand': 'Physical Environment',
        'ges_code': 'B7.1.1.1',
        'bloom': 'Knowledge',
        'question_text': 'The layer of the atmosphere closest to the surface of the earth is the:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Stratosphere', 'B) Troposphere', 'C) Mesosphere', 'D) Thermosphere'],
        'correct_answer': 'B',
        'explanation': 'The troposphere extends from the earth\'s surface to about 12 km up and is where weather occurs.',
    },
    {
        'topic': 'Map Reading',
        'strand': 'Environment',
        'sub_strand': 'Map Work',
        'ges_code': 'B7.1.2.1',
        'bloom': 'Application',
        'question_text': 'On a map with a scale of 1:50,000, a distance of 4 cm represents:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) 500 m', 'B) 2 km', 'C) 20 km', 'D) 200 km'],
        'correct_answer': 'B',
        'explanation': '4 cm × 50,000 = 200,000 cm = 2,000 m = 2 km.',
    },
    {
        'topic': 'Climate and Vegetation',
        'strand': 'Environment',
        'sub_strand': 'Climate',
        'ges_code': 'B8.1.3.1',
        'bloom': 'Knowledge',
        'question_text': 'The two main seasons experienced in Ghana are:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Summer and Winter', 'B) Rainy and Dry (Harmattan)', 'C) Spring and Autumn', 'D) Hot and Cold'],
        'correct_answer': 'B',
        'explanation': 'Ghana, being close to the equator, has a wet (rainy) season and a dry (harmattan) season.',
    },
    {
        'topic': 'Climate and Vegetation',
        'strand': 'Environment',
        'sub_strand': 'Vegetation',
        'ges_code': 'B8.1.3.2',
        'bloom': 'Comprehension',
        'question_text': 'The savanna vegetation zone in Ghana is characterised by:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Tall trees with thick canopy', 'B) Short grasses and scattered drought-resistant trees', 'C) Mangrove swamps', 'D) Dense equatorial rainforest'],
        'correct_answer': 'B',
        'explanation': 'The savanna is grassland with few trees, adapted to long dry periods and seasonal rainfall.',
    },
    {
        'topic': 'Population',
        'strand': 'Environment',
        'sub_strand': 'Population',
        'ges_code': 'B9.1.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Rapid population growth in a country can lead to:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Reduced pressure on resources', 'B) Strain on health, education and social services', 'C) Reduced unemployment', 'D) No significant effects'],
        'correct_answer': 'B',
        'explanation': 'Rapid population growth increases demand for schools, hospitals, food, and jobs, often exceeding government capacity.',
    },
    {
        'topic': 'Environmental Degradation',
        'strand': 'Environment',
        'sub_strand': 'Environmental Issues',
        'ges_code': 'B9.1.5.1',
        'bloom': 'Analysis',
        'question_text': 'Illegal mining (galamsey) in Ghana destroys water bodies primarily because:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) It makes the water cleaner', 'B) Chemicals like mercury contaminate rivers and streams', 'C) It increases fish population', 'D) It creates new water sources'],
        'correct_answer': 'B',
        'explanation': 'Galamsey uses mercury and cyanide which contaminate water, making it unsafe for drinking and killing aquatic life.',
    },
    {
        'topic': 'The Environment',
        'strand': 'Environment',
        'sub_strand': 'Physical Environment',
        'ges_code': 'B7.1.1.2',
        'bloom': 'Knowledge',
        'question_text': 'The major rivers of Ghana include the Volta, Pra, Ankobra, and:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'Tano',
        'explanation': 'The five major rivers of Ghana are Volta, Pra, Ankobra, Tano, and Densu/Oti.',
    },
    {
        'topic': 'Natural Resources',
        'strand': 'Environment',
        'sub_strand': 'Natural Resources',
        'ges_code': 'B8.1.6.1',
        'bloom': 'Comprehension',
        'question_text': 'True or False: Gold, bauxite, and cocoa are all important natural resources of Ghana.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Ghana is a major exporter of gold, has significant bauxite reserves, and is the world\'s second-largest cocoa producer.',
    },
    {
        'topic': 'Environmental Conservation',
        'strand': 'Environment',
        'sub_strand': 'Conservation',
        'ges_code': 'B9.1.7.1',
        'bloom': 'Application',
        'question_text': 'Which of the following is a sustainable practice for protecting the environment?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Cutting all trees for farming', 'B) Afforestation and tree planting', 'C) Dumping waste in rivers', 'D) Burning waste in the open'],
        'correct_answer': 'B',
        'explanation': 'Afforestation replaces trees lost to deforestation, protecting soil and maintaining the carbon cycle.',
    },
    {
        'topic': 'Settlement',
        'strand': 'Environment',
        'sub_strand': 'Settlement',
        'ges_code': 'B7.1.8.1',
        'bloom': 'Comprehension',
        'question_text': 'People settle near rivers mainly because:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Rivers provide entertainment', 'B) Rivers provide water for drinking, farming, and transportation', 'C) Rivers are always clean', 'D) Rivers keep the area cool'],
        'correct_answer': 'B',
        'explanation': 'Rivers are essential for water supply, irrigation, fishing, and transportation, attracting settlements.',
    },
    {
        'topic': 'Map Reading',
        'strand': 'Environment',
        'sub_strand': 'Map Work',
        'ges_code': 'B7.1.2.2',
        'bloom': 'Knowledge',
        'question_text': 'The four cardinal points of a compass are:',
        'question_format': 'short',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'North, South, East, West',
        'explanation': 'The four cardinal directions form the primary divisions of a compass.',
    },
    {
        'topic': 'Environmental Degradation',
        'strand': 'Environment',
        'sub_strand': 'Environmental Issues',
        'ges_code': 'B9.1.5.2',
        'bloom': 'Synthesis',
        'question_text': 'Suggest two measures the government can take to reduce the effects of climate change in Ghana.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Promote renewable energy (solar, wind) and enforce strict laws against deforestation and illegal mining.',
        'explanation': 'Reducing fossil fuel use and protecting forests are key strategies for climate change mitigation.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 2: GOVERNANCE, POLITICS AND STABILITY (14 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Government',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Types of Government',
        'ges_code': 'B7.2.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Ghana practices which form of government?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Monarchy', 'B) Constitutional democracy', 'C) Military dictatorship', 'D) Communist state'],
        'correct_answer': 'B',
        'explanation': 'Ghana is a constitutional democracy governed by the 1992 Constitution with regular elections.',
    },
    {
        'topic': 'Arms of Government',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Arms of Government',
        'ges_code': 'B8.2.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The three arms of government in Ghana are the Executive, Legislature, and:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'Judiciary',
        'explanation': 'The Judiciary interprets laws, the Legislature makes laws, and the Executive implements laws.',
    },
    {
        'topic': 'Arms of Government',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Arms of Government',
        'ges_code': 'B8.2.2.2',
        'bloom': 'Comprehension',
        'question_text': 'The primary function of Parliament (Legislature) in Ghana is to:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Execute government policies', 'B) Interpret the constitution', 'C) Make and pass laws', 'D) Arrest criminals'],
        'correct_answer': 'C',
        'explanation': 'Parliament\'s primary role is law-making, including debating and passing bills into law.',
    },
    {
        'topic': 'The Constitution',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'The Constitution',
        'ges_code': 'B9.2.3.1',
        'bloom': 'Comprehension',
        'question_text': 'The 1992 Constitution of Ghana guarantees fundamental human rights such as:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Right to own another person', 'B) Right to life, liberty, and freedom of speech', 'C) Right to avoid paying taxes', 'D) Right to disobey all laws'],
        'correct_answer': 'B',
        'explanation': 'Chapter 5 of the 1992 Constitution outlines fundamental human rights including life, liberty, and free speech.',
    },
    {
        'topic': 'Citizenship',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Citizenship',
        'ges_code': 'B7.2.4.1',
        'bloom': 'Knowledge',
        'question_text': 'A person born in Ghana to Ghanaian parents is a citizen by:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Naturalisation', 'B) Birth', 'C) Registration', 'D) Adoption'],
        'correct_answer': 'B',
        'explanation': 'Citizenship by birth is automatic when both parents are Ghanaian nationals.',
    },
    {
        'topic': 'Conflict Resolution',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Conflict Resolution',
        'ges_code': 'B9.2.5.1',
        'bloom': 'Application',
        'question_text': 'Two ethnic groups in a village disagree over farmland. The best approach to resolve this conflict is:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Through violence', 'B) By negotiation and mediation involving elders/chiefs', 'C) By ignoring the conflict', 'D) By one group forcefully taking the land'],
        'correct_answer': 'B',
        'explanation': 'Negotiation and mediation by respected leaders is a peaceful and effective conflict resolution method.',
    },
    {
        'topic': 'Local Government',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Local Government',
        'ges_code': 'B8.2.6.1',
        'bloom': 'Comprehension',
        'question_text': 'The head of a Metropolitan Assembly in Ghana is called the:',
        'question_format': 'fill',
        'difficulty': 'medium',
        'options': [],
        'correct_answer': 'Metropolitan Chief Executive',
        'explanation': 'The Metropolitan Chief Executive (MCE) heads a Metropolitan Assembly, appointed by the President.',
    },
    {
        'topic': 'Democracy',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Democracy',
        'ges_code': 'B8.2.7.1',
        'bloom': 'Analysis',
        'question_text': 'Which of the following is a feature of a democratic society?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) One-party rule', 'B) Free and fair elections', 'C) No freedom of the press', 'D) Government by inheritance'],
        'correct_answer': 'B',
        'explanation': 'Free and fair elections are a cornerstone of democracy, allowing citizens to choose their leaders.',
    },
    {
        'topic': 'Rule of Law',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Rule of Law',
        'ges_code': 'B9.2.8.1',
        'bloom': 'Application',
        'question_text': '"No one is above the law." This statement best describes the principle of:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Separation of powers', 'B) Rule of law', 'C) Popular sovereignty', 'D) Federalism'],
        'correct_answer': 'B',
        'explanation': 'The rule of law means all persons and institutions, including the government, are accountable to the law.',
    },
    {
        'topic': 'Human Rights',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Rights and Responsibilities',
        'ges_code': 'B9.2.9.1',
        'bloom': 'Analysis',
        'question_text': 'True or False: With every right comes a corresponding responsibility.',
        'question_format': 'truefalse',
        'difficulty': 'medium',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'Rights and responsibilities go together — e.g., the right to vote comes with the responsibility to vote wisely.',
    },
    {
        'topic': 'Child Labour',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Child Rights',
        'ges_code': 'B8.2.10.1',
        'bloom': 'Synthesis',
        'question_text': 'Explain one reason why child labour is harmful to the development of a child.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Child labour deprives children of education, which limits their future opportunities and traps them in a cycle of poverty.',
        'explanation': 'Child labour affects health, education, and emotional development, violating children\'s rights.',
    },
    {
        'topic': 'Elections',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Elections',
        'ges_code': 'B9.2.11.1',
        'bloom': 'Knowledge',
        'question_text': 'In Ghana, the body responsible for conducting elections is the:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Ghana Education Service', 'B) Electoral Commission of Ghana', 'C) National Commission for Civic Education', 'D) Ghana Police Service'],
        'correct_answer': 'B',
        'explanation': 'The Electoral Commission (EC) organises and oversees all public elections and referenda in Ghana.',
    },
    {
        'topic': 'Separation of Powers',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Arms of Government',
        'ges_code': 'B9.2.2.3',
        'bloom': 'Analysis',
        'question_text': 'Why is the separation of powers important in a democracy?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'It prevents any one arm of government from becoming too powerful and ensures checks and balances.',
        'explanation': 'Separation of powers distributes authority to prevent abuse and protect citizens\' rights.',
    },
    {
        'topic': 'Duties of a Citizen',
        'strand': 'Governance, Politics and Stability',
        'sub_strand': 'Citizenship',
        'ges_code': 'B7.2.4.2',
        'bloom': 'Comprehension',
        'question_text': 'Which of the following is a duty of a Ghanaian citizen?',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Evading taxes', 'B) Paying taxes', 'C) Breaking laws', 'D) Refusing to vote'],
        'correct_answer': 'B',
        'explanation': 'Paying taxes is a civic duty that funds public services like education, healthcare, and infrastructure.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 3: SOCIO-ECONOMIC DEVELOPMENT (12 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Agriculture',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Agriculture',
        'ges_code': 'B7.3.1.1',
        'bloom': 'Knowledge',
        'question_text': 'The main cash crop of Ghana is:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Rice', 'B) Maize', 'C) Cocoa', 'D) Cassava'],
        'correct_answer': 'C',
        'explanation': 'Cocoa is Ghana\'s most important cash crop and a major source of foreign exchange.',
    },
    {
        'topic': 'Industrialisation',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Industry',
        'ges_code': 'B9.3.2.1',
        'bloom': 'Comprehension',
        'question_text': 'Industrialisation is important to Ghana\'s development because it:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Reduces the need for education', 'B) Creates employment and adds value to raw materials', 'C) Increases dependence on imports', 'D) Reduces the need for technology'],
        'correct_answer': 'B',
        'explanation': 'Industrialisation creates jobs, processes raw materials locally, and reduces dependence on imported goods.',
    },
    {
        'topic': 'Science and Technology',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Science and Technology',
        'ges_code': 'B9.3.3.1',
        'bloom': 'Application',
        'question_text': 'How has mobile phone technology improved farming in rural Ghana?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Farmers can access market prices, weather information, and mobile money services, helping them make better decisions and receive payments.',
        'explanation': 'Mobile technology bridges the information gap for rural farmers, improving market access.',
    },
    {
        'topic': 'Tourism',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Tourism',
        'ges_code': 'B8.3.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Tourism benefits Ghana\'s economy by:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Causing environmental pollution', 'B) Bringing foreign exchange and creating jobs', 'C) Reducing cultural awareness', 'D) Discouraging investment'],
        'correct_answer': 'B',
        'explanation': 'Tourism generates revenue, creates employment in hotels/restaurants, and promotes cultural exchange.',
    },
    {
        'topic': 'Tourism',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Tourism',
        'ges_code': 'B8.3.4.2',
        'bloom': 'Knowledge',
        'question_text': 'Cape Coast Castle is a major tourist attraction in Ghana because of its historical significance as:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) The first university in Ghana', 'B) A former slave trading post', 'C) The largest market in West Africa', 'D) The seat of traditional rulers'],
        'correct_answer': 'B',
        'explanation': 'Cape Coast Castle was a major centre for the transatlantic slave trade and is now a UNESCO World Heritage Site.',
    },
    {
        'topic': 'Education',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Education',
        'ges_code': 'B7.3.5.1',
        'bloom': 'Analysis',
        'question_text': 'Why is education considered the key to national development?',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'Education produces skilled workers, promotes innovation, reduces poverty, and enables citizens to participate effectively in governance.',
        'explanation': 'An educated population drives economic growth, improves health outcomes, and strengthens democracy.',
    },
    {
        'topic': 'Trade',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Trade',
        'ges_code': 'B8.3.6.1',
        'bloom': 'Comprehension',
        'question_text': 'True or False: ECOWAS promotes trade and economic cooperation among West African countries.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'ECOWAS (Economic Community of West African States) facilitates regional trade and integration.',
    },
    {
        'topic': 'Poverty',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Poverty and Development',
        'ges_code': 'B9.3.7.1',
        'bloom': 'Analysis',
        'question_text': 'Which of the following is a cause of poverty in Ghana?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Abundance of natural resources', 'B) Low levels of education and unemployment', 'C) Too many industries', 'D) Excess rainfall'],
        'correct_answer': 'B',
        'explanation': 'Low education limits job opportunities; unemployment leads to inability to meet basic needs.',
    },
    {
        'topic': 'Money and Banking',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Money',
        'ges_code': 'B7.3.8.1',
        'bloom': 'Knowledge',
        'question_text': 'The official currency of Ghana is the:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'Ghana Cedi',
        'explanation': 'The Ghana Cedi (GH₵) is the official monetary unit, managed by the Bank of Ghana.',
    },
    {
        'topic': 'Transportation',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Transportation',
        'ges_code': 'B7.3.9.1',
        'bloom': 'Application',
        'question_text': 'Good roads are important for economic development because they:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Make cars look nice', 'B) Facilitate the movement of goods and people', 'C) Reduce the population', 'D) Increase rainfall'],
        'correct_answer': 'B',
        'explanation': 'Roads enable farmers to transport produce to markets and workers to reach jobs, driving economic activity.',
    },
    {
        'topic': 'Labour',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Labour',
        'ges_code': 'B9.3.10.1',
        'bloom': 'Application',
        'question_text': 'Which of the following is a factor of production?',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Consumption', 'B) Labour', 'C) Inflation', 'D) Taxation'],
        'correct_answer': 'B',
        'explanation': 'The four factors of production are Land, Labour, Capital, and Entrepreneurship.',
    },
    {
        'topic': 'Health',
        'strand': 'Socio-Economic Development',
        'sub_strand': 'Health',
        'ges_code': 'B8.3.11.1',
        'bloom': 'Synthesis',
        'question_text': 'Explain how the National Health Insurance Scheme (NHIS) helps Ghanaians.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'The NHIS makes healthcare affordable by covering medical costs, enabling even poor citizens to access treatment without full out-of-pocket payments.',
        'explanation': 'NHIS reduces financial barriers to healthcare, improving health outcomes especially for the poor.',
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # STRAND 4: OUR NATIONHOOD (12 items)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        'topic': 'Ghana\'s Independence',
        'strand': 'Our Nationhood',
        'sub_strand': 'Independence',
        'ges_code': 'B7.4.1.1',
        'bloom': 'Knowledge',
        'question_text': 'Ghana gained independence from British colonial rule on:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) July 1, 1960', 'B) March 6, 1957', 'C) February 24, 1966', 'D) June 4, 1979'],
        'correct_answer': 'B',
        'explanation': 'Ghana became the first sub-Saharan African country to gain independence on 6th March 1957.',
    },
    {
        'topic': 'National Symbols',
        'strand': 'Our Nationhood',
        'sub_strand': 'National Symbols',
        'ges_code': 'B7.4.2.1',
        'bloom': 'Knowledge',
        'question_text': 'The colours of the Ghana flag (red, gold, green with a black star) represent respectively:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Blood, minerals, forests, African freedom', 'B) Love, sun, trees, luck', 'C) War, sand, rivers, night', 'D) Fire, gold bars, money, darkness'],
        'correct_answer': 'A',
        'explanation': 'Red = blood of ancestors, Gold = mineral wealth, Green = forests, Black Star = African freedom and emancipation.',
    },
    {
        'topic': 'Ethnic Groups',
        'strand': 'Our Nationhood',
        'sub_strand': 'Culture and Diversity',
        'ges_code': 'B7.4.3.1',
        'bloom': 'Knowledge',
        'question_text': 'The largest ethnic group in Ghana by population is the:',
        'question_format': 'mcq',
        'difficulty': 'easy',
        'options': ['A) Ga-Dangme', 'B) Ewe', 'C) Akan', 'D) Mole-Dagbani'],
        'correct_answer': 'C',
        'explanation': 'The Akan people (Ashanti, Fante, Akyem, etc.) make up about 47.5% of Ghana\'s population.',
    },
    {
        'topic': 'National Leaders',
        'strand': 'Our Nationhood',
        'sub_strand': 'Independence',
        'ges_code': 'B8.4.1.2',
        'bloom': 'Knowledge',
        'question_text': 'The first President of independent Ghana was:',
        'question_format': 'fill',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'Dr. Kwame Nkrumah',
        'explanation': 'Dr. Kwame Nkrumah led Ghana to independence and became its first President in 1960.',
    },
    {
        'topic': 'Festivals',
        'strand': 'Our Nationhood',
        'sub_strand': 'Culture and Diversity',
        'ges_code': 'B7.4.3.2',
        'bloom': 'Comprehension',
        'question_text': 'The Homowo festival is celebrated by the:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Ashanti people', 'B) Ga people', 'C) Ewe people', 'D) Dagomba people'],
        'correct_answer': 'B',
        'explanation': 'Homowo ("hooting at hunger") is a harvest festival celebrated by the Ga people of Accra.',
    },
    {
        'topic': 'National Unity',
        'strand': 'Our Nationhood',
        'sub_strand': 'Unity and Integration',
        'ges_code': 'B8.4.4.1',
        'bloom': 'Comprehension',
        'question_text': 'Inter-tribal marriages promote national unity because they:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Create conflict between families', 'B) Bridge cultural gaps and foster understanding between ethnic groups', 'C) Are financially profitable', 'D) Reduce the population'],
        'correct_answer': 'B',
        'explanation': 'Inter-ethnic marriages bring families from different backgrounds together, promoting tolerance and unity.',
    },
    {
        'topic': 'Pre-Colonial Ghana',
        'strand': 'Our Nationhood',
        'sub_strand': 'History',
        'ges_code': 'B8.4.5.1',
        'bloom': 'Comprehension',
        'question_text': 'True or False: The Ashanti Empire was one of the most powerful kingdoms in pre-colonial West Africa.',
        'question_format': 'truefalse',
        'difficulty': 'easy',
        'options': ['True', 'False'],
        'correct_answer': 'True',
        'explanation': 'The Ashanti Empire was highly organised with a strong military, gold trade, and political structure.',
    },
    {
        'topic': 'Colonialism',
        'strand': 'Our Nationhood',
        'sub_strand': 'Colonial History',
        'ges_code': 'B9.4.6.1',
        'bloom': 'Analysis',
        'question_text': 'Which of the following is a negative effect of colonialism on Ghana?',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Introduction of formal education', 'B) Exploitation of natural resources for the benefit of the colonisers', 'C) Building of roads and railways', 'D) Introduction of Christianity'],
        'correct_answer': 'B',
        'explanation': 'Colonisers extracted raw materials (gold, timber, cocoa) primarily for European industries, not local development.',
    },
    {
        'topic': 'National Development',
        'strand': 'Our Nationhood',
        'sub_strand': 'National Development',
        'ges_code': 'B9.4.7.1',
        'bloom': 'Synthesis',
        'question_text': 'As a young Ghanaian, suggest one way you can contribute to national development.',
        'question_format': 'short',
        'difficulty': 'hard',
        'options': [],
        'correct_answer': 'By studying hard to become a skilled professional who contributes productively to the economy and community.',
        'explanation': 'Individual education and skill-building directly contribute to the human capital needed for national growth.',
    },
    {
        'topic': 'Chieftaincy',
        'strand': 'Our Nationhood',
        'sub_strand': 'Traditional Authority',
        'ges_code': 'B8.4.8.1',
        'bloom': 'Application',
        'question_text': 'The role of the chief in traditional Ghanaian society includes:',
        'question_format': 'mcq',
        'difficulty': 'medium',
        'options': ['A) Collecting taxes for the central government', 'B) Settling disputes and managing community land', 'C) Running the national police', 'D) Appointing members of Parliament'],
        'correct_answer': 'B',
        'explanation': 'Chiefs traditionally serve as custodians of land, mediators of disputes, and guardians of culture.',
    },
    {
        'topic': 'Gender and Development',
        'strand': 'Our Nationhood',
        'sub_strand': 'Gender Issues',
        'ges_code': 'B9.4.9.1',
        'bloom': 'Analysis',
        'question_text': 'Gender inequality in education means:',
        'question_format': 'mcq',
        'difficulty': 'hard',
        'options': ['A) Boys and girls have the same opportunities', 'B) One gender has more access to educational opportunities than the other', 'C) All schools are mixed gender', 'D) Education is free for everyone'],
        'correct_answer': 'B',
        'explanation': 'Gender inequality in education occurs when boys or girls face barriers (cultural, economic) to accessing school.',
    },
    {
        'topic': 'National Anthem',
        'strand': 'Our Nationhood',
        'sub_strand': 'National Symbols',
        'ges_code': 'B7.4.2.2',
        'bloom': 'Knowledge',
        'question_text': 'The first line of the Ghana National Anthem is:',
        'question_format': 'short',
        'difficulty': 'easy',
        'options': [],
        'correct_answer': 'God bless our homeland Ghana',
        'explanation': 'The Ghana National Anthem begins with "God bless our homeland Ghana."',
    },
]
