# Generated by Django 5.0 on 2026-04-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='GES code, e.g. B7.1.3.1', max_length=30)),
                ('statement', models.TextField(help_text='Full content standard text')),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Content Standard',
                'ordering': ['ordering', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, default='', help_text='Optional short code, e.g. MATH, SCI', max_length=30)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curriculum Subject',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Basic 7 (JHS 1)"', max_length=60)),
                ('code', models.CharField(help_text='GES code prefix, e.g. B7, B8', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='curriculum.curriculumsubject')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'ordering': ['ordering', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='GES indicator code, e.g. B7.1.3.1.1', max_length=30)),
                ('statement', models.TextField(help_text='Full indicator statement describing what learners should do')),
                ('suggested_weeks', models.PositiveIntegerField(default=1, help_text='Suggested number of weeks for pacing')),
                ('term', models.CharField(blank=True, choices=[('first', 'Term 1'), ('second', 'Term 2'), ('third', 'Term 3')], default='', help_text='Suggested term placement per GES pacing', max_length=15)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('content_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='curriculum.contentstandard')),
            ],
            options={
                'ordering': ['ordering', 'code'],
                'unique_together': {('content_standard', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Exemplar activity description')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplars', to='curriculum.indicator')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='curriculum.gradelevel')),
            ],
            options={
                'ordering': ['ordering', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='curriculum.strand')),
            ],
            options={
                'verbose_name': 'Sub-Strand',
                'ordering': ['ordering', 'name'],
                'unique_together': {('strand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contentstandard',
            name='sub_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_standards', to='curriculum.substrand'),
        ),
        migrations.AlterUniqueTogether(
            name='contentstandard',
            unique_together={('sub_strand', 'code')},
        ),
    ]
