# Generated by Django 5.0 on 2026-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='School Name', max_length=200)),
                ('address', models.TextField(default='School Address')),
                ('phone', models.CharField(default='Phone Number', max_length=50)),
                ('email', models.EmailField(default='info@school.edu', max_length=254)),
                ('motto', models.CharField(default='Education for All', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
            ],
            options={
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
