# Generated by Django 5.0 on 2026-01-09 10:06

from django.db import migrations

def create_initial_school_info(apps, schema_editor):
    SchoolInfo = apps.get_model('academics', 'SchoolInfo')
    if not SchoolInfo.objects.exists():
        SchoolInfo.objects.create(
            name="School Name",
            address="School Address",
            phone="Phone Number",
            email="info@school.edu",
            motto="Education for All"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_schoolinfo'),
    ]

    operations = [
        migrations.RunPython(create_initial_school_info),
    ]
