# Generated by Django 5.0 on 2026-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_resource_curriculum_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='primary_color',
            field=models.CharField(default='#026e56', help_text='Main theme color (e.g. #026e56)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='secondary_color',
            field=models.CharField(default='#0f3b57', help_text='Sidebar/Dark color (e.g. #0f3b57)', max_length=7),
        ),
    ]
