# Generated by Django 5.0 on 2026-01-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_schoolinfo_primary_color_schoolinfo_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='address',
            field=models.TextField(default='School Address'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(default='info@school.edu', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='motto',
            field=models.CharField(default='Education for All', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='name',
            field=models.CharField(default='School Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(default='Phone Number', max_length=50),
        ),
    ]
