# Generated by Django 5.0 on 2026-01-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_schoolinfo_setup_complete_alter_schoolinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='homepage_template',
            field=models.CharField(choices=[('default', 'Default (Activity Feed)'), ('modern', 'Modern (Hero + Highlights)'), ('classic', 'Classic (Sidebar + Info)'), ('minimal', 'Minimal (Centered Focus)')], default='default', max_length=20),
        ),
    ]
