# Generated by Django 5.0 on 2026-02-23 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_schoolinfo_homepage_customization'),
        ('students', '0005_classexercise_studentexercisescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='id_card_template',
            field=models.CharField(choices=[('classic', 'Classic — Orange accent, clean layout'), ('modern', 'Modern — Gradient header, vibrant colors'), ('elegant', 'Elegant — Navy & gold, professional look')], default='classic', help_text='ID card design template for students and teachers', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='homepage_template',
            field=models.CharField(choices=[('default', 'Default (Activity Feed)'), ('modern', 'Modern (Hero + Highlights)'), ('classic', 'Classic (Sidebar + Info)'), ('minimal', 'Minimal (Centered Focus)'), ('playful', 'Playful (Colorful + Shapes)'), ('elegant', 'Elegant (Navy + Gold)')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='PracticeQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('questions', models.JSONField(help_text='AI-generated questions and answers')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Percentage score', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sets', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('topics_discussed', models.JSONField(blank=True, default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Student'), ('assistant', 'AI Tutor')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='academics.tutorsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
