# Generated by Django 5.0 on 2026-03-01 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_achievement_studentxp_studentachievement'),
        ('students', '0006_student_localization_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastered_topics', models.JSONField(blank=True, default=list, help_text='List of topic strings the student has demonstrated mastery of.')),
                ('active_misconceptions', models.JSONField(blank=True, default=list, help_text='Misconceptions not yet fully resolved across sessions.')),
                ('corrected_misconceptions', models.JSONField(blank=True, default=list, help_text='Misconceptions successfully corrected (historical).')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='Identified cognitive or subject-area strengths.')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='Identified areas needing improvement.')),
                ('recent_summaries', models.JSONField(blank=True, default=list, help_text='Last 10 session_summary payloads for trend analysis.')),
                ('review_queue', models.JSONField(blank=True, default=list, help_text='Topics scheduled for review: [{topic, subject, due_date, interval_days, ease_factor}].')),
                ('total_sessions_analysed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_memory', to='students.student')),
            ],
            options={
                'verbose_name': 'Learner Memory',
                'verbose_name_plural': 'Learner Memories',
            },
        ),
    ]
