# Generated by Django 5.0 on 2026-03-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_powerword'),
        ('students', '0007_add_preferred_language_and_aura_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuraSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_state', models.CharField(choices=[('IDLE', 'Not started'), ('HOOK', 'Hook'), ('NUGGET_1', 'Nugget 1'), ('NUGGET_2', 'Nugget 2'), ('NUGGET_3', 'Nugget 3'), ('NUGGET_4', 'Nugget 4'), ('NUGGET_5', 'Nugget 5'), ('STRESS_TEST', 'Stress Test'), ('DONE', 'Done')], default='IDLE', max_length=30)),
                ('vocab_level', models.IntegerField(default=3)),
                ('mood', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('frustrated', 'Frustrated')], default='neutral', max_length=20)),
                ('updated_by', models.CharField(default='text', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aura_state', to='students.student')),
            ],
            options={
                'verbose_name': 'SchoolPadi Session State',
            },
        ),
    ]
