# Generated by Django 5.0 on 2026-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_aura_session_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
