# Generated by Django 5.0 on 2026-03-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_tutorsession_title'),
        ('teachers', '0006_lessongenerationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=15)),
                ('image', models.ImageField(upload_to='schemes_of_work/')),
                ('extracted_topics', models.TextField(blank=True, default='[]', help_text='JSON array of topic strings extracted from the image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='academics.classsubject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes_of_work', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Scheme of Work',
                'verbose_name_plural': 'Schemes of Work',
                'ordering': ['-uploaded_at'],
                'unique_together': {('class_subject', 'term', 'academic_year')},
            },
        ),
    ]
