# Generated by Django 5.0 on 2026-03-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_schemeofwork'),
        ('students', '0007_add_preferred_language_and_aura_notes'),
        ('teachers', '0007_teacher_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('q1_text', models.TextField(blank=True)),
                ('q2_text', models.TextField(blank=True)),
                ('q3_text', models.TextField(blank=True)),
                ('q3_chips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_sessions', to='teachers.lessonplan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_sessions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PulseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_answer', models.BooleanField(blank=True, null=True)),
                ('q2_answer', models.BooleanField(blank=True, null=True)),
                ('q3_answer', models.CharField(blank=True, max_length=200)),
                ('is_typing', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_responses', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='academics.pulsesession')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
