# Generated by Django 5.0 on 2026-03-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_studygroupmessage_battle_type_battle_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupmessage',
            name='battle_type',
            field=models.CharField(choices=[('battle', 'Trivia Battle'), ('riddle', 'Riddle'), ('math', 'Math Challenge'), ('scrabble', 'Scrabble Challenge'), ('spell', 'Spelling Challenge (Legacy)'), ('truefalse', 'True or False')], default='battle', max_length=20),
        ),
    ]
