# Generated by Django 5.0 on 2026-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_add_admission_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='homepage_template',
            field=models.CharField(choices=[('default', 'Default (Activity Feed)'), ('modern', 'Modern (Hero + Highlights)'), ('classic', 'Classic (Sidebar + Info)'), ('minimal', 'Minimal (Centered Focus)'), ('playful', 'Playful (Colorful + Shapes)'), ('elegant', 'Elegant (Navy + Gold)'), ('artdeco', 'Art Deco (Bold Geometric)'), ('japandi', 'Japandi (Calm & Minimal)')], default='default', max_length=20),
        ),
    ]
