# Generated by Django 5.0 on 2026-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_add_japandi_artdeco_template_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_label', models.CharField(help_text='e.g. 1, A+, A', max_length=5)),
                ('remarks', models.CharField(max_length=60)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower = higher grade')),
            ],
            options={
                'verbose_name_plural': 'Grading Scale',
                'ordering': ['-min_score'],
            },
        ),
    ]
