# Generated by Django 5.0 on 2026-04-07 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_exam_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('exam', 'Examination'), ('holiday', 'Holiday / Break'), ('sport', 'Sports & Games'), ('cultural', 'Cultural / Social'), ('meeting', 'Meeting'), ('pta', 'PTA / Parents'), ('other', 'Other')], default='other', max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, help_text='Leave blank for single-day events', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('admin', 'Admin Only'), ('teachers', 'Teachers'), ('students', 'Students'), ('parents', 'Parents')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_start', 'start_time'],
            },
        ),
    ]
