# Generated by Django 5.0 on 2026-04-07 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_add_schoolevent_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_active', 'date'], name='activity_active_date_idx'),
        ),
    ]
