# Generated by Django 5.0 on 2026-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeofwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schemes_of_work/'),
        ),
    ]
